### ISSUE TITLE
IO JSON export failure

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#1145]
I try to export a JSON file using master and I get the following error.

@zeffii 
Any idea?

```python
Traceback (most recent call last):
  File "/Users/linusyng/Library/Application Support/Blender/2.78/scripts/addons/sverchok/utils/sv_IO_panel_tools.py", line 660, in execute
    destination_path += '.json'
  File "/Users/linusyng/Library/Application Support/Blender/2.78/scripts/addons/sverchok/utils/sv_IO_panel_tools.py", line 98, in write_json
    m = json.dumps(layout_dict, sort_keys=True, indent=2)
  File "/Applications/blender/blender.app/Contents/Resources/2.78/python/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/Applications/blender/blender.app/Contents/Resources/2.78/python/lib/python3.5/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Applications/blender/blender.app/Contents/Resources/2.78/python/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Applications/blender/blender.app/Contents/Resources/2.78/python/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/Applications/blender/blender.app/Contents/Resources/2.78/python/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/Applications/blender/blender.app/Contents/Resources/2.78/python/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/Applications/blender/blender.app/Contents/Resources/2.78/python/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/Applications/blender/blender.app/Contents/Resources/2.78/python/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/Applications/blender/blender.app/Contents/Resources/2.78/python/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/Applications/blender/blender.app/Contents/Resources/2.78/python/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <bpy id prop: owner="NTNodeTree", name="", address=0x117e4aaf8> is not JSON serializable
```

**Comment by ly29** [comment]
Okay, so added some debug prints to try to find the error pressed F8 and it started working. Closing for now since I can't reproduce anymore...

**Comment by zeffii** [comment]
very odd.

**Comment by ly29** [comment]
Yes it is a very odd error.

**Comment by zeffii** [comment]
I thought my edits today to iojson prevented this, but if you have a debug print that prints the name of the node currently being processed, that will be valuable.

**Comment by ly29** [comment]
same error as before with obj in mk3, had missed that issue. anyway, the F8 applied some changes from master I guess. just forget about this issue.

**Comment by zeffii** [comment]
OK

**Comment by zeffii** [comment]
but i might add something to
```python
            if isinstance(v, (float, int, str)):
                node_items[k] = v
            else:
                node_items[k] = v[:]
```
like
```python
            if isinstance(v, (float, int, str)):
                node_items[k] = v
            else:
                try:
                    node_items[k] = v[:]
                except:
                    print('tried casting ', v, 'for node named ', node.name )
```

**Comment by ly29** [comment]
Or maybe make a generic case for a ```bpy_colllection```
