### ISSUE TITLE
templates and deprecated nodes

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1526]
Recently i looked at some sverchok templates and i found that some has some deprecated nodes, so i start to look to other and i think many of them has some deprecated node. Example line node instead line mk2. Should we fix them? maybe we can change them with the newest version?

**Comment by zeffii** [comment]
good point. definitely doesn't make sense to have deprecated nodes in templates. 

If you're lucky all you have to do is change the bl_idname in the .json. That'll take someone an hour or more to go through..

**Comment by kalwalt** [comment]
i think i can do, so i will try as you suggested. I think open all the templates will be a crazy thing...

**Comment by zeffii** [comment]
i suggest replacing the node in situ, and uploading the gist here including the name of the template that it replaces.

or

make a branch, and save/overwrite gists as you get through them ;) then do a pullrequest :)

**Comment by kalwalt** [comment]
i think better to make a new branch and overwrite the json file in the branch. maybe some simpler json can be changed in the text editor but remain the fact you have to know which node is deprecated or not in the json.

**Comment by kalwalt** [comment]
I would to fix some small things more, (some broken connections) but when i try to export (for saving the json) i get this error:
```python
failed total 3
[['Text Input.001', 'Objects input.002:Matrixes', 'Matrix out.001', 'Matrix'], ['Text Input', 'Objects input:Vertices', 'Bisect', 'vertices'], ['Text Input', 'Objects input:Polygons', 'Bisect', 'edg_pol']]
Processed  Matrix out.001 in: 0.0000
cache miss: Vectors out -> Vectors from: Matrix out.001 -> Location
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/core/update_system.py", line 322, in do_update_general
    node.process()
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/nodes/vector/vector_out.py", line 40, in process
    xyz = self.inputs['Vectors'].sv_get(deepcopy=False)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/node_tree.py", line 185, in sv_get
    return SvGetSocket(self, deepcopy)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/core/socket_data.py", line 106, in SvGetSocket
    raise SvNoDataError
Node Vectors out had exception 
Traceback (most recent call last):
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 681, in execute
    layout_dict = create_dict_of_tree(ng)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 191, in create_dict_of_tree
    json_as_dict = json.loads(text_str)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/python/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/python/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/python/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 681, in execute
    layout_dict = create_dict_of_tree(ng)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 191, in create_dict_of_tree
    json_as_dict = json.loads(text_str)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/python/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/python/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/python/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

location: <unknown location>:-1

location: <unknown location>:-1
```

This  happens when i try to export the `8.CrossSection` template. notice that node do what expected.

**Comment by zeffii** [comment]
interesting

**Comment by kalwalt** [comment]
i will try again if this persist i will zip a blend file here.

**Comment by zeffii** [comment]
these days it's stored like this:
```text
   "Text in": {
      "bl_idname": "SvTextInNode",
      "color": [
        0.5,
        0.5,
        1.0
      ],
      "current_text": "Text",
      "height": 100.0,
      "hide": false,
      "label": "",
      "location": [
        -158.02481079101562,
        195.405029296875
      ],
      "params": {
        "current_text": "Text",
        "text": "Text",
        "textmode": "JSON"
      },
      "text_lines": {
        "stored_as_json": {
          "Objects in mk3:Polygons": [
            "s",
            [
              [
                [
                  0,
                  1,
                  3,
                  2
                ],
                [
                  2,
                  3,
                  7,
                  6
                ],
                [
                  6,
                  7,
                  5,
                  4
                ],
                [
                  4,
                  5,
                  1,
                  0
                ],
                [
                  2,
                  6,
                  4,
                  0
                ],
                [
                  7,
                  3,
                  1,
                  5
                ]
              ]
            ]
          ],
          "Objects in mk3:Vertices": [
            "v",
            [
              [
                [
                  -1.0,
                  -1.0,
                  -1.0
                ],
                [
                  -1.0,
                  -1.0,
                  1.0
                ],
                [
                  -1.0,
                  1.0,
                  -1.0
                ],
                [
                  -1.0,
                  1.0,
                  1.0
                ],
                [
                  1.0,
                  -1.0,
                  -1.0
                ],
                [
                  1.0,
                  -1.0,
                  1.0
                ],
                [
                  1.0,
                  1.0,
                  -1.0
                ],
                [
                  1.0,
                  1.0,
                  1.0
                ]
              ]
            ]
          ]
        }
      },
      "textmode": "JSON",
      "width": 204.04568481445312
    },
```
in that example it's being stored like:
```text
    "Text Input.001": {
      "bl_idname": "SvTextInNode",
      "color": [
        0.5,
        0.5,
        1.0
      ],
      "current_text": "Empty",
      "height": 100.0,
      "hide": false,
      "label": "",
      "location": [
        -655.5185546875,
        -354.5196228027344
      ],
      "params": {
        "current_text": "Empty",
        "text": "Empty",
        "textmode": "JSON"
      },
      "text_lines": "{\"Objects input.002:Matrixes\":[\"m\",[[[1.0,0.0,0.0,-3.6734676361083984],[0.0,1.0,0.0,-2.2040786743164062],[0.0,0.0,1.0,0.11563356965780258],[0.0,0.0,0.0,1.0]]]]}",
      "textmode": "JSON",
      "width": 140.0
    },


```

**Comment by zeffii** [comment]
i could add better parsing to the decoder.. but it's not exactly high on my todo

**Comment by zeffii** [comment]
see the decoder's assumption here..
```
    elif not current_text in texts:
        new_text = texts.new(current_text)
        if node.textmode == 'JSON':
            json_str = json.dumps(node_ref['text_lines']['stored_as_json'])
            new_text.from_string(json_str)
        else:
            new_text.from_string(node_ref['text_lines'])

```

**Comment by zeffii** [comment]
arguably, it could be changed to
```python

    # works.. but not for old stuff

    elif not current_text in texts:
        new_text = texts.new(current_text)
        if node.textmode == 'JSON':
            json_str = json.dumps(node_ref['text_lines']['stored_as_json'])
            new_text.from_string(json_str)
        else:
            new_text.from_string(node_ref['text_lines'])



    # works for old stuff too.

    elif not current_text in texts:
        new_text = texts.new(current_text)
        text_line_entry = node_ref['text_lines']
        if node.textmode == 'JSON':

            # preserve old compatibility
            if isinstance(text_line_entry, str):
                new_text.from_string(text_line_entry)

            elif isinstance(text_line_entry, dict):
                json_str = json.dumps(text_line_entry['stored_as_json'])
                new_text.from_string(json_str)
        else:
            new_text.from_string(text_line_entry)



```

**Comment by kalwalt** [comment]
@zeffii  thanks for the clarifications!

**Comment by zeffii** [comment]
see the updated code.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1579 commit that - welcome to test it.

**Comment by kalwalt** [comment]
Ok i will test it, Thank you

**Comment by kalwalt** [comment]
@zeffii now it works correctly, i'm checking what templates need some fixes and as soon as i have fix them i will ask for a pull request.

**Comment by kalwalt** [comment]
There is one thing, i post the images:
**before exporting**  (saved the nodes again because overlapping)
![before_export](https://cloud.githubusercontent.com/assets/1275858/25390257/471c0386-29d3-11e7-914a-6f4175fba0b7.png)
**after exporting** and re-loading in a nodetree again:
![after_export](https://cloud.githubusercontent.com/assets/1275858/25390291/688b8d5c-29d3-11e7-80aa-83718da8eefe.png)
In this case it's only two nodes but if multinodes are overlapping, it's became quite problematic..

**Comment by zeffii** [comment]
yeah `frames` are stored ok, but not really imported correctly from a json.. ( i never could find the energy to figure that out...)

**Comment by kalwalt** [comment]
Infact happens only with frames...since it's relatively important, we can keep this issue open as reminder.

**Comment by zeffii** [comment]
or make a fresh - dedicated issue for it.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/1244

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25393807/b7de8fb8-29dc-11e7-9da4-419ddc0279fc.png)
