### ISSUE TITLE
Macro examples

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1538]
```
"""

This file demonstrates a few features that can be used in a macro

"""
import bpy

def domo_esta(self, context):
    """ info about domo esta /// will ignore this"""
    active_node = context.active_node
    print('mouse:', context.space_data.cursor_location)
    if active_node:
        print(active_node.name)
        print(active_node.location)
        print(active_node.bl_idname)


def domo_esta4(self, context, a=10, b=140):
    """ info about domo esta4 ///"""
    print(a, b)


def windows_console(*args):
    """ show / hide console ///"""
    bpy.ops.wm.console_toggle()

```

## Some tips

in macros.py you can do any regular importing, but i recommend not importing functions directly unless you want them to be visible in the extended search menu.

```diff
- from math import floor, roof, swimmingpool
+ import math   # math won't show up in the menu because it isn't 'callable'
```
so
```diff
def some_macro(self, context):
    """ some short description ///  
    longer description if needed
    """
-    print(floor(45/2))
+    print(math.floor(45/2))
```

**Comment by zeffii** [comment]
@kalwalt  i'll show how to switch the current vdmk2 node into a bmeshviewer node..

**Comment by zeffii** [comment]
```python
def swap_vdmk2_bmeshview(self, context):
    """ hotswap vd <---> bmview """
    active_node = context.active_node
    if active_node and active_node.bl_idname == 'ViewerNode2':
        loc = active_node.location[:]

        tree = context.space_data.edit_tree
        nodes, links = tree.nodes, tree.links

        bmv = tree.nodes.new('SvBmeshViewerNodeMK2')
        bmv.location = loc

        a_inputs = active_node.inputs  
        links.new(a_inputs[0].links[0].from_socket, bmv.inputs[0])   #verts
        links.new(a_inputs[1].links[0].from_socket, bmv.inputs[2])   #edgepol
        links.new(a_inputs[2].links[0].from_socket, bmv.inputs[3])   #matrix

        nodes.remove(active_node)
        
```
![freisland](https://cloud.githubusercontent.com/assets/619340/25150874/c2298850-2483-11e7-851b-98f028da1490.gif)

**Comment by zeffii** [comment]
that's the general idea, a lot more potential error checking can be done , and it could even detect if the vdmk2 edgpol connection is coming from a socket called edges, it would hook that into the edges socket of bmviewmk2.   Currently the macro is doing the bare minimum.

**Comment by zeffii** [comment]
another macro could be randomize the hue of viewer draw...

**Comment by kalwalt** [comment]
The `swap_vdmk2_bmeshview` works for me. I start to understand the general idea. How i could load a script_lite node with a custom script?

**Comment by kalwalt** [comment]
```python
def windows_console(*args):
    """ show / hide console """
    bpy.ops.wm.console_toggle()
```
I think this is Windows only. Won't works for linux.

**Comment by kalwalt** [comment]
this load an empty script lite:
```python
def script_lite_test(self, context):
    """ load a script_lite gen /// test"""
    tree = context.space_data.edit_tree
    nodes, links = tree.nodes, tree.links
    bmv = tree.nodes.new('SvScriptNodeLite')

```

**Comment by enzyme69** [comment]
@Dealga

One day you make video tutorial of this domo esta?
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
@kalwalt 

Yes the Windows toggle is for win os only.

Regarding snlite with custom script - see how default macro "sn petal " works.

**Comment by portnov** [comment]
> another macro could be randomize the hue of viewer draw...
I think this should better be a button in the node itself.

**Comment by zeffii** [comment]
@portnov perhaps.

user defined Macros are like simple operators, that you can easily write and load without needing to add it to sverchok.

**Comment by zeffii** [comment]
@enzyme69 

> One day you make video tutorial of this

don't get your hopes up : )

**Comment by kalwalt** [comment]
> Regarding snlite with custom script - see how default macro "sn petal " works.

yes, thanks, i'm looking into it. i will post something about.

**Comment by zeffii** [comment]
i'll add a function for it to snlite's own loader operators file, that way all you have to do is 

```python
from sverchok.utils.snlite_utils import snload_from_path
from sverchok.utils.snlite_utils import snload_from_clipboard_path

def snload_my_star_file():
    snlite_node = snlite_load_from_path(___your_full_path___)
    # perform hookup if needed, with snlite_node reference

def snload_my_star_file():        
    snlite_node = snload_from_clipboard_path()
    # stuff
```

**Comment by zeffii** [comment]
or ... because the macro feature is going to be in a state of flux for a while, i'll have to think about a few things..

**Comment by kalwalt** [comment]
> or ... because the macro feature is going to be in a state of flux for a while, i'll have to think about a few things..

yes of course it's an experimental feature. Btw thank you.

**Comment by zeffii** [comment]
I think i might look for `///` in the docstring of macros, and discard those functions that don't contain that identifier.  This would allow you to import any kind of functions into macros.py, and be fairly confident that they won't show up in the extended menu.

**Comment by kalwalt** [comment]
Tryed to import a script_lite node with the `sn_petal` included.
Adding to macros.py this import:

`from sverchok.utils.sv_update_utils import sv_get_local_path`

give me this error while i try to open the extra search console:


```python
--- first time getting sv_macro_module --- 
Traceback (most recent call last):
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_extra_search.py", line 158, in invoke
    loop['results'] = gather_items()
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_extra_search.py", line 114, in gather_items
    fx_extend(idx, fx)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_extra_search.py", line 95, in fx_extend
    datastorage.append((func_name, format_macro_item(func_name, func_descriptor), '', idx))
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_extra_search.py", line 46, in format_macro_item
    return '< ' + k.replace('_', ' ') + " | " + slice_docstring(v)
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_extra_search.py", line 49, in slice_docstring
    if '///' in desc:
TypeError: argument of type 'NoneType' is not iterable

location: <unknown location>:-1

location: <unknown location>:-1


```

**Comment by zeffii** [comment]
OK.
```python
def user_macro_one(self, context):
    xy = context.space_data.cursor_location
    snlite = nodes.new('SvScriptNodeLite')
    xnlite.location = xy

    sv_path = os.path.dirname(sv_update_utils.sv_get_local_path()[0])
    snlite_template_path = os.path.join(sv_path, 'node_scripts', 'SNLite_templates')
    fullpath = os.path.join(snlite_template_path, 'petal_sine.py')
    
    txt = bpy.data.texts.load(fullpath)
    snlite.script_name = os.path.basename(txt.name)
    snlite.load()

def user_macro_two(self, context):
    xy = context.space_data.cursor_location
    snlite = nodes.new('SvScriptNodeLite')
    xnlite.location = xy
    fullpath = ___full_path_to_you_script___
    
    txt = bpy.data.texts.load(fullpath)
    snlite.script_name = os.path.basename(txt.name)
    snlite.load()
```

**Comment by zeffii** [comment]
update this page, i added some imports

**Comment by zeffii** [comment]
ok.. all functions must have a docstring..to show up in the menu.. i'm OK with that... i'll make it fail gracefully..
```python
def user_macro_one(self, context):
    """ needs docstring """

    tree = context.space_data.edit_tree
    nodes, links = tree.nodes, tree.links

    xy = context.space_data.cursor_location
    snlite = nodes.new('SvScriptNodeLite')
    xnlite.location = xy

    sv_path = os.path.dirname(sv_update_utils.sv_get_local_path()[0])
    snlite_template_path = os.path.join(sv_path, 'node_scripts', 'SNLite_templates')
    fullpath = os.path.join(snlite_template_path, 'petal_sine.py')
    
    txt = bpy.data.texts.load(fullpath)
    snlite.script_name = os.path.basename(txt.name)
    snlite.load()

```
here fullpath can be any valid path on your filesystem.. it just happens that i'm loading it from the supplied snlite templates using sv_get_local_path...  you don't have it.

**Comment by kalwalt** [comment]
i recieve this error:
```
from sverchok.utils.sv_update_utils
                                      ^
SyntaxError: invalid syntax
```
as  iread from your last post so it's not now possible.

**Comment by kalwalt** [comment]
i think you mean:
`from sverchok.utils.sv_update_utils import sv_get_local_path`

**Comment by zeffii** [comment]
very frustrating that github doesn't notify you that i've updated content in the thread : /

**Comment by zeffii** [comment]
here 

click to expand
<details>
```python
"""

This file demonstrates a few features that can be used in a macro

"""
import os
import bpy
from sverchok.utils import sv_update_utils
from sverchok.utils.sv_default_macros import DefaultMacros


def domo_esta(self, context):
    """ info about domo esta /// will ignore this"""
    active_node = context.active_node
    print('mouse:', context.space_data.cursor_location)
    if active_node:
        print(active_node.name)
        print(active_node.location)
        print(active_node.bl_idname)


def windows_console(*args):
    """ show / hide console """
    bpy.ops.wm.console_toggle()


def swap_vdmk2_bmeshview(self, context):
    """ hotswap vd <---> bmview """
    active_node = context.active_node
    if active_node and active_node.bl_idname == 'ViewerNode2':
        loc = active_node.location[:]

        tree = context.space_data.edit_tree
        nodes, links = tree.nodes, tree.links

        bmv = tree.nodes.new('SvBmeshViewerNodeMK2')
        bmv.location = loc

        a_inputs = active_node.inputs  
        links.new(a_inputs[0].links[0].from_socket, bmv.inputs[0])   #verts
        links.new(a_inputs[1].links[0].from_socket, bmv.inputs[2])   #edgepol
        links.new(a_inputs[2].links[0].from_socket, bmv.inputs[3])   #matrix

        nodes.remove(active_node)
        


def user_macro_one(self, context):
    """ needs docstring """

    DefaultMacros.ensure_nodetree(self, context)

    tree = context.space_data.edit_tree
    nodes, links = tree.nodes, tree.links

    xy = context.space_data.cursor_location
    snlite = nodes.new('SvScriptNodeLite')
    snlite.location = xy

    sv_path = os.path.dirname(sv_update_utils.sv_get_local_path()[0])
    snlite_template_path = os.path.join(sv_path, 'node_scripts', 'SNLite_templates')
    fullpath = os.path.join(snlite_template_path, 'petal_sine.py')
    
    txt = bpy.data.texts.load(fullpath)
    snlite.script_name = os.path.basename(txt.name)
    snlite.load()
```

</details>

**Comment by zeffii** [comment]
ok ..in the next update all user macros will require `///` in the docstring..else they will not show up in the menu.

**Comment by zeffii** [comment]
```python
"""

This file demonstrates a few features that can be used in a macro

"""
import os
import bpy
from sverchok.utils import sv_update_utils
from sverchok.utils.sv_default_macros import DefaultMacros


def domo_esta(self, context):
    """ info about domo esta /// will ignore this"""
    active_node = context.active_node
    print('mouse:', context.space_data.cursor_location)
    if active_node:
        print(active_node.name)
        print(active_node.location)
        print(active_node.bl_idname)


def windows_console(*args):
    """ show / hide console """
    bpy.ops.wm.console_toggle()


def swap_vdmk2_bmeshview(self, context):
    """ hotswap vd <---> bmview ///"""
    active_node = context.active_node
    if active_node and active_node.bl_idname == 'ViewerNode2':
        loc = active_node.location[:]

        tree = context.space_data.edit_tree
        nodes, links = tree.nodes, tree.links

        bmv = tree.nodes.new('SvBmeshViewerNodeMK2')
        bmv.location = loc

        a_inputs = active_node.inputs  
        links.new(a_inputs[0].links[0].from_socket, bmv.inputs[0])   #verts
        links.new(a_inputs[1].links[0].from_socket, bmv.inputs[2])   #edgepol
        links.new(a_inputs[2].links[0].from_socket, bmv.inputs[3])   #matrix

        nodes.remove(active_node)
        


def user_macro_one(self, context):
    """ needs docstring ///"""

    DefaultMacros.ensure_nodetree(self, context)

    tree = context.space_data.edit_tree
    nodes, links = tree.nodes, tree.links

    xy = context.space_data.cursor_location
    snlite = nodes.new('SvScriptNodeLite')
    snlite.location = xy

    sv_path = os.path.dirname(sv_update_utils.sv_get_local_path()[0])
    snlite_template_path = os.path.join(sv_path, 'node_scripts', 'SNLite_templates')
    fullpath = os.path.join(snlite_template_path, 'petal_sine.py')
    
    txt = bpy.data.texts.load(fullpath)
    snlite.script_name = os.path.basename(txt.name)
    snlite.load()
```

**Comment by kalwalt** [comment]
with  the latest i get again the:
 ```
 if '///' in desc:
TypeError: argument of type 'NoneType' is not iterable
```
as before

**Comment by kalwalt** [comment]
Progress:
but the problem for me is  when is searching the path. or related. Now i can load the `user_macro_two` into the nodtreeview. but  `user_macro_one` not.
This is my macros.py:

```python
"""
This file demonstrates a few features that can be used in a macro
"""
import os
import bpy
import sverchok.utils.sv_update_utils




def domo_esta(self, context):
    """ info about domo esta /// will ignore this"""
    active_node = context.active_node
    print('mouse:', context.space_data.cursor_location)
    if active_node:
        print(active_node.name)
        print(active_node.location)
        print(active_node.bl_idname)


def domo_esta4(self, context, a=10, b=140):
    """ info about domo esta4 """
    print(a, b)

def windows_console(*args):
    """ show / hide console """
    bpy.ops.wm.console_toggle()

def swap_vdmk2_bmeshview(self, context):
    """ hotswap vd <---> bmview """
    active_node = context.active_node
    if active_node and active_node.bl_idname == 'ViewerNode2':
        loc = active_node.location[:]

        tree = context.space_data.edit_tree
        nodes, links = tree.nodes, tree.links

        bmv = tree.nodes.new('SvBmeshViewerNodeMK2')
        bmv.location = loc

        a_inputs = active_node.inputs  
        links.new(a_inputs[0].links[0].from_socket, bmv.inputs[0])   #verts
        links.new(a_inputs[1].links[0].from_socket, bmv.inputs[2])   #edgepol
        links.new(a_inputs[2].links[0].from_socket, bmv.inputs[3])   #matrix

        nodes.remove(active_node)

def script_lite_test(self, context):
    """ load a script_lite gen /// test"""
    tree = context.space_data.edit_tree
    nodes, links = tree.nodes, tree.links
    bmv = tree.nodes.new('SvScriptNodeLite')

def user_macro_one(self, context):
    """ needs docstring """

    tree = context.space_data.edit_tree
    nodes, links = tree.nodes, tree.links

    xy = context.space_data.cursor_location
    snlite = nodes.new('SvScriptNodeLite')
    snlite.location = xy

    sv_path = os.path.dirname(sv_get_local_path()[0])
    snlite_template_path = os.path.join(sv_path, 'node_scripts', 'SNLite_templates')
    fullpath = os.path.join(snlite_template_path, 'petal_sine.py')
    
    txt = bpy.data.texts.load(fullpath)
    snlite.script_name = os.path.basename(txt.name)
    snlite.load()

def user_macro_two(self, context):
    """ needs docstring2"""
    tree = context.space_data.edit_tree
    nodes, links = tree.nodes, tree.links
    xy = context.space_data.cursor_location
    snlite = nodes.new('SvScriptNodeLite')
    snlite.location = xy
    fullpath = '/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/node_scripts/SNLite_templates/petal_sine.py'
    
    txt = bpy.data.texts.load(fullpath)
    snlite.script_name = os.path.basename(txt.name)
    snlite.load()
     
```
note the import at the beggining. and the difference from your.
to be clear: with `user_macro_one` i can import only an empty script_lite and i receive this error:

```
Traceback (most recent call last):
  File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/utils/sv_extra_search.py", line 152, in execute
    func(self, context)
  File "/home/walter/.config/blender/2.78/datafiles/sverchok/user_macros/macros.py", line 64, in user_macro_one
    sv_path = os.path.dirname(sv_get_local_path()[0])
NameError: name 'sv_get_local_path' is not defined

location: <unknown location>:-1

location: <unknown location>:-1

```

**Comment by zeffii** [comment]
git master pull :)

**Comment by zeffii** [comment]
this should work
```python
"""

This file demonstrates a few features that can be used in a macro

"""
import os
import bpy
from sverchok.utils import sv_update_utils
from sverchok.utils.sv_default_macros import DefaultMacros


def domo_esta(self, context):
    """ info about domo esta /// will ignore this"""
    active_node = context.active_node
    print('mouse:', context.space_data.cursor_location)
    if active_node:
        print(active_node.name)
        print(active_node.location)
        print(active_node.bl_idname)


def windows_console(*args):
    """ show / hide console ///"""
    bpy.ops.wm.console_toggle()


def swap_vdmk2_bmeshview(self, context):
    """ hotswap vd <---> bmview ///"""
    active_node = context.active_node
    if active_node and active_node.bl_idname == 'ViewerNode2':
        loc = active_node.location[:]

        tree = context.space_data.edit_tree
        nodes, links = tree.nodes, tree.links

        bmv = tree.nodes.new('SvBmeshViewerNodeMK2')
        bmv.location = loc

        a_inputs = active_node.inputs  
        links.new(a_inputs[0].links[0].from_socket, bmv.inputs[0])   #verts
        links.new(a_inputs[1].links[0].from_socket, bmv.inputs[2])   #edgepol
        links.new(a_inputs[2].links[0].from_socket, bmv.inputs[3])   #matrix

        nodes.remove(active_node)
        


def user_macro_one(self, context):
    """ needs docstring ///"""

    DefaultMacros.ensure_nodetree(self, context)

    tree = context.space_data.edit_tree
    nodes, links = tree.nodes, tree.links

    xy = context.space_data.cursor_location
    snlite = nodes.new('SvScriptNodeLite')
    snlite.location = xy

    sv_path = os.path.dirname(sv_update_utils.sv_get_local_path()[0])
    snlite_template_path = os.path.join(sv_path, 'node_scripts', 'SNLite_templates')
    fullpath = os.path.join(snlite_template_path, 'petal_sine.py')
    
    txt = bpy.data.texts.load(fullpath)
    snlite.script_name = os.path.basename(txt.name)
    snlite.load()
```

**Comment by zeffii** [comment]
btw, scripting the node tree is pretty mundane stuff, i'm sorry this is your introduction to it :)

**Comment by kalwalt** [comment]
i'm going to test it again.

**Comment by kalwalt** [comment]
Yeah this is awesome!! 
Now `user_macro_one` load the `sn_petal` script into the Nodetree view.... :champagne:

**Comment by zeffii** [comment]
cool!  you'll notice i'll wipe some posts in this thread to keep it a little short :)

**Comment by kalwalt** [comment]
yes, the important part is the final result. and adding some important notes at the top.

I have another question related to macros but i will open another issue.

**Comment by zeffii** [comment]
nooo.. stick the question here is fine

**Comment by kalwalt** [comment]
ok, we can import every sverchok node in the macro like this:
```python
def script_lite_test(self, context):
    """ load a script_lite gen /// test"""
    tree = context.space_data.edit_tree
    nodes, links = tree.nodes, tree.links
    bmv = tree.nodes.new('SvScriptNodeLite')
```
This load an empty script_lite node.  Could be possible to load a node that is not in` sverchok/nodes` path but instead sited in let's say in `sverchok/user_nodes` without the need to register in `index.md` ? In this way we could develop a macro with all the sverchok/blender methods and facilities. Much, much better from this point of view...

**Comment by zeffii** [comment]
i hope you mean `/datafiles/sverchok/user_nodes`. I see no real reason this can't be done already. here a simple example (sans licence)

**Comment by zeffii** [comment]
```python
def load_custom_node(self, context):
    """ how does this work ? ///"""
    import importlib.util as getutil

    DefaultMacros.ensure_nodetree(self, context)
    tree = context.space_data.edit_tree
    nodes, links = tree.nodes, tree.links

    datafiles = os.path.join(bpy.utils.user_resource('DATAFILES', path='sverchok', create=True))
    fullpath = os.path.join(datafiles, 'user_nodes', 'example.py')
    if os.path.exists(fullpath):
        spec = getutil.spec_from_file_location("custom_node.demo", fullpath)
        custom_node_module = getutil.module_from_spec(spec)
        spec.loader.exec_module(custom_node_module)
        custom_node_module.register()

        custom_node = nodes.new('SvFKB')
        custom_node.location = context.space_data.cursor_location
        
```

**Comment by zeffii** [comment]
but F8 is needed at the moment if you make changes to the node's code..   it's too late in the evening for me to explain this :)  I haven't tried hot-reloading

**Comment by kalwalt** [comment]
ok and thanks for the focus.  too late also for me, i will try with patience tomorrow.

**Comment by zeffii** [comment]
```python
def load_custom_node(self, context):
    """ how does this work ? ///"""
    import importlib.util as getutil

    DefaultMacros.ensure_nodetree(self, context)
    tree = context.space_data.edit_tree
    nodes, links = tree.nodes, tree.links

    datafiles = os.path.join(bpy.utils.user_resource('DATAFILES', path='sverchok', create=True))
    fullpath = os.path.join(datafiles, 'user_nodes', 'example.py')
    if os.path.exists(fullpath):
        spec = getutil.spec_from_file_location("custom_node.demo", fullpath)
        custom_node_module = getutil.module_from_spec(spec)
        spec.loader.exec_module(custom_node_module)
        try:
            custom_node_module.register()
        except Exception as err:
            print(repr(err))
            custom_node_module.unregister()
            custom_node_module.register()

        active_node = context.active_node
        if not active_node:
            custom_node = nodes.new('SvFKB')
            custom_node.location = context.space_data.cursor_location

```

this lets you edit your node's .py file... and "update it" by triggering the same macro again :)

**Comment by zeffii** [comment]
quite a bit of boilerplate there that could be tucked away into your own macro_utility module at some point..

**Comment by zeffii** [comment]
I imagine that's what i'll do as it progresses..

**Comment by zeffii** [comment]
if you change stuff in `sv_init`  an f8 / unregister / register won't know about those changes, a hard reset would be possible to some extent ( there will always be scenarios where the changed code is too big and changed too much of the node to make a 'hot swap' impossible..

anyway.. that might be a fun thing for someone else to figure out.

**Comment by kalwalt** [comment]
i added this to my `macros.py` file:
```python
def load_custom_node(self, context):
    """ This load a fake int node... ///"""
    import importlib.util as getutil

    DefaultMacros.ensure_nodetree(self, context)
    tree = context.space_data.edit_tree
    nodes, links = tree.nodes, tree.links

    datafiles = os.path.join(bpy.utils.user_resource('DATAFILES', path='sverchok', create=True))
    fullpath = os.path.join(datafiles, 'user_nodes', 'example.py')
    if os.path.exists(fullpath):
        spec = getutil.spec_from_file_location("custom_node.demo", fullpath)
        custom_node_module = getutil.module_from_spec(spec)
        spec.loader.exec_module(custom_node_module)
        try:
            custom_node_module.register()
        except Exception as err:
            print(repr(err))
            custom_node_module.unregister()
            custom_node_module.register()

        active_node = context.active_node
        if not active_node:
            custom_node = nodes.new('SvFakeIntNode')
            custom_node.location = context.space_data.cursor_location

```
and added example.py to `datafiles/sverchok/user_nodes` get it from [here](https://github.com/kalwalt/sverchok_nodes_collection/blob/master/scripts/user_nodes/example.py)
and it worls perfectly!!
SUPER!!
:1st_place_medal:

**Comment by zeffii** [comment]
maybe sverchok macros should be it's own repo, with modules

```
user_macros\macros.py
user_macros\macro_helpers.py
```
then

##### macros.py
```python
import macro_helpers

def some_macro(self, context):
    macro_helpers.hotswap(full_path_to_node)
```

**Comment by nortikin** [comment]
it have to be several menu items, but it is one first. why?

**Comment by zeffii** [comment]
@nortikin  i don't understand

**Comment by nortikin** [comment]
![0014](https://cloud.githubusercontent.com/assets/5783432/25308414/72fca33e-27bc-11e7-9df6-27252073e915.png)
```python
"""

This file demonstrates a few features that can be used in a macro

"""
import bpy

#import macro_helpers

#def some_macro(self, context):
#    """ hotswap vd <---> bmview """
#    macro_helpers.swap_vdmk2_bmeshview(self, context)

def domo_esta(self, context):
    """ info about domo esta /// will ignore this"""
    active_node = context.active_node
    print('mouse:', context.space_data.cursor_location)
    if active_node:
        print(active_node.name)
        print(active_node.location)
        print(active_node.bl_idname)


def domo_esta4(self, context, a=10, b=140):
    """ info about domo esta4 """
    print(a, b)


def windows_console(*args):
    """ show / hide console """
    bpy.ops.wm.console_toggle()

def swap_vdmk2_bmeshview(self, context):
    """ hotswap vd <---> bmview """
    active_node = context.active_node
    if active_node and active_node.bl_idname == 'ViewerNode2':
        loc = active_node.location[:]

        tree = context.space_data.edit_tree
        nodes, links = tree.nodes, tree.links

        bmv = tree.nodes.new('SvBmeshViewerNodeMK2')
        bmv.location = loc

        a_inputs = active_node.inputs  
        links.new(a_inputs[0].links[0].from_socket, bmv.inputs[0])   #verts
        links.new(a_inputs[1].links[0].from_socket, bmv.inputs[2])   #edgepol
        links.new(a_inputs[2].links[0].from_socket, bmv.inputs[3])   #matrix

        nodes.remove(active_node)
```

**Comment by zeffii** [comment]
docstring now need `///` somewhere

for example
```diff
- """ show / hide console """
+ """ show / hide console /// """
```

**Comment by nortikin** [comment]
@zeffii danke schon!!! Much of thanks!

**Comment by zeffii** [comment]
: ]

**Comment by zeffii** [comment]
tripple slash allows us to have functions in the macros.py that don't show up in the menu... like helper functions.

**Comment by zeffii** [comment]
or if you don't need a macro for a while, you can remove it's `///`.. until a time when you do need it often.

**Comment by zeffii** [comment]
I don't have much to add to this at the moment.
