### ISSUE TITLE
Bisect Multicuts question again

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1547]
I might look at older thread talking about this. But thinking a setup in Sverchok that can quickly generate a process of cutting in a brute force kind of way.... And each swapping of geometry is done via Frame Update.

So the idea is starting from a 3D object: Cube.

![screen shot 2017-04-20 at 11 03 43](https://cloud.githubusercontent.com/assets/3952687/25208642/5597dc00-25b9-11e7-8ea1-45ff2faf286a.png)
![screen shot 2017-04-20 at 11 03 26](https://cloud.githubusercontent.com/assets/3952687/25208643/55d73814-25b9-11e7-8d1b-50f3d99069db.png)

Then the cut happens to Cube -> Alpha_0
Frame 2: Alpha_0 -> Cut -> Alpha_1
Frame 3: Alpha_1 -> Cut -> Alpha_2
and iteration happens.

I will try this maybe possible.

**Comment by enzyme69** [comment]
Starting BLEND:
[sv_multiple_cut_theory_004_2017_04_20_01_10.zip](https://github.com/nortikin/sverchok/files/939177/sv_multiple_cut_theory_004_2017_04_20_01_10.zip)

Maybe Monad is better actually...

**Comment by enzyme69** [comment]
Monad gave me an error:


location: /Users/jimmygunawan/bsscript/addons/sverchok/utils/monad.py:324
Traceback (most recent call last):
  File "/Users/jimmygunawan/bsscript/addons/sverchok/utils/monad.py", line 437, in execute
    cls_ref = monad.update_cls()
  File "/Users/jimmygunawan/bsscript/addons/sverchok/core/monad.py", line 263, in update_cls
    cls_dict["output_template"] = self.generate_outputs()
  File "/Users/jimmygunawan/bsscript/addons/sverchok/core/monad.py", line 313, in generate_outputs
    socket_name, socket_bl_idname, _ = get_socket_data(socket)
  File "/Users/jimmygunawan/bsscript/addons/sverchok/core/monad.py", line 62, in get_socket_data
    return socket_name, socket_bl_idname, socket.prop_name
AttributeError: 'SvObjectSocket' object has no attribute 'prop_name'

**Comment by enzyme69** [comment]
Object In and Out Monad is not supported?
![screen shot 2017-04-20 at 11 13 47](https://cloud.githubusercontent.com/assets/3952687/25208824/734281b4-25ba-11e7-88bc-f096042b5e96.png)

**Comment by enzyme69** [comment]
Chaining like this... wonder if this can be improved.

![screen shot 2017-04-20 at 11 16 28](https://cloud.githubusercontent.com/assets/3952687/25208880/d8cdd48e-25ba-11e7-8b0e-59c9c8b969e0.png)
![screen shot 2017-04-20 at 11 16 19](https://cloud.githubusercontent.com/assets/3952687/25208881/d909c20a-25ba-11e7-9072-3bb45c6d8a1c.png)

Bisect Separate and Combine maybe...

**Comment by enzyme69** [comment]
I gotta say this is working really well, despite of one thing: Viewer BMesh naming of the Mesh needs to be adjusted manually. 

[sv_multiple_cut_theory_005_2017_04_20_01_20.zip](https://github.com/nortikin/sverchok/files/939233/sv_multiple_cut_theory_005_2017_04_20_01_20.zip)
![screen shot 2017-04-20 at 11 20 03](https://cloud.githubusercontent.com/assets/3952687/25208987/6c33771a-25bb-11e7-86d5-4b061fc2a127.png)

Maybe using some kind of Zeffii Macro that generate the nodes will resolve such matters.

**Comment by enzyme69** [comment]
Wonder if this kind of task would be better in this scenario:
- just make node that cut objects into pizze slizes (one axis, going around)
- make node that randomly slices objects
- a node that specifically does the job above

Maybe.

I am thinking maybe user can provide grease pencil that slices from that axis plane...

To be continued....
