### ISSUE TITLE
nodes that implement the "update()" might need extra try/except

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1601]
Nodes that draw using bgl/blf require a call to `update` to test if any sockets are connected (no connections means it shouldn't be drawing anything)

```python
location: <unknown location>:-1
Traceback (most recent call last):
  File "viz\viewer_mk2.py", line 332, in update
    if not (self.inputs[0].other or self.inputs[2].other):
  File "node_tree.py", line 75, in other
    return get_other_socket(self)
  File "data_structure.py", line 533, in get_other_socket
    other = socket.links[0].from_socket
IndexError: tuple index out of range
```

for example, this is triggered by clicking on the matrix socket of Viewer Draw (even if the socket is connected -- i think temporarily it is virtually unconnected between _mouse press / release_) 

```python
    def update(self):
        if not ("matrix" in self.inputs):
            return
        if not (self.inputs[0].other or self.inputs[2].other):
            callback_disable(node_id(self))        

```
it's not serious or anything, but we might have to fix it in the update ..or fix it in data_structure.py

if we fix it in the nodes, the update() would be like 
```python
    def update(self):
        if not ("matrix" in self.inputs):
            return
        try:
            if not (self.inputs[0].other or self.inputs[2].other):
                callback_disable(node_id(self))        
        except:
            print('supress virtual disconnect in vdmk2')

```

**Comment by zeffii** [comment]
i've added to viewerdraw..

**Comment by zeffii** [comment]
added to stethoschope now
