### ISSUE TITLE
Typography Viewer (alpha...) IO/JSON storage broken.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1837]
i just noticed that this is now broken. will investigate
```python
//
Exec Node Mod  -> property: dynamic_strings <class 'list'>
<class 'bpy.types.CollectionProperty'>
\\
//
Typography Viewer  -> property: lp <class 'IDPropertyArray'>
Traceback (most recent call last):
  File "sverchok\utils\sv_IO_panel_tools.py", line 874, in execute
    layout_dict = create_dict_of_tree(ng, skip_set={}, selected=False)
  File "sverchok\utils\sv_IO_panel_tools.py", line 190, in create_dict_of_tree
    print(type(node.bl_rna.properties[k]))
KeyError: 'bpy_prop_collection[key]: key "lp" not found'
```
at least the error reporting in IO/JSON gives me some confidence it can be fixed.

=======

ps... any other node that uses the same layer code will need to be checked out too.. (Curve node i think...)

**Comment by zeffii** [comment]
`self['lp']`  is used for layer choice (external buttons of Typography Viewer)..
![image](https://user-images.githubusercontent.com/619340/32404539-5df77b06-c151-11e7-8673-ef887de12b20.png)

**Comment by zeffii** [comment]
Not sure why this became broken, am pretty sure it worked at some point. Maybe sv_init will need to set `self["lp"] = [False] * 20`  or  `[True] + [False] * 19`

**Comment by zeffii** [comment]
this works again.. https://gist.github.com/b3157b2c3fa190884a72954cfe599721
