### ISSUE TITLE
Exception while exporting node tree with Profile node

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2012]
```
2018-01-05 20:41:03,255 [ERROR] sverchok.utils.sv_IO_panel_tools: TypeError('<bpy id prop: owner="NTTestingTree", name="", address=0x7f9935de10c8> is not JSON serializable',)
2018-01-05 20:41:03,256 [INFO] sverchok.utils.sv_IO_panel_tools: {'groups': {}, 'update_lists': [('Profile Parametric', 0, 'Viewer Draw', 0), ('Profile Parametric', 1, 'Viewer Draw', 1)], 'framed_nodes': {}, 'nodes': {'Viewer Draw': {'color': (1.0, 0.30000001192092896, 0.0), 'hide': False, 'params': {'activate': 1}, 'width': 140.0, 'bl_idname': 'ViewerNode2', 'location': (-329.5323791503906, 90.7144775390625), 'label': '', 'height': 100.0, 'use_custom_color': True}, 'Profile Parametric': {'hide': False, 'params': {'filename': 'Profile.txt', 'SvLists': [<bpy id prop: owner="NTTestingTree", name="", address=0x7f9935de10c8>, <bpy id prop: owner="NTTestingTree", name="", address=0x7f9935de1148>], 'extended_parsing': 1}, 'width': 140.0, 'bl_idname': 'SvProfileNodeMK2', 'location': (-544.7394409179688, 53.82294464111328), 'label': '', 'height': 100.0}}, 'export_version': '0.07'}
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 755, in execute
    write_json(layout_dict, destination_path)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 121, in write_json
    node_tree.writelines(m)
UnboundLocalError: local variable 'm' referenced before assignment
```

[profile_ref.blend.gz](https://github.com/nortikin/sverchok/files/1607030/profile_ref.blend.gz)

 Found while testing #2011 .

**Comment by zeffii** [comment]
ah yes. profileNode MK2 uses CollectionProperty , which needs (probably) to be registered to the class much like ExecNodeMod.

> TypeError('<bpy id prop: owner="NTTestingTree", name="", address=0x7f9935de10c8> is not JSON serializable',)

specifically this in the `node_dict`:

>  'SvLists': [<bpy id prop: owner="NTTestingTree",

**Comment by zeffii** [comment]
i'll sort this one out.

**Comment by zeffii** [comment]
i think this will be another instance of the need for storage_get / set for the offending node. and add the `SvLists` to the list of ignored properties. (to be collected and dealt with in storage_get / set .

for now anyway.

**Comment by zeffii** [comment]
i think the https://github.com/nortikin/sverchok/pull/2015 branch may also solve that. but to test it you need to fill the CollectionProperty property using an active curve and the prifilizer operator. Without those structures being used, all the storage_get/set is unused (iterating over empty iterables, thus storing nothing and retrieving nothing)

**Comment by zeffii** [comment]
it's a little late for me to test tonight.

**Comment by zeffii** [comment]
A generic CollectionProperty "instance" serializer function/class would be handy, there will be a few nodes to test it on.

**Comment by zeffii** [comment]
fixed with: https://github.com/nortikin/sverchok/commit/acb407a17c228f303b246d1b8835bfc73337b3e4

(mind you, only new jsons will generate enough node_dict data for PFNMK2.. but that's ok because this will never have worked anyway)..
