### ISSUE TITLE
SNL Marching Cubes example does not work

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2114]
I am looking at this thread:
https://github.com/nortikin/sverchok/issues/1549

@kalwalt  @zeffii 

Somewhat, some examples work and some does not.
pymcubes_multi_schwarz.py -- not working
pymcubes_w_noise.py -- not working
torus_iso.py -- works

Very likely something has changed with Viewer Draw or Script Node Lite ?

Error message:
```
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/ui/viewer_draw_mk2.py", line 386, in draw_callback_view
    data_vector = Vector_generate2(sl1)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/ui/viewer_draw_mk2.py", line 373, in Vector_generate2
    return [[Vector(v) for v in obj] for obj in prop]
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/ui/viewer_draw_mk2.py", line 373, in <listcomp>
    return [[Vector(v) for v in obj] for obj in prop]
TypeError: 'int' object is not iterable
0 ('StringsSocket', 'bounds', 10, 2)
1 ('StringsSocket', 'iso_val', 8.0, 2)
2 ('StringsSocket', 'samples', 100, 2)
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/ui/viewer_draw_mk2.py", line 386, in draw_callback_view
    data_vector = Vector_generate2(sl1)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/ui/viewer_draw_mk2.py", line 373, in Vector_generate2
    return [[Vector(v) for v in obj] for obj in prop]
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/ui/viewer_draw_mk2.py", line 373, in <listcomp>
    return [[Vector(v) for v in obj] for obj in prop]
TypeError: 'int' object is not iterable
vdmk2 update holdout
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/ui/viewer_draw_mk2.py", line 386, in draw_callback_view
    data_vector = Vector_generate2(sl1)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/ui/viewer_draw_mk2.py", line 373, in Vector_generate2
    return [[Vector(v) for v in obj] for obj in prop]
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/ui/viewer_draw_mk2.py", line 373, in <listcomp>
    return [[Vector(v) for v in obj] for obj in prop]
TypeError: 'int' object is not iterable

```

[kalwalt_noise_004_2018_02_06_12_57.zip](https://github.com/nortikin/sverchok/files/1699085/kalwalt_noise_004_2018_02_06_12_57.zip)

**Comment by zeffii** [comment]
please continue the old thread

**Comment by zeffii** [comment]
whenever you see :
```
  File "......../2.79/scripts/addons/sverchok-master/ui/viewer_draw_mk2.py", line 373, in <listcomp>
    return [[Vector(v) for v in obj] for obj in prop]
TypeError: 'int' object is not iterable
```
then the data in the vertex socket you are feeding into VDMK2 is not nested correctly.

**Comment by zeffii** [comment]
probably
```diff
- vertices, triangles = [verts.tolist()], [tri.tolist()]
+ vertices, triangles = [[verts.tolist()]], [[tri.tolist()]]
```
or something... compare it to the similar lines of the working scripts..

**Comment by zeffii** [comment]
i wish you always not only look at the errors in the console, but also

- reduce geometry if possible (upstream..)
- stick a `debug print` node into the output and look for yourself what the script node outputs. If that doesn't instantly show an answer. Use the console's feature to 'select all' or 'select region' and paste the output into a `gist`, and link the gist in the issue.

The reason you should disconnect the intended "next node" ...like vdmk2 (or whatever is next), is so that their inevitable exception/error/failure doesn't prevent Debug Print from being executed.
