### ISSUE TITLE
Text In CSV is broken again ...

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2135]
Can test using my old setup:
https://github.com/enzyme69/blendersushi/issues/209

Can try any of this CSV:
https://people.sc.fsu.edu/~jburkardt/data/csv/csv.html

I test with simple CSV and also not working :(

**Comment by enzyme69** [comment]
I tried many different options, none works:

Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/utils/sv_text_io_common.py", line 84, in execute
    f()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/nodes/text/text_in_mk2.py", line 230, in load
    self.load_csv()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/nodes/text/text_in_mk2.py", line 275, in load_csv
    self.load_csv_data()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/nodes/text/text_in_mk2.py", line 304, in load_csv_data
    reader = csv.reader(f, delimiter=d)
TypeError: "delimiter" must be a 1-character string

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/utils/sv_text_io_common.py", line 84, in execute
    f()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/nodes/text/text_in_mk2.py", line 230, in load
    self.load_csv()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/nodes/text/text_in_mk2.py", line 275, in load_csv
    self.load_csv_data()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/nodes/text/text_in_mk2.py", line 304, in load_csv_data
    reader = csv.reader(f, delimiter=d)
TypeError: "delimiter" must be a 1-character string

location: <unknown location>:-1

location: <unknown location>:-1
Error, no data loaded
Error, no data loaded
Error, no data loaded
Error, no data loaded
Error, no data loaded
Error, no data loaded

**Comment by enzyme69** [comment]
When I use delimiter with just a comma, it is also not working.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/36098165-30d806d0-0ffe-11e8-9e78-3530c310cfc5.png)

**Comment by zeffii** [comment]
## TypeError: "delimiter" must be a 1-character string

**Comment by zeffii** [comment]
even if the csv uses `, ` to delimit, you just leave it at default

**Comment by zeffii** [comment]
`text in+`  is fine.  In the N-panel for Text In node (also the old node has this)  you must tick "Force Input" to allow the csv reader to convert those columns that can be interpretted as numbers (they are all strings otherwise)

![image](https://user-images.githubusercontent.com/619340/36098505-712b697e-0fff-11e8-8b72-4b210f713e01.png)

**Comment by zeffii** [comment]
"why doesn't it detect whether it needs to force_input for me" 

because i forgot to make "force_input" default for `Text In+` , but if you find yourself using force_input more often than not then you should set up a default macro that enables it automatically.

sadly what is great for one person as a default, is not great for someone else. we must move on.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/36098795-93f4b126-1000-11e8-895b-a611b7a42d68.png)

![image](https://user-images.githubusercontent.com/619340/36098855-d917be7e-1000-11e8-9911-87a96004e328.png)

**Comment by enzyme69** [comment]
Ok thanks, I forgot about this "force input". Cheers~
