### ISSUE TITLE
Date Time String --- how to use this node?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2138]
```python
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/core/update_system.py", line 325, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/nodes/text/datetime_strings.py", line 121, in process
    ordinal_offset = datetime.datetime.strptime(offset[0], self.date_pattern).toordinal()
  File "/Applications/blender-2.79-macOS-10.6/blender.app/Contents/Resources/2.79/python/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/Applications/blender-2.79-macOS-10.6/blender.app/Contents/Resources/2.79/python/lib/python3.5/_strptime.py", line 346, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 18
```

<img width="592" alt="screen shot 2018-02-15 at 10 24 49 pm" src="https://user-images.githubusercontent.com/3952687/36254396-0f2a473e-129f-11e8-8334-2d90ff7f77dd.png">

**Comment by enzyme69** [comment]
<img width="599" alt="screen shot 2018-02-15 at 10 25 38 pm" src="https://user-images.githubusercontent.com/3952687/36254425-295a649a-129f-11e8-90da-ebefdbfdee24.png">

Not sure exactly how this node supposed to work. There is no documentation.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/master/docs/nodes/text/datetime_strings.rst

**Comment by zeffii** [comment]
The documentation is incomplete because i consider the node incomplete. The doc does reference the pull-request where sample usage is shown.

**Comment by nortikin** [comment]
my new insolation node must handle datetime aswell. so minimal inputs will be needed.
