### ISSUE TITLE
Sverchok cannot load and cannot install with Blender 2.79a RC

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2156]
## Problem statement

I downloaded latest Blender 2.79a RC and latest Sverchok, cannot install cannot run.. :(

```

Traceback (most recent call last):
  File "/Applications/blender-2.79a-RC/blender.app/Contents/Resources/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/__init__.py", line 79, in <module>
    node_list = make_node_list(nodes)
NameError: name 'nodes' is not defined

Traceback (most recent call last):
  File "/Applications/blender-2.79a-RC/blender.app/Contents/Resources/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/__init__.py", line 79, in <module>
    node_list = make_node_list(nodes)
NameError: name 'nodes' is not defined

```

**Comment by enzyme69** [comment]
False alarm, I need to restart Blender and it's okey now, but the SSH and update issue persists...
