### ISSUE TITLE
Experimental: Trying to run Turi Create inside Blender, maybe SV node 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2226]
I am trying to run Turi Create "Machine Learning" Module using Blender 2.79, Python 3.5.
https://github.com/apple/turicreate

So far I am getting weird error like sometimes Blender just keeps popping up many times. Maybe I am doing this wrong way?

```python
import sys
turi_path = r"/Users/jimmygunawan/anaconda3/lib/python3.5/site-packages"
#turi_path = r"/usr/local/lib/python3.5/dist-packages" #it depend on your OS but just paste the path where is mcubes
if not turi_path in sys.path:
    sys.path.append(turi_path)    
    
import turicreate as tc

style = tc.load_images('yoji/')
content = tc.load_images('content/')
model = tc.style_transfer.create(style, content, max_iterations = 10)
```

```
Traceback (most recent call last):
  File "/Users/jimmygunawan/anaconda3/lib/python3.5/site-packages/turicreate/data_structures/sarray.py", line 1916, in apply
    return SArray(_proxy=self.__proxy__.transform(fn, dtype, skip_na, seed))
  File "turicreate/cython/cy_sarray.pyx", line 130, in turicreate.cython.cy_sarray.UnitySArrayProxy.transform
  File "turicreate/cython/cy_sarray.pyx", line 141, in turicreate.cython.cy_sarray.UnitySArrayProxy.transform
RuntimeError: Cannot evaluate lambda. Lambda workers cannot not start.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/Users/jimmygunawan/anaconda3/lib/python3.5/site-packages/turicreate/toolkits/style_transfer/style_transfer.py", line 192, in create
    sequential=params['sequential_image_processing'])
  File "/Users/jimmygunawan/anaconda3/lib/python3.5/site-packages/turicreate/toolkits/style_transfer/_sframe_loader.py", line 101, in __init__
    self.sframe[_TMP_COL_PREP_IMAGE] = self.sframe[self.feature_column].apply(img_prep_fn)
  File "/Users/jimmygunawan/anaconda3/lib/python3.5/site-packages/turicreate/data_structures/sarray.py", line 1916, in apply
    return SArray(_proxy=self.__proxy__.transform(fn, dtype, skip_na, seed))
  File "/Users/jimmygunawan/anaconda3/lib/python3.5/site-packages/turicreate/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
RuntimeError: Cannot evaluate lambda. Lambda workers cannot not start.
```

**Comment by zeffii** [comment]
Jimmy, try blender stackexchangd. This problem is not sv related if you can't get text editor to run a demo script with that library.
