### ISSUE TITLE
Heat map and colours of monads

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2249]
## Problem statement

I don't understand what `heat map` does but it certainly doesn't work with `monad`s.

<details> 
  <summary>Error message</summary>  

```Python
** Sverchok loaded with 284 nodes **
Read blend: C:\Users\User\Desktop\untitled2.blend
2018-07-19 08:33:33,386 [ERROR] sverchok.core.update_system: Node Monad had exception: 'SverchGroupTree' object has no attribute 'sv_user_colors'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\core\update_system.py", line 325, in do_update_general
    node.process()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\core\monad.py", line 470, in process
    do_update(ul, monad.nodes)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\core\update_system.py", line 350, in do_update
    do_update_heat_map(node_list, nodes)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\core\update_system.py", line 252, in do_update_heat_map
    if not nodes.id_data.sv_user_colors:
AttributeError: 'SverchGroupTree' object has no attribute 'sv_user_colors'
```

</details>

## Steps to reproduce

1. Open new file create one `monad`. 
2. Go to user preferences and find `heat map` toggle in section dedicated to Sverchok. Switch on the toggle. 
3. Save user preferences.
4.  Save file.
5. Close Blender. Open the file and see the error.

## Expected result

Without errors

## Actual result

[untitled2.zip](https://github.com/nortikin/sverchok/files/2208243/untitled2.zip)

## Sverchok version

last

**Comment by zeffii** [comment]
heatmap was made and completed a long time before we introduced monads. I understand that this is a bit painful but monad is pretty rough in many areas. For now once nodes are inside a monad only the whole monad Node is considered an execution step. If someone really wanted it it could be accomplished.

for now i recommend speed testing a tree before turning it into a monad.

**Comment by zeffii** [comment]
i imagine it would be pretty neat to get per loop execution-time per node.

**Comment by zeffii** [comment]
the error suggests a missing `sv_user_colors` property in `class SverchGroupTree(NodeTree, SvNodeTreeCommon):` . I doubt that's the only error..

**Comment by zeffii** [comment]
> I don't understand what heat map does

the heatmap is supposed to (when it works) show you quickly which nodes take a lot of time to process, each node gets a color that maps (linear i think...) to the duration of the nodes `process` function.

https://github.com/nortikin/sverchok/issues/235  for more and the evolution.
