### ISSUE TITLE
Exception in module register():

### ISSUE THREAD

**Issue by gerroon** [nortikin/sverchok#2319]
Hi

I suddenly started getting this error. Sverchok was working well for a while, I am not sure what has changed :(  

I am on Windows using, has been using nightlies for  a while and SC worked always fine.

Exception in module register(): C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok_nodes\__init__.py
Traceback (most recent call last):
  File "T:\_BLENDER_BUILDS\_BLENDER_VERSIONS\blender-2.79.0-git.c66570f519f-windows64\2.79\scripts\modules\addon_utils.py", line 370, in enable
    mod.register()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok_nodes\__init__.py", line 90, in register
    sv_registration_utils.register_all(imported_modules + node_list)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok_nodes\core\__init__.py", line 23, in sv_register_modules
    m.register()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok_nodes\ui\presets.py", line 661, in register
    preset.make_add_operator()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok_nodes\ui\presets.py", line 194, in make_add_operator
    SverchPresetAddOperator.__doc__ = self.meta.get("description", self.name)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok_nodes\ui\presets.py", line 111, in meta
    if 'metainfo' in data:
TypeError: argument of type 'NoneType' is not iterable

TypeError: argument of type 'NoneType' is not iterable
search for unknown menutype NODE_MT_category_SVERCHOK_BPY_Data
uiItemM: not found NODE_MT_category_SVERCHOK_BPY_Data

C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok_nodes\ui\nodeview_space_menu.py:126
search for unknown menutype NODE_MT_category_SVERCHOK_GROUPS
uiItemM: not found NODE_MT_category_SVERCHOK_GROUPS

C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok_nodes\ui\nodeview_space_menu.py:132

**Comment by zeffii** [comment]
hi @gerroon , thanks for the notification. If we get more reports like this we can take a deeper look. Unfortunately the error you pasted does not hint at a cause, only what failed ..and once something small fails the rest burns too.

**Comment by zeffii** [comment]
but it happened in this section.. it seems.

https://github.com/nortikin/sverchok/blob/065af54b3a5b9e0aecc619c81533420a79f13d7b/ui/presets.py#L94-L116
