### ISSUE TITLE
Cannot enable addon

### ISSUE THREAD

**Issue by TWINGSISTER** [nortikin/sverchok#2348]
upon enabling Sverchok crashes trying to import glBegin. glBegin no longer in the Blender API, glBeginQuery is there.

Please describe your problem here.

## Steps to reproduce

1. 
F:\DesktopEverywhere\blender-2.80.0-git.a77b63c56943-windows32>blender --debug
Switching to fully guarded memory allocator.
Blender 2.80 (sub 40)
Build: 04/01/2019 16:09 Windows Release
argv[0] = blender
argv[1] = --debug
read file C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
  Version 280 sub 40 date 2019-01-04 21:18 hash a77b63c56943
Read prefs: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
read file
  Version 280 sub 39 date unknown hash unknown
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
found bundled python: F:\DesktopEverywhere\blender-2.80.0-git.a77b63c56943-windows32\2.80\python
Traceback (most recent call last):
  File "F:\DesktopEverywhere\blender-2.80.0-git.a77b63c56943-windows32\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-master\__init__.py", line 77, in <module>
    imported_modules = init_architecture(__name__, utils_modules, ui_modules)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-master\core\__init__.py", line 99, in init_architecture
    import_settings(imported_modules, sv_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-master\core\__init__.py", line 80, in import_settings
    settings = importlib.import_module(".settings", sv_dir_name)
  File "F:\DesktopEverywhere\blender-2.80.0-git.a77b63c56943-windows32\2.80\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-master\settings.py", line 8, in <module>
    from sverchok.core import handlers
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-master\core\handlers.py", line 10, in <module>
    from sverchok.ui import (
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-master\ui\viewer_draw_mk2.py", line 36, in <module>
    from bgl import (
ImportError: cannot import name 'glBegin' from 'bgl' (unknown location)
2. 
3. 

## Expected result

What did you expect to see as a result of those steps?

## Actual result

What did you actually get?

## Sverchok version

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by mcolinp** [comment]
I also seem to be experiencing this while attempting to install to Blender 2.8 on OSX.

[https://app.box.com/s/b7h1rr1ryvmjzcnany4jee4hnhzh4s14](url)

**Comment by mcolinp** [comment]
Yes; that seemed to be the problem. While I had seen #2299, I had not seen #2326; which did install in 2.8. 

Thanks for your help.

**Comment by zeffii** [comment]
yes @nortikin  you must use a daily build of Blender for Sverchok in 2.80.  

`bpy.context.preferences` was formerly called `bpy.context.user_preferences`.

**Comment by zeffii** [comment]
see https://github.com/nortikin/sverchok/pull/2299#issuecomment-449600523 @nortikin

**Comment by s8** [comment]
i'm still experiencing the bgl import issue on macOS 10.14.5 blender 2.80 2019-07-29 sverchok 0.6.0.0

**Comment by zeffii** [comment]
you must remove sverchok from the directories and install from the zip at #2299 instead

**Comment by zeffii** [comment]
maybe this isn't super clear

for blender 2.79 use sverchok's master branch ( the default zip )
for blender 2.8+ use sverchok's `prelease_master` branch, [available here](#2326 )
