### ISSUE TITLE
search node error (when using non master branch and update)

### ISSUE THREAD

**Issue by stansu** [nortikin/sverchok#2412]
i'm using SV 0.5.9.6 (61921c4)

error message:

Traceback (most recent call last):
  File "/home/stan/Documents/apps/blender/blender-2.79b-linux-glibc219-x86_64/2.79/scripts/addons/sverchok-gcode/utils/sv_extra_search.py", line 165, in invoke
    loop['results'] = gather_items()
  File "/home/stan/Documents/apps/blender/blender-2.79b-linux-glibc219-x86_64/2.79/scripts/addons/sverchok-gcode/utils/sv_extra_search.py", line 108, in gather_items
    fx.append((str(idx), ensure_valid_show_string(item), '', idx))
  File "/home/stan/Documents/apps/blender/blender-2.79b-linux-glibc219-x86_64/2.79/scripts/addons/sverchok-gcode/utils/sv_extra_search.py", line 66, in ensure_valid_show_string
    description = nodetype.bl_rna.get_shorthand()
AttributeError: 'Node' object has no attribute 'get_shorthand'

location: <unknown location>:-1

**Comment by stansu** [comment]
sorry guys, i found out i'm using another branch then update.
can we have branch check before update?

**Comment by enzyme69** [comment]
Had same issue,  reinstalled Sverchok and that fixed it...

**Comment by nortikin** [comment]
if you using git and make link to folder in addons directory, than in bottom right you will see branch. if you download only zip, than nothing ATM

**Comment by enzyme69** [comment]
@nortikin I have a feeling Sverchok "search" is clashing with ProcGenMode addon...

Whenever I install ProcGenMod, Sverchok search stops working:

**Comment by zeffii** [comment]
@enzyme69 , that's a separate issue  (maybe more suitable to report to the maker of that addon )
