### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2467]
## Problem statement

```Python
======================================================================
FAIL: test_ngon (simple_generator_tests.NGonNodeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\╨б╨╡╤А╨╡╨│╨╣\╨п╨╜╨┤╨╡╨║╤Б╨Ф╨╕╤Б╨║\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\tests\simple_generator_tests.py", line 51, in test_ngon
    self.assert_output_data_equals("Vertices", expected_data)
  File "D:\╨б╨╡╤А╨╡╨│╨╣\╨п╨╜╨┤╨╡╨║╤Б╨Ф╨╕╤Б╨║\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\utils\testing.py", line 552, in assert_output_data_equals
    self.assertEquals(data, expected_data, message)
AssertionError: Lists differ: [[(1.[118 chars]749475, -0.587785252292473, 0), (0.30901699437[28 chars] 0)]] != [[(1.[118 chars]749476, -0.587785252292473, 0), (0.30901699437[28 chars] 0)]]

First differing element 0:
[(1.0[117 chars]749475, -0.587785252292473, 0), (0.30901699437[27 chars], 0)]
[(1.0[117 chars]749476, -0.587785252292473, 0), (0.30901699437[27 chars], 0)]

  [[(1.0, 0.0, 0),
    (0.30901699437494745, 0.9510565162951535, 0),
    (-0.8090169943749473, 0.5877852522924732, 0),
-   (-0.8090169943749475, -0.587785252292473, 0),
?                      ^

+   (-0.8090169943749476, -0.587785252292473, 0),
?                      ^

    (0.30901699437494723, -0.9510565162951536, 0)]]

======================================================================
FAIL: test_text_viewer (simple_viewer_text_tests.TextViewerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\╨б╨╡╤А╨╡╨│╨╣\╨п╨╜╨┤╨╡╨║╤Б╨Ф╨╕╤Б╨║\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\tests\simple_viewer_text_tests.py", line 29, in test_text_viewer
    self.assertEquals(text, expected_text)
AssertionError: 'node[287 chars]865476, 0.0]\n[0.5555702330196023, 0.831469612[2832 chars]    ' != 'node[287 chars]865475, 0.0]\n[0.5555702330196023, 0.831469612[2832 chars]    '
Diff is 3514 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 84 tests in 2.852s

FAILED (failures=2, skipped=2)
```

## Steps to reproduce

1. open Blender
2. switch to Sverchok
3. press Run all tests

## Expected result

I think there should not be at least failures

## Sverchok version

Last

**Comment by portnov** [comment]
This is relatively easy to fix
1) in testing.py / assert_output_data_equals, support precision parameter and call assert_sverchok_data_equal() instead of assertEquals()
2) pass precision=5 from NGon test.
