### ISSUE TITLE
prerelease master. can not activate

### ISSUE THREAD

**Issue by hitrpr** [nortikin/sverchok#2481]
Can not activate after installation
Не активируется после установки

`Traceback (most recent call last):
  File "F:\Progs\Graphics\3d\blender 2.80\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "G:\Users\Ad.AdCOMP\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-b28_prelease_master\__init__.py", line 77, in <module>
    imported_modules = init_architecture(__name__, utils_modules, ui_modules)
  File "G:\Users\Ad.AdCOMP\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-master\core\__init__.py", line 99, in init_architecture
  File "G:\Users\Ad.AdCOMP\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-master\core\__init__.py", line 80, in import_settings
  File "F:\Progs\Graphics\3d\blender 2.80\2.80\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "G:\Users\Ad.AdCOMP\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-b28_prelease_master\settings.py", line 8, in <module>
    from sverchok.core import handlers
ImportError: cannot import name 'handlers' from 'sverchok.core' (G:\Users\Ad.AdCOMP\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sverchok-master\core\__init__.py)
`

**Comment by hitrpr** [comment]
помогла прямая устанвка из Zip копированием.
Direct unpack «sverchok» folder from zip-file helps.
