### ISSUE TITLE
Prepare new examples for 2.80 release

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2540]
It would be nice to review critically all examples that we had for 2.79.
We should select best ones and reimplement them for 2.8. Or maybe make new ones from scratch.

I would suggest to use the following principles for the new set of examples:

* Examples should be easy to understand
* Thus, most of examples should be simple enough
* We can add 1 or 2 examples of complex setups just to demonstrate that such ones are possible too.
* Most of examples should not use any scene objects, so that they could work "out of the box" without any additional configuration
* We can add a few examples that use scene objects; these must have a "note" node which describes how to get the example working.
* Most of examples should not use scripted nodes, to demonstrate how much is possible out-of-the-box;
* We can add a few examples with scripted nodes. Scripts must contain enough comments and be easily readable.
* Example names, descriptions, comments, node names... should be in English :) Well, some of Sverchok developers (and some of users) are russian, but we are working for the whole world :)
* I'd suggest to add a github wiki page with screenshots and short descriptions of all examples provided.

**Comment by zeffii** [comment]
does this work? https://gist.github.com/bd3814f6a87fa4815ace586ff3105bac

**Comment by portnov** [comment]
I was able to import it.

Though when I tried to import from URL directly, I got

```
2019-09-28 18:33:16,593 [ERROR] sverchok.utils.sv_IO_panel_tools: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>
Traceback (most recent call last):
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons_contrib/sverchok/utils/sv_IO_panel_tools.py", line 753, in read_n_decode
    content_at_url = urlopen(url)
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/portnov/SSD/soft/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>
```

**Comment by zeffii** [comment]
that seems to be a linux/python issue. cuz it works on `win64`..

**Comment by zeffii** [comment]
ah yes.. again with the SSL certification...

**Comment by portnov** [comment]
![Screenshot_20190929_214407](https://user-images.githubusercontent.com/284644/65835647-5363cd00-e302-11e9-8107-c4df9902fac3.png)

https://gist.github.com/portnov/921014d4f27a2e96d605c329d0a5ecab

**Comment by zeffii** [comment]
i suspect `formula3` wasn;t extensively passed through `json/IO`, yet.  because 
```
Traceback (most recent call last):
  File "\sverchok\nodes\number\formula3.py", line 185, in on_update
    self.adjust_sockets()
  File "\sverchok\nodes\number\formula3.py", line 252, in adjust_sockets
    self.inputs.remove(self.inputs[key])
KeyError: 'bpy_prop_collection[key]: key "y" not found'
File "\sverchok\nodes\number\formula3.py", line 184, in on_update
```
nevertheless, sverchok recovers.

**Comment by portnov** [comment]
I'll post here my thoughts on examples existing in 2.79.

`json_examples/Architecture/ROADS_LARGE_nikitron_2014.json` is a good example of complex layout. I think it worth porting to 2.8. Maybe it can be simplified by use of more modern nodes. Also it has to be translated to English.

**Comment by portnov** [comment]
`Profile reconnect` should be 1) renamed (it draws some sort of building), 2) re-implemented with more modern nodes.

**Comment by portnov** [comment]
Honestly, I'm under impression that a vast percentage of examples were put into examples just by some random "historical reasons" :)
So I'd suggest that everyone would write here which ones he likes, and we would remove all others :)

**Comment by portnov** [comment]
`Donut` is a relatively simple example of how it is possible to create non-trivial meshes "by hand", with lower-level nodes. It should be kept.

**Comment by zeffii** [comment]
> Honestly, I'm under impression that a vast percentage of examples were put into examples just by some random "historical reasons" :)

that's why it's so easy to just flick them out :) -- it's not just convenience, but also important to build examples from scratch in b28 - we likely will find bugs .

**Comment by portnov** [comment]
`Blender logo` should be ported :)

**Comment by portnov** [comment]
Blender logo for 2.8 https://gist.github.com/portnov/a1486c07f0de1f92739801497a5f9d34

**Comment by portnov** [comment]
I'm a bit tentative about adding examples to b28 master, because I'm not completely sure about quality of json export/import functionality in b28 branch yet...

**Comment by portnov** [comment]
https://gist.github.com/portnov/24028870c181500f897a49696f5f0651

![Screenshot_20191009_225354](https://user-images.githubusercontent.com/284644/66507388-89fecc00-eae8-11e9-92bd-59aedbf96e16.png)

**Comment by portnov** [comment]
https://gist.github.com/f07c634df0aa6e16a1251dc0993125fc

![Screenshot_20191020_213715](https://user-images.githubusercontent.com/284644/67162857-cd2b2b80-f381-11e9-9dd2-62f7de8c5a5c.png)

**Comment by nortikin** [comment]
what about autoconverter for jsons?
i have some code here:
It gives me list of 2.79 nodes with inputs and outputs.
Next step to replace node names in json (try to predict naming with 'oldname' 'in' 'newname')
It will help us some, but with sockets. Have we to check sockets names?
```python
import re
import inspect
import sverchok
import bpy


def GetNodesNames(node):
    reg_list = re.findall('\(\w+\)',inspect.getsource(node.register),re.M)
    out = []
    for r in reg_list:
        haha =  r[1:-1]
        if haha.endswith('Node'):
            out.append(haha)
    return out

def GetInputs(func):
    #print(func)
    inputs = re.findall('(self.inputs.new)(..)([A-Za-z]*)([,\"\'\ ]*)([A-Za-z]*)',inspect.getsource(func.sv_init),re.M)
    outputs = re.findall('(self.outputs.new)(..)([A-Za-z]*)([,\"\'\ ]*)([A-Za-z]*)',inspect.getsource(func.sv_init),re.M)
    inputs = [i[-1] for i in inputs]
    outputs = [i[-1] for i in outputs]
    return inputs, outputs

classiclass = type(sverchok.nodes.viz.empty_out)
def SvFindRegistrations():
    inputs = {}
    outputs = {}
    for groups in dir(sverchok.nodes): # example viz
        if (not groups.endswith('__')) and (not groups == 'os'):
            groups_ = getattr(sverchok.nodes,groups)
            #print(type(groups_))
            #print('_______________________',groups_)
            for node in dir(groups_): # empty_out
                node_ = getattr(groups_,node)
                if (not node.endswith('__')) and (type(node_) == classiclass):
                    #print('+++++++++++++++++',node_)
                    names = GetNodesNames(node_)
                    #print(names)
                    if names:
                        for n in names: # classes
                            func = getattr(node_,n)
                            inputs_,outputs_ = GetInputs(func)
                            inputs[n]=inputs_
                            outputs[n]=outputs_
                        
    return inputs, outputs


inputs, outputs = SvFindRegistrations()
#print(classiclass)

print('||||||||||||||outputs|||||||||||||')
a = bpy.data.texts.new('nodes_out')
for i,j in zip(outputs.keys(),outputs.values()):
    print(i,j)
    a.write(i+' '+str(j)+'\n')
    
print('||||||||||||||inputs|||||||||||||')
b = bpy.data.texts.new('nodes_in')
for i,j in zip(inputs.keys(),inputs.values()):
    print(i,j)
    b.write(i+' '+str(j)+'\n')
```

**Comment by nortikin** [comment]
```python
SvListDecomposeNode ['data']
SvIndexToMaskNode ['Index', 'mask', 'data']
SvMapRangeNode ['Value', 'Old', 'Old', 'New', 'New']
BasicSplineNode ['num', 'knot', 'ctrl', 'ctrl', 'knot']
SvFillHolesNode ['vertices', 'edges', 'Sides']
SvCalcMaskNode ['Subset', 'Set']
SvBendAlongPathNode ['Vertices', 'Path']
ListFlipNode ['data']
SvNodeRemoteNode ['auto']
SvUVtextureNode ['Object']
WifiInNode []
Hilbert3dNode ['Level', 'Size']
RandomNode ['Count', 'Seed']
VectorPolarOutNode ['Vectors']
VectorNormalNode ['Vertices', 'Polygons']
SvDebugPrintNode ['Data']
SvRandomizeVerticesNode ['Vertices', 'RandomX', 'RandomY', 'RandomZ', 'Seed']
SvNoiseNode ['Vertices']
SvBricksNode ['DU', 'DV', 'SizeU', 'SizeV', 'Toothing', 'ToothingR', 'RDU', 'RDV', 'Shift', 'RandomSeed']
SvPolygonSortNode ['Verts', 'Polys', 'Direction']
SvBMtoElementNode ['bmesh']
SvExtrudeSeparateLiteNode []
GetNormalsNode ['Vertices', 'Edges', 'Polygons']
ListSliceNode ['Data', 'Start', 'Stop']
SvExportGcodeNode ['Layer', 'Flow', 'Vertices']
SvDataShapeNode ['Data']
SvListSliceLiteNode []
ListShuffleNode ['data', 'seed']
Sv3DviewPropsNode []
Formula2Node ['X', 'n']
SvSpiralNode ['R', 'r', 'e', 't', 'n', 's', 'h', 'p', 'a']
MatrixOutNode ['Matrix']
SvSetPropNode []
SvListStatisticsNode ['Data', 'Percentage', 'Bins', 'Size']
SvMetaballOutLiteNode ['Meta', 'Types', 'Origins', 'Radius', 'Stiffness', 'Negation']
SvLampOutNode ['Origin', 'Size', 'Size', 'Size', 'Spot', 'Spot', 'Strength', 'Color']
SvEasingNode ['Float']
SvMetaballOutNode ['Types', 'Origins', 'Radius', 'Stiffness', 'Negation']
SvMixInputsNode ['f', 'A', 'B']
ListFLNode ['Data']
VectorsOutNode ['Vectors']
SvBendAlongSurfaceNode ['Vertices', 'Surface']
SvVolumeNode ['Vers', 'Pols']
SvRemoveDoublesNode ['Distance', 'Vertices', 'PolyEdge']
SvColorInputNode []
SvNumberNode ['Float']
SvMatrixApplyJoinNode ['Vertices', 'Edges', 'Faces', 'Matrices']
SvNumpyArrayNode ['x', 'y']
SvEdgeAnglesNode ['Vertices', 'Edges', 'Polygons']
SvLatticePropsNode ['Lattice', 'deformed', 'point']
IntegerNode ['Integer']
SvSuperEllipsoidNode ['SX', 'SY', 'SZ', 'XP', 'XM', 'NP', 'NM']
SvRaycasterLiteNode []
ListLengthNode ['Data']
SvQuaternionOutNode ['Quaternions']
SvInterpolationStripesNode ['Vertices', 'IntervalX', 'IntervalY', 'Attractor']
SvOBJInsolationNode ['']
SvProportionalEditNode ['Vertices', 'Mask', 'Radius']
SvParticlesMK2Node ['Object', 'Velocity', 'Location', 'Size']
SvMatrixEulerNode ['pos', 'pos', 'pos']
SvTriangulateNode ['Vertices', 'Edges', 'Polygons', 'Mask']
SvContourNode ['Distance', 'N', 'Verts', 'Edges']
SvIcosphereNode ['Subdivisions', 'Radius']
ImageNode ['vecs', 'vecs', 'Step', 'Step']
ZipNode ['data']
SvMirrorNode ['Vertices', 'Vert']
SvSwitchNode ['State', 'T', 'F']
SvUnsubdivideNode ['']
SvUVPointonMeshNode ['']
SvMaskConvertNode ['Vertices', 'Edges', 'Faces', 'VerticesMask', 'EdgesMask', 'FacesMask']
SvListModifierNode ['Data', 'Data']
SvCombinatoricsNode ['Repeat', 'Length', 'A', 'B']
SvDeleteLooseNode ['Vertices', 'PolyEdge']
SvVertSortNode ['Vertices', 'PolyEdge']
SvDeformationNode []
SvArmaturePropsNode ['Armature', 'bone']
SvExtrudeEdgesNode ['Vertices', 'Edg', 'Polygons', 'ExtrudeEdges', 'Matrices']
ScalarMathNode ['X']
SphereNode ['Radius', 'U', 'V']
SvCacheNode ['Data']
SvListSplitNode ['Data', 'Split']
SvPolygonGridNode ['Radius', 'Scale', 'Angle', 'Level', 'NumX', 'NumY']
SvSortObjsNode ['Objects', 'CustomValue']
SvBevelCurveNode ['Curve', 'BevelVerts', 'BevelEdges', 'BevelFaces', 'TaperVerts', 'Steps']
MatrixDeformNode ['Original', 'Location', 'Scale', 'Rotation', 'Angle']
SvJoinTrianglesNode ['Vertices', 'Polygons']
CylinderNode ['RadTop', 'RadBot', 'Vertices', 'Height', 'Subdivisions']
Voronoi2DNode ['Vertices', 'Clipping']
SvMatrixNormalNode ['Location', 'Normal']
SvBMoutputNode ['bmesh']
SvMeshSelectNode ['Vertices', 'Edges', 'Polygons', 'Direction', 'Center', 'Percent', 'Radius']
SvNGonNode ['Radius', 'N', 'RandomR', 'RandomPhi', 'RandomSeed', 'Shift']
SvSubdivideNode ['Vertices', 'Edges', 'Faces', 'EdgeMask', 'Cuts', 'Smooth', 'Fractal', 'AlongNormal', 'Seed']
SvKDTreePathNode ['Verts', 'maxdist', 'start']
SvSuzanneNode []
SvMeshFilterNode ['Vertices', 'Edges', 'Polygons']
SvMeshUVColorNode []
SvMatrixMathNode ['A', 'B']
SvAdaptiveEdgeNode ['VersR', 'EdgeR', 'VersD', 'EdgeD']
SvBarycentricTransformNode []
SvEmptyOutNode ['Matrix']
SvSeparateMeshNode ['Vertices', 'Poly']
SvDistancetLineLineNode []
SvSolidifyNode ['thickness', 'vertices', 'polygons']
Pols2EdgsNode ['pols']
SvLinearApproxNode ['Vertices']
SvSampleUVColorNode ['Point']
PolygonBoomNode ['vertices', 'edg']
IndexViewerNode ['vertices', 'edges', 'faces', 'matrix', 'text']
SvBisectNode ['vertices', 'edg', 'cut']
SvListInputNode []
SvBoxRoundedNode []
SvDistancePointPlaneNode []
SvQuaternionMathNode ['Scale', 'A', 'B']
SvFormulaShapeNode ['Count', 'Scale', 'XX', 'YY', 'ZZ']
SvParticlesNode ['Object']
SvSelectSimilarNode ['Vertices', 'Edges', 'Faces', 'Mask', 'Threshold']
SvTypeViewerNode ['text', 'matrix']
SvFormulaDeformMK2Node ['Verts', 'Verts']
SvOffsetNode ['Vers', 'Pols', 'Offset', 'N', 'Radius']
SvLacunarityNode ['Vertices', 'Seed', 'Distrortion']
SvHeavyTriangulateNode ['Vertices', 'Polygons']
SvImageComponentsNode []
HilbertImageNode ['Level', 'Size', 'Sensitivity']
VertsDelDoublesNode ['vers']
DelaunayTriangulation2DNode ['Vertices']
SvFixEmptyObjectsNode ['data']
SvSimpleDeformNode ['Vertices', 'Origin', 'Angle', 'Factor', 'LowLimit', 'HighLimit']
SvTorusKnotNode ['R', 'r', 'p', 'q', 'n', 'rP', 'sP']
SvIntersectPlanePlaneNode []
GenVectorsNode ['X', 'Y', 'Z']
MatrixInterpolationNode ['Factor', 'A', 'B']
SvWafelNode ['vecLine', 'vecPlane', 'edgPlane', 'thick']
ListLevelsNode ['data']
ListMatchNode ['Data', 'Data']
SvPulgaPhysicsNode []
ListRepeaterNode ['Data', 'Number']
SvBBoxNode ['Vertices']
SvCurveViewerNode ['vertices', 'edges', 'matrix']
SvLatheNode ['Verts', 'Edges', 'cent', 'axis', 'dvec', 'Degrees', 'Steps']
SvMatrixTubeNode ['Matrices', 'Vertices']
SvFlipNormalsNode ['Vertices', 'Edges', 'Polygons', 'Mask']
SvBManalyzinNode ['']
SvAttractorNode ['Vertices', 'Center', 'Direction', 'Amplitude', 'Coefficient']
SvSmoothNode ['Vertices', 'Edges', 'Faces', 'VertMask', 'Iterations', 'ClipDist', 'Factor', 'BorderFactor']
SvSubdivideLiteNode ['']
SvSculptMaskNode ['Object', 'Sculpt']
ConverterNode ['data']
AdaptivePolsNode ['VersR', 'PolsR', 'VersD', 'PolsD', 'Z']
SvEllipseNode ['Major', 'Minor', 'Num', 'Phase', 'Rotation', 'Scale']
VectorDropNode ['Vectors', 'Matrixes']
SvTurbulenceNode ['Vertices', 'Octaves', 'Hard', 'Amplitude', 'Frequency', 'Random']
MaskListNode ['data', 'mask']
SvExtrudeRegionNode ['Vertices', 'Edges', 'Polygons', 'Mask', 'Matrices', 'Height', 'Scale']
SvQuaternionInNode ['W', 'X', 'Y', 'Z', 'Scalar', 'Vector', 'Angle', 'Angle', 'Angle', 'Axis', 'Angle', 'Matrix']
SvWireframeNode ['thickness', 'Offset', 'vertices', 'polygons']
AreaNode ['Vertices', 'Polygons']
SvBVHnearNewNode []
MatrixShearNode ['Factor', 'Factor']
CrossSectionNode ['vertices', 'edg', 'matrix', 'cut']
GTextNode []
ListJoinNode ['data']
ListItem2Node ['Data', 'Item']
SvRecalcNormalsNode ['Vertices', 'Edges', 'Polygons', 'Mask']
SvCurveInputNode []
NoteNode ['Text']
SvInstancerNode ['matrix']
SvFormulaColorNode ['Colors', 'Colors']
SvOffsetLineNode ['Vers', 'Edgs', 'Offset']
ListReverseNode ['data']
EvaluateImageNode ['Verts', 'U', 'V']
SvInterpolationNode ['Vertices', 'Interval']
SvNeuroElman1LNode ['data', 'etalon']
SvTransformSelectNode []
SvCircleNode ['Radius', 'N', 'Degrees']
SvLogicNode ['X', 'Y']
SvIntersectLineSphereNode []
SvBMObjinputNode ['Objects']
SvFractalCurveNode ['Iterations', 'MinLength', 'Vertices']
SvMatrixTrackToNode ['Location', 'Scale', 'A', 'B']
MatrixApplyNode ['Vectors', 'Matrixes']
SvFilterObjsNode ['Objects', 'mask']
SvTextureViewerNode ['Float']
SvInputSwitchNode ['Selected', 'self', 'self']
ListFuncNode ['Data']
SvSplitEdgesNode ['Vertices', 'Edges', 'Factor']
SvVertMaskNode ['Mask', 'Vertices', 'Poly']
VectorPolarInNode ['rho', 'phi', 'Z']
SvDuplicateAlongEdgeNode ['Vertices', 'Edges', 'Polygons', 'Vertex', 'Vertex', 'VerticesR', 'EdgesR', 'Count', 'Padding']
SvTorusNode ['R', 'r', 'n', 'n', 'rP', 'sP', 'sT']
SvGetPropNode []
SvPipeNode ['Vers', 'Edgs', 'Diameter', 'Sides', 'Offset', 'Size', 'Extrude']
SvMeshEvalNode ['a']
SvPathLengthNode []
SvExtrudeSeparateNode []
SvConvexHullNode ['Vertices']
SvLinkedVertsNode []
WifiOutNode []
Float2IntNode ['float']
SvMeshSwitchNode ['Selected', 'Verts', 'EdgePolys']
SvIterateNode ['Matrix', 'Vertices', 'Edges', 'Polygons', 'Iterations']
SvMeshJoinNode ['Vertices', 'PolyEdge']
DistancePPNode ['vertices', 'matrix', 'vertices', 'matrix']
HilbertNode ['Level', 'Size']
svBasicArcNode ['num', 'arc']
SvBoxNode ['Size', 'Divx', 'Divy', 'Divz']
SvDiameterNode ['Vertices', 'Direction']
SvMaskJoinNode ['Mask', 'Data', 'Data']
SvDistancePointLineNode []
SvRotationNode ['Vertices', 'Center', 'Axis', 'Angle']
SvRingNode ['R', 'r', 'n', 'n', 'rP']
SvBevelNode ['']
SvGenerativeArtNode ['Vertices']
FloatNode ['Float']

```

**Comment by nortikin** [comment]
or should we generate dictionary from git commits? There are relations between all branches i guess, so renamed files should be supervised allready. We need only git-comparator

**Comment by zeffii** [comment]
> important to build examples from scratch in b28 - we likely will find bugs .

this is a good enough reason for me to not put much effort into writing any conversion code.

**Comment by nortikin** [comment]
ok, will remake waffle json now

**Comment by zeffii** [comment]
if there are a selection of examples you really think we should port, list them here. That might motivate (me or someone else) to write a quick-dirty converter tool.

**Comment by nortikin** [comment]
> if there are a selection of examples you really think we should port, list them here. That might motivate (me or someone else) to write a quick-dirty converter tool.

Ok, discribed as current 2.79 groups in examples now and write why we need it and how to organize better.

<details>

insolation (i will investigate insolation later on)
stairs from lines (it shows some concept)
tensile cover (pulga example)

greacePencil injection (basics usefull)
elfnor tree generator (knowhow)
line bevel (basics usefull)
petri spiral scale (vectorised level data concept usage)
points on face gather lines (topology)

donut (basics topology)
boolean (usefull)
flip polygon (basics list workout)
circle with legs (basics usefull)
circle fittin phisics (pulga example)
interpolations (basics all kinds of interpolations)
polar coordinates (basics usefull)
profile tissue super (example for vectorised quads with level usage)
petal egg (interpolation case please join with interpolations)

formula generators (basics math display)
zef lesson 01 (basics illustration)
leveldata example (basics correct usage of data levels)

shape keys setup (basics usefull)
l-systems (knowhow usefull)
buddah lotus (beautifull)
pelmen (proportional and vector math things)
pillow (nice example proportionsl)
elfnor topology (knowhow)
generative art l-systems (knowhow)
holes in polygons (basics usefull)
join meshes (basics usefull)
bend surface (join with interpolations json, please)


text in sverchok (basics showroom)
dance (interconnection with data, also it is greate to have audionodes interaction example)

</details>

**Comment by portnov** [comment]
The whole /r/blender seem "a little donut-happy". Well, here we go.
https://gist.github.com/5070c4ee1e56d28643e284a4a44789cb
![Screenshot_20191226_225123](https://user-images.githubusercontent.com/284644/71485374-8b5fab00-2832-11ea-976e-8a5b3117c662.png)

**Comment by portnov** [comment]
https://gist.github.com/8e162e9ddb4a5151e43aadd1af930ffb
![Screenshot_20191229_144759](https://user-images.githubusercontent.com/284644/71555178-cdfbd000-2a4a-11ea-94b8-e9dd06944f69.png)

**Comment by portnov** [comment]
https://gist.github.com/cdba3275db0a63611d300bf14d2df260

![Screenshot_20200104_000909](https://user-images.githubusercontent.com/284644/71743986-bfb51600-2e87-11ea-8c57-06ef52827ca6.png)

**Comment by portnov** [comment]
https://gist.github.com/df953c19f6d0a0d0cb4a9884b876c0c0

![Screenshot_20200104_171259](https://user-images.githubusercontent.com/284644/71765392-fdf91680-2f15-11ea-93d8-5045b857a419.png)

**Comment by portnov** [comment]
https://gist.github.com/ce25e43bee2e82a7ebbb7e3599427836

![Screenshot_20200105_010208](https://user-images.githubusercontent.com/284644/71771069-556ba680-2f57-11ea-9e48-a06cefa7fc09.png)
