### ISSUE TITLE
Cannot install version 6.0.0

### ISSUE THREAD

**Issue by sedrew** [nortikin/sverchok#2869]
Hello,

I cannot install the latest version sverchok-master.zip from github , I use the stable build 2.81a on Windows.

`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\╨┤╨╛╨╝\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\sverchok-master\__init__.py", line 74, in <module>
    node_list = make_node_list(nodes)
  File "C:\Users\╨┤╨╛╨╝\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\sverchok-master\core\__init__.py", line 55, in make_node_list
    import_modules(names, '{}.{}'.format(base_name, category), node_list)
  File "C:\Users\╨┤╨╛╨╝\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\sverchok-master\core\__init__.py", line 61, in import_modules
    im = importlib.import_module('.{}'.format(m), base)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\╨┤╨╛╨╝\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\sverchok-master\nodes\generator\icosphere.py", line 28, in <module>
    from sverchok.nodes.vector.vector_polar_in import cylindrical as from_cylindrical
ImportError: cannot import name 'cylindrical' from 'sverchok.nodes.vector.vector_polar_in' (C:\Users\╨┤╨╛╨╝\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\sverchok-master\nodes\vector\vector_polar_in.py)`

**Comment by vicdoval** [comment]
Fixed 😄  Just download it again Thanks for reporting!
