### ISSUE TITLE
UnboundLocalError: local variable 'ok' referenced before assignment

### ISSUE THREAD

**Issue by gerroon** [nortikin/sverchok#2884]
Hi

For some reason either reloading scripts (F8) or disabling and enabling Sverchok throws the error seen in the log below. 

I am on Win 10, Blender 2.82 release. 

```
Traceback (most recent call last):
  File "C:\BLENDER_28\2.82\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\sverchok\__init__.py", line 86, in register
    sv_registration_utils.register_all(imported_modules + node_list)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\sverchok\core\__init__.py", line 23, in sv_register_modules
    m.register()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\sverchok\core\handlers.py", line 213, in register
    app_handler_ops(append=handler_dict)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\sverchok\utils\__init__.py", line 115, in app_handler_ops
    print(f'sv: {operation} app.handlers')
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\run_in_console.py", line 122, in printc
    scrollback_append(sep.join(str(v) for v in args) + end, type='OUTPUT')
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\run_in_console.py", line 107, in scrollback_append
    if not ok:
UnboundLocalError: local variable 'ok' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\BLENDER_28\2.82\scripts\modules\bpy\utils\__init__.py", line 282, in load_scripts
    _addon_utils.reset_all(reload_scripts=reload_scripts)
  File "C:\BLENDER_28\2.82\scripts\modules\addon_utils.py", line 481, in reset_all
    enable(mod_name)
  File "C:\BLENDER_28\2.82\scripts\modules\addon_utils.py", line 386, in enable
    getattr(mod, "__file__", module_name),
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\run_in_console.py", line 122, in printc
    scrollback_append(sep.join(str(v) for v in args) + end, type='OUTPUT')
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\run_in_console.py", line 107, in scrollback_append
    if not ok:
UnboundLocalError: local variable 'ok' referenced before assignment

location: <unknown location>:-1

```

**Comment by zeffii** [comment]
" 2.82\scripts\addons\run_in_console.py", line 107, in scrollback_append "
the addon "run_in_console" is the origin of this error.

**Comment by gerroon** [comment]
Hi

You are right, disabling that  addon seems to resolve it however it is interesting that this only happens with Sverchok :( That addon does not complaint about other ones.

**Comment by zeffii** [comment]
gerroon, yeah Sverchok is not a trivial add-on, it has to do a lot of things in the "python reset during f9".  We can't really test it's effect in combination with all other add-ons,, realistically.  I've filed a bug report on the github issue tracker of the author (i think) of `run_in_console.py`.
