### ISSUE TITLE
figuring out the import route for Exception drawing in nodeview

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2966]
kind of annoying that this isn't simpler..
```
sys.modules['sverchok.ui.bgl_callback_nodeview']
```

**Comment by Durman** [comment]
Probably something like this can be more readable:
```Python
MODULE_NAME = 'sverchok.ui.bgl_callback_nodeview'
sys.modules[MODULE_NAME]
```

**Comment by zeffii** [comment]
the most frustrating issue here is really that i can't reproduce the cyclic import error on my win10 machine.

**Comment by Durman** [comment]
Is it really difficult? module1: `import module_2`, module2: `import module_1`. =)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2967

**Comment by zeffii** [comment]
does that work for you?

**Comment by Durman** [comment]
Yes

**Comment by zeffii** [comment]
and this?  https://github.com/nortikin/sverchok/pull/2967/commits/cb9bcb1e8b6a16aaec1b4764b623b8d5400237d8

**Comment by Durman** [comment]
No
<details> 
  <summary>error</summary>  

```
C:\Users\User\Desktop>"C:\Program Files\Blender Foundation\Blender 2.81\blender.exe"
Read prefs: C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.81\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.81\2.81\python
sv: import settings
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\User\YandexDisk\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\__init__.py", line 73, in <modul
e>
    imported_modules = init_architecture(__name__, utils_modules, ui_modules)
  File "C:\Users\User\YandexDisk\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\core\__init__.py", line 99, in i
nit_architecture
    import_settings(imported_modules, sv_name)
  File "C:\Users\User\YandexDisk\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\core\__init__.py", line 80, in i
mport_settings
    settings = importlib.import_module(".settings", sv_dir_name)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\importlib\__init__.py", line 127, in import_mod
ule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\User\YandexDisk\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\settings.py", line 8, in <module
>
    from sverchok.core import handlers
  File "C:\Users\User\YandexDisk\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\core\handlers.py", line 6, in <m
odule>
    from sverchok import old_nodes
  File "C:\Users\User\YandexDisk\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\old_nodes\__init__.py", line 28,
 in <module>
    from sverchok.node_tree import SverchCustomTreeNode
  File "C:\Users\User\YandexDisk\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\node_tree.py", line 33, in <modu
le>
    from sverchok.core.update_system import (
  File "C:\Users\User\YandexDisk\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\core\update_system.py", line 31,
 in <module>
    bgl_exceptions = sverchok.utils.exception_drawing_with_bgl
AttributeError: module 'sverchok.utils' has no attribute 'exception_drawing_with_bgl'
```

</details>

**Comment by zeffii** [comment]
cool :)

**Comment by zeffii** [comment]
i can also reproduce the error now

**Comment by Durman** [comment]
Why not `import sverchok.utils.exception_drawing_with_bgl as bgl_exceptions`?

**Comment by zeffii** [comment]
because https://github.com/nortikin/sverchok/issues/2952

**Comment by zeffii** [comment]
which i couldn't reproduce using my original code...

**Comment by Durman** [comment]
Well I have get the error by the renaming the addon folder to `Sverchok2`

**Comment by Durman** [comment]
```
...
  File "C:\Users\Home\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sverchok-master\core\__init__.py", line 99, in init_architecture
    import_settings(imported_modules, sv_name)
...
```
```Python
def import_settings(imported_modules, sv_dir_name):
    # "settings" treated separately incase the sverchok dir not named "sverchok"
    settings = importlib.import_module(".settings", sv_dir_name)
    imported_modules.append(settings)
````

**Comment by zeffii** [comment]
ah... yes..  ok.

**Comment by Durman** [comment]
I have got the idea about how it would be possible to avoid cycle importing in case one module is importing some class for `isinstance` checking from another module. 

For example module **A** is importing class **Test** from module **B**. 
This link can be broken by creating module **C**. 
Module **C** should keep class **Someable** which should be imported in both modules **A** and **B**. And class **Test** should inherited class **Someable**. 

In this case inside module **A** it would be possible to replace test with this `isinstance(obj, Someable)`

**Comment by zeffii** [comment]
I already dropped the recursive import of `node_tree` in the `bgl_callback_nodeview` ..

https://github.com/nortikin/sverchok/commit/86a1cede2ddef457130ba35c1ecbf658deecfc2e#diff-515c7117d407317f041b8b3c4475b0e8L230-R231

should be OK. now.
