### ISSUE TITLE
metaballs bug in svobj helper

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2978]
```python
2020-03-16 22:07:09,127 [ERROR] sverchok.core.update_system: Node Metaball had exception: Error: Object 'Alpha.0002' not in collection 'Master Collection'
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 351, in do_update_general
    node.process()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\viz\viewer_metaball.py", line 225, in process
    self.remove_non_updated_objects(object_index)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_obj_helper.py", line 360, in remove_non_updated_objects
    collection.objects.unlink(obj)
RuntimeError: Error: Object 'Alpha.0002' not in collection 'Master Collection'

2020-03-16 22:07:09,135 [ERROR] sverchok.core.update_system: Node Metaball had exception: local variable 'kinds' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 351, in do_update_general
    node.process()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\viz\viewer_metaball.py", line 225, in process
    self.remove_non_updated_objects(object_index)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_obj_helper.py", line 365, in remove_non_updated_objects
    kinds.remove(kinds[object_name])
UnboundLocalError: local variable 'kinds' referenced before assignment
```
one of these needs addressing :)  tomorrow. it's late now..

![image](https://user-images.githubusercontent.com/619340/76800461-01413600-67d4-11ea-99c0-2e944b0a92b6.png)

[still_life_2020_03_16_21_12.zip](https://github.com/nortikin/sverchok/files/4340418/still_life_2020_03_16_21_12.zip)

**Comment by zeffii** [comment]
i'll do a pass over the metalball node tomorrow @portnov , while it is still fresh in my mind.

**Comment by zeffii** [comment]
[still_life_2020_03_17_09_25.zip](https://github.com/nortikin/sverchok/files/4342566/still_life_2020_03_17_09_25.zip)
![image](https://user-images.githubusercontent.com/619340/76841971-d4276e80-6839-11ea-9fef-b3b9f0dd7983.png)

hmm.. i recall someone made a repeater node..

**Comment by Durman** [comment]
What do you mean by repeater node?

**Comment by zeffii** [comment]
@Durman , a node that outputs a value n times. similar to a list Repeat node, but just for numbers..

**Comment by portnov** [comment]
"Constant list".

**Comment by zeffii** [comment]
@portnov !   that;s the one

**Comment by zeffii** [comment]
@portnov  i was wondering (and being lazy..and not doing it myself)  if it would be neat to have a mode on that node that would auto-analyze the input and produce a constant for each input vector / float / int .
```
        vectors
in   :  [[v1, v2, v3, v4, v5....], [v1, v2,  ....]]

        numbers
in   :  [[n1, n2, n3, n4, n5....], [n1, n2,  ....]]

        result
out :  [[c, c, c, c, c], [c, c....]]
```

because big change that that is the way it will be used anyway..

**Comment by Durman** [comment]
There is `List match` node as well.
![2020-03-17_19-07-57](https://user-images.githubusercontent.com/28003269/76870080-a87ca680-6882-11ea-8131-195416e89ee0.png)
