### ISSUE TITLE
Matrix Out Node error 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#3023]
It seems that either Matrix Out node has some issues with the input.. (from various matrix generating nodes). Note: this is on master branch.. with the MK2 Matrix In node. Same error occurs if feeding in matrix from Matrix Euler node.

<img width="984" alt="SV-MatrixOut-Error" src="https://user-images.githubusercontent.com/2083719/78086085-e30a3700-738a-11ea-8f26-f408bfbcd010.png">

With the following error:

```
sv: version: 0.6.0.0, branch master, commit 6a5b20ea
sv: 374 nodes.
get_and_set_gl_scale_info called from sv_post_load
getting gl scale params
set render_scale to: 2.0
set render_location_xy_multiplier to: 2.0
going to add a new empty node tree
2020-03-31 20:00:59,146 [INFO] root: Initializing Sverchok logging. Blender version 2.82 (sub 7), Sverchok version 0.6.0.0, branch master, commit 6a5b20ea
Warning: going to add a new empty node tree
Warning: added new node tree

get_and_set_gl_scale_info called from Stethoscope MK2
getting gl scale params
set render_scale to: 2.0
set render_location_xy_multiplier to: 2.0
2020-03-31 20:01:06,506 [ERROR] sverchok.core.update_system: Node Stethoscope MK2 had exception: node Stethoscope MK2 (socket Data) not found in socket_data_cache
Traceback (most recent call last):
  File "/Users/atokirina/Library/Application Support/Blender/2.82/scripts/addons/sverchok/core/update_system.py", line 351, in do_update_general
    node.process()
  File "/Users/atokirina/Library/Application Support/Blender/2.82/scripts/addons/sverchok/nodes/text/stethoscope_v28.py", line 186, in process
    data = inputs[0].sv_get(deepcopy=False)
  File "/Users/atokirina/Library/Application Support/Blender/2.82/scripts/addons/sverchok/core/sockets.py", line 514, in sv_get
    return self.convert_data(SvGetSocket(self, deepcopy), implicit_conversions)
  File "/Users/atokirina/Library/Application Support/Blender/2.82/scripts/addons/sverchok/core/socket_data.py", line 107, in SvGetSocket
    raise SvNoDataError(socket, msg="not found in socket_data_cache")
sverchok.core.socket_data.SvNoDataError: node Stethoscope MK2 (socket Data) not found in socket_data_cache
2020-03-31 20:01:08,607 [ERROR] sverchok.core.update_system: Node Matrix out had exception: Matrix_location() got an unexpected keyword argument 'list'
Traceback (most recent call last):
  File "/Users/atokirina/Library/Application Support/Blender/2.82/scripts/addons/sverchok/core/update_system.py", line 351, in do_update_general
    node.process()
  File "/Users/atokirina/Library/Application Support/Blender/2.82/scripts/addons/sverchok/nodes/matrix/matrix_out.py", line 46, in process
    locs = Matrix_location(matrixes, list=True)
TypeError: Matrix_location() got an unexpected keyword argument 'list'
```

Can someone confirm this is an issue with the Matrix Out node? or perhaps with the socket converters?

**Comment by vicdoval** [comment]
Confirmed 
Please change the `list `keyword by `is_list`
https://github.com/nortikin/sverchok/blob/6a5b20ea02a404e461bae047f09d7a6cf0b1ec8b/nodes/matrix/matrix_out.py#L45-L52
```
            if L.is_linked:
                locs = Matrix_location(matrixes, is_list=True)
                L.sv_set(locs)
            if S.is_linked:
                locs = Matrix_scale(matrixes, is_list=True)
                S.sv_set(locs)
            if R.is_linked or A.is_linked:
                locs = Matrix_rotation(matrixes, is_list=True)
```
or even better (if you dont do it now i will do it soon):
change `list `and `is_list` to `to_list` in the previous lines and here:
https://github.com/nortikin/sverchok/blob/6a5b20ea02a404e461bae047f09d7a6cf0b1ec8b/data_structure.py#L679-L713

**Comment by DolphinDream** [comment]
@vicdoval please go ahead with the best fix.
