### ISSUE TITLE
SNL Voronoi 3D is broken I think

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3069]
<img width="658" alt="Screen Shot 2020-04-14 at 10 24 25 am" src="https://user-images.githubusercontent.com/3952687/79173176-1f816c80-7e3a-11ea-9627-e02b08a537d7.png">

```
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.82/scripts/addons/sverchok-master/nodes/generator/script1_lite.py", line 422, in process_script
    exec(self.script_str, locals(), locals())
  File "<string>", line 40, in <module>
TypeError: object of type 'NoneType' has no len()
2020-04-14 10:23:24,410 [ERROR] sverchok.core.update_system: Node Scripted Node Lite had exception: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.82/scripts/addons/sverchok-master/core/update_system.py", line 351, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.82/scripts/addons/sverchok-master/nodes/generator/script1_lite.py", line 307, in process
    self.process_script()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.82/scripts/addons/sverchok-master/nodes/generator/script1_lite.py", line 422, in process_script
    exec(self.script_str, locals(), locals())
  File "<string>", line 40, in <module>
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.82/scripts/addons/sverchok-master/utils/sv_bmesh_utils.py", line 47, in bmesh_from_pydata
    if len(edges) > 0:
TypeError: object of type 'NoneType' has no len()
Unexpected error: <class 'TypeError'>
on line:  47
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.82/scripts/addons/sverchok-master/nodes/generator/script1_lite.py", line 422, in process_script
    exec(self.script_str, locals(), locals())
  File "<string>", line 40, in <module>
TypeError: object of type 'NoneType' has no len()
2020-04-14 10:23:37,148 [ERROR] sverchok.core.update_system: Node Scripted Node Lite had exception: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.82/scripts/addons/sverchok-master/core/update_system.py", line 351, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.82/scripts/addons/sverchok-master/nodes/generator/script1_lite.py", line 307, in process
    self.process_script()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.82/scripts/addons/sverchok-master/nodes/generator/script1_lite.py", line 422, in process_script
    exec(self.script_str, locals(), locals())
  File "<string>", line 40, in <module>
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.82/scripts/addons/sverchok-master/utils/sv_bmesh_utils.py", line 47, in bmesh_from_pydata
    if len(edges) > 0:

```

**Comment by zeffii** [comment]
fixed.. https://github.com/nortikin/sverchok/commit/6afd4fdd5a9620fb8c58914498a533d0888ca87d

![image](https://user-images.githubusercontent.com/619340/79204431-d54dba80-7e3c-11ea-8b1f-89178ea40b00.png)

```
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.82/scripts/addons/sverchok-master/utils/sv_bmesh_utils.py", line 47, in bmesh_from_pydata
    if len(edges) > 0:
TypeError: object of type 'NoneType' has no len()
```
`bmesh_from_pydata` has changed considerably since this nodescript was written.
