### ISSUE TITLE
Subdivide Node output new/old

### ISSUE THREAD

**Issue by bstnhnsl** [nortikin/sverchok#3124]
I try to process faces I subdivided using the subdivide node and an edge mask.
But whenever I connect a node to the NewEdges/NewFaces or OldEdges/OldFaces outputs, my network breaks.

This is the Error Output for a Viewer Text node i.e.:
```
Traceback (most recent call last):
  File "/blender/2.82/scripts/addons/sverchok-master/nodes/text/viewer_text_mk3.py", line 155, in execute
    prep_text(node, num_lines)
  File "/blender/2.82/scripts/addons/sverchok-master/nodes/text/viewer_text_mk3.py", line 126, in prep_text
    eva = socket.sv_get()
  File "/blender/2.82/scripts/addons/sverchok-master/core/sockets.py", line 390, in sv_get
    source_data = SvGetSocket(self, deepcopy = True if self.needs_data_conversion() else deepcopy)
  File "/blender/2.82/scripts/addons/sverchok-master/core/socket_data.py", line 107, in SvGetSocket
    raise SvNoDataError(socket, msg="not found in socket_data_cache")
sverchok.core.socket_data.SvNoDataError: node Viewer text mk3 (socket data0) not found in socket_data_cache
```

Not quite sure if I'm misusing the outputs or it's a bug.

![Brut_Sverchok](https://user-images.githubusercontent.com/3930204/80372913-8ff5a800-8894-11ea-837d-db1965a9aa08.png)

I'm on Blender 2.82, Sverchok 0.6.0.0 (476f26d)

**Comment by vicdoval** [comment]
Now should work, just update Sverchok.
Thanks for reporting :) !!
