### ISSUE TITLE
broken tests

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3191]
what's the deal with the `intersecting_planes.blend.gz` ?

![image](https://user-images.githubusercontent.com/619340/81493981-41d5a100-92a5-11ea-8dc8-a75f7e421573.png)

is this to test deprecated nodes in the nodetree?

**Comment by portnov** [comment]
No, one has to replace deprecated nodes with new ones...

**Comment by enzyme69** [comment]
I thought that "refresh node tree" will automagically fix it with newer
version of the nodes
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
@portnov  cool, maybe i'll get around to it.

another question, here's a snippet of the test log. I'm struggling to find what blend/json/whatever is being triggered to cause the error
```
2020-05-10 08:55:14,105 [INFO] profile_mk3_tests: Checking profile example: quadratic_fillet.txt
2020-05-10 08:55:14,140 [INFO] sverchok.utils.sv_IO_panel_tools: ############0.079
2020-05-10 08:55:14,147 [INFO] sverchok.utils.sv_IO_panel_tools: ############0.079
2020-05-10 08:55:14,155 [INFO] sverchok.utils.sv_IO_panel_tools: ############0.079
2020-05-10 08:55:14,201 [ERROR] sverchok.core.update_system: Node Object ID Set MK2 had exception: 'tuple' object has no attribute 'delta_location'
Traceback (most recent call last):
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.82/scripts/addons/sverchok/core/update_system.py", line 383, in do_update_general
    node.process()
  File "/home/travis/build/nortikin/sverchok/installation/blender/2.82/scripts/addons/sverchok/nodes/object_nodes/set_blenddata2.py", line 82, in process
    exec("for OL in objs:\n    for i in OL:\n        i."+Prop)
  File "<string>", line 3, in <module>
AttributeError: 'tuple' object has no attribute 'delta_location'
2020-05-10 08:55:14,214 [INFO] sverchok.utils.testing: ---- Linked text block: /home/travis/build/nortikin/sverchok/installation/blender/2.82/scripts/addons/sverchok/tests/references/mesh_expr_ref.blend.gz
2020-05-10 08:55:14,220 [INFO] sverchok.utils.testing: ---- Linked node tree: /home/travis/build/nortikin/sverchok/installation/blender/2.82/scripts/addons/sverchok/tests/references/mesh_expr_ref.blend.gz
```
now in that example `objs` is an ngon of  ( i know because i added a print statement temporarily)
```
[[(1.0, 0.0, 0), (0.30901699437494745, 0.9510565162951535, 0), (-0.8090169943749473, 0.5877852522924732, 0), (-0.8090169943749476, -0.587785252292473, 0), (0.30901699437494723, -0.9510565162951536, 0)]]
```
so yeah `AttributeError: 'tuple' object has no attribute 'delta_location'`  is understood, but do you know how the nodetree is getting into that state?  i'm missing some obvious printouts of what test is being performed.

**Comment by zeffii** [comment]
i'm going to add 
```
        info(('#' * 12) + nodes_json['export_version'])
        info(f"full path to this test {fullpath}")
```

**Comment by zeffii** [comment]
ah ha.. `sverchok/tests/references/torus.json`

**Comment by zeffii** [comment]
nope.. that's not it.

**Comment by zeffii** [comment]
..so what is executed/imported between 

- test/references  *.*
- ?
- Linked text block:  tests/references/mesh_expr_ref.blend.gz

**Comment by zeffii** [comment]
ok..
```
def run_all_tests(pattern=None):
    """
    Run all existing test cases.
    Test cases are looked up under tests/ directory.
    """
    
    if pattern is None:
        pattern = "*_tests.py"

    tests_path = get_tests_path()
    log_handler = logging.FileHandler(join(tests_path, "sverchok_tests.log"), mode='w')
    logging.getLogger().addHandler(log_handler)
    try:
        loader = unittest.TestLoader()
        suite = loader.discover(start_dir = tests_path, pattern = pattern)
        buffer = StringIO()
        runner = unittest.TextTestRunner(stream = buffer, verbosity=2)
        with coverage_report():
            result = runner.run(suite)
            info("Test cases result:\n%s", buffer.getvalue())
            return result
    finally:
        logging.getLogger().removeHandler(log_handler)
```

huh ?

**Comment by zeffii** [comment]
there we go.. socket conversion tests.
