### ISSUE TITLE
Save as preset

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3311]
Looks like presets does not take frame nodes into account.

![2020-06-03_15-36-00](https://user-images.githubusercontent.com/28003269/83632211-f4043e00-a5af-11ea-930d-6fdf2264acf6.png)

```Text
Error: Traceback (most recent call last):
  File "D:\╨б╨╡╤А╨╡╨│╨╣\╨п╨╜╨┤╨╡╨║╤Б╨Ф╨╕╤Б╨║\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\ui\presets.py", line 400, in execute
    layout_dict = create_dict_of_tree(ng, selected=True, save_defaults = self.save_defaults)
  File "D:\╨б╨╡╤А╨╡╨│╨╣\╨п╨╜╨┤╨╡╨║╤Б╨Ф╨╕╤Б╨║\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\utils\sv_IO_panel_tools.py", line 297, in create_dict_of_tree
    node_props = get_node_annotations(node)
  File "D:\╨б╨╡╤А╨╡╨│╨╣\╨п╨╜╨┤╨╡╨║╤Б╨Ф╨╕╤Б╨║\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\utils\sv_IO_panel_tools.py", line 262, in get_node_annotations
    for key, ann in node.bl_rna.__annotations__.items():
AttributeError: 'NodeFrame' object has no attribute '__annotations__'
```

**Comment by portnov** [comment]
I think we should just disable this menu for frame nodes.

**Comment by Durman** [comment]
I'm not quite understand how node tree is saving into preset. Has it matter which node is active for creating preset?

**Comment by portnov** [comment]
"Presets" menu of the node (Shift-P or submenu in the right-click menu) is about "per-node" presets, such presets must contain exactly one node always. And it obviously has no sense to make presets of frames — there is nothing to configure in them.

**Comment by Durman** [comment]
Now I got it. This function definitely should be named more clear, probably something like `node preset`. Because I thought it is about of creating of a tree preset.
