### ISSUE TITLE
Object ID - cannot count total object length

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3324]
<img width="710" alt="Screen Shot 2020-06-07 at 8 44 41 am" src="https://user-images.githubusercontent.com/3952687/83955891-3b821700-a89b-11ea-8537-c9d7c44914f1.png">

```
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/core/update_system.py", line 383, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/list_main/length.py", line 45, in process
    out = self.count(data, self.level)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/list_main/length.py", line 55, in count
    out = [self.count(obj, level-1) for obj in data]
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/list_main/length.py", line 55, in <listcomp>
    out = [self.count(obj, level-1) for obj in data]
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/list_main/length.py", line 53, in count
    return [self.count(obj, level-1) for obj in data]
TypeError: 'Object' object is not iterable
```

Something seems broken, I cannot count the number of objects (list length) using Object ID Select

**Comment by enzyme69** [comment]
Level 0 do the job.
<img width="846" alt="Screen Shot 2020-06-07 at 8 47 06 am" src="https://user-images.githubusercontent.com/3952687/83955912-797f3b00-a89b-11ea-9823-6979e869d8db.png">


Never mind.
