### ISSUE TITLE
FreeCAD loading

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#3409]
## Problem statement
writing error (but it works):

```bash
PyMCubes package is not available. PyMCubes-based implementation of Marching Cubes will not be available
FreeCAD 0.18, Libs: 0.18R
No modules found in /usr/lib/freecad-python3/Mod
During initialization the error No module named 'freecad' occurred
Dependencies available: pip, scipy, geomdl, scikit-image, circlify, lbt-ladybug, FreeCAD.

2020-07-19 04:01:52,840 [INFO] sverchok_extra.dependencies: Dependencies available: pip, scipy, geomdl, scikit-image, circlify, lbt-ladybug.
Exception in module register(): /home/ololo/.config/blender/2.82/scripts/addons/sverchok-extra/__init__.py
Traceback (most recent call last):
File "/home/ololo/Downloads/INSTALL/blender-2.82-linux64/2.82/scripts/modules/addon_utils.py", line 382, in enable
mod.register()
File "/home/ololo/.config/blender/2.82/scripts/addons/sverchok-extra/__init__.py", line 179, in register
icons.register()
File "/home/ololo/.config/blender/2.82/scripts/addons/sverchok-extra/icons.py", line 23, in register
register_custom_icon_provider("sverchok_extra", SvExIconProvider())
File "/home/ololo/.config/blender/2.82/scripts/addons/sverchok/ui/sv_icons.py", line 34, in register_custom_icon_provider
record.init(custom_icons)
File "/home/ololo/.config/blender/2.82/scripts/addons/sverchok/ui/sv_icons.py", line 21, in init
custom_icons.load(icon_id, path, "IMAGE")
File "/home/ololo/Downloads/INSTALL/blender-2.82-linux64/2.82/scripts/modules/bpy/utils/previews.py", line 97, in load
raise KeyError("key {name!r} already exists")
KeyError: 'key {name!r} already exists'
get_and_set_gl_scale_info called from sv_post_load
getting gl scale params
set render_scale to: 1.0
set render_location_xy_multiplier to: 1.0
/home/ololo/.config/blender/2.82/scripts/addons/sverchok/settings.py:384
Info: See 'settings.py' in the text editor
```

## Steps to reproduce

1. sudo apt install libfreecad-python3-0.18
2. path to freecad lib /usr/lib/freecad-python3/lib/
3. load blender with SV

## Expected result

No error

## Actual result

Error

## Sverchok version

git master 2020-06-19

**Comment by nortikin** [comment]
is it critical that it:
```No modules found in /usr/lib/freecad-python3/Mod```?

**Comment by portnov** [comment]
It works for me with this message. Have no idea what it means. It seems freecad library outputs it by itself.
