### ISSUE TITLE
Hadley Attractors script

### ISSUE THREAD

**Issue by DaveSledz** [nortikin/sverchok#3434]
Hi guys, I'm trying to run Zeffi's script Hadley Attractors from 2016. I found it on [BA thread](https://blenderartists.org/t/attraktors-generative-equation/629114/33) but I cannot run it on newest SV. I noticed some changes in scripting so I started converting this old script into new one but still I have some issues.

I already converted parameters but don't know what's next?

![ln5ny](https://user-images.githubusercontent.com/45789626/89178826-c7a87600-d58e-11ea-9168-66b2a52e05d5.png)

**Comment by DaveSledz** [comment]
The old code:

`
def sv_main(alpha=2.0, beta=4, delta=8, gamma=1, factor=7, dif=0.005, t=20000, step=10):
    
    verts_out = []
    
    # Parameters
    
    in_sockets = [
        ['s', 'alpha', alpha],
        ['s', 'beta', beta],
        ['s', 'delta', delta],
        ['s', 'gamma', gamma],
        ['s', 'factor', factor],
        ['s', 'dif', dif],
        ['s', 't', t],
        ['s', 'step', step]]
        
    x0, y0, z0 = 0.1, 0, 0
    i = 0
    j = 0
    
    PointX, PointY, PointZ = [], [], []
    VertexX, VertexY, vertexZ = [], [], []
    
    x = x0
    y = y0
    z = z0
    for i in range(1, t):
        dx = (-y**2) - (z**2) - (alpha*z) + (alpha*delta)
        dy = (x*y) - (beta * x * z) - y + gamma
        dz = (beta * x * y) + (x * z) - z
        x = x + (dif + dx)
        y = y + (dif * dy)
        z = z + (dif * dz)
        PointX.append(x)
        PointY.append(y)
        PointZ.append(z)
        
    sublistlen = int(len(PointX) / step)
    for i in range(sublistlen):
        vert = [
            (PointX[i * step] * factor),
            (PointY[i * step] * factor),
            (PointZ[i * step] * factor)]
        verts_out.append(vert)
        
    
    out_sockets = [
        ['v', 'verts', [verts_out]]
    ]
    
    return in_sockets, out_sockets
        `


Converted parameters:

"""
in  alpha   s default=2.0
in  beta    s default=4
in  delta   s default=8
in  gamma   s default=1
in  factor  s default=7
in  dif     s default=0.005
in  t       s default=20000
in  step    s default=10
out verts   v
out edges   s
"""

**Comment by zeffii** [comment]
_this_ i will help you with.

**Comment by zeffii** [comment]
it would look something like
```python
"""
in  alpha   s default=2.0 n=2
in  beta    s default=4.0 n=2
in  delta   s default=8.0 n=2
in  gamma   s default=1.0 n=2
in  factor  s default=7.0 n=2
in  dif     s default=0.005 n=2
in  t       s default=20000 n=2
in  step    s default=10 n=2
out verts   v
"""    

x0, y0, z0 = 0.1, 0, 0
i = 0
j = 0

PointX, PointY, PointZ = [], [], []
VertexX, VertexY, vertexZ = [], [], []

x = x0
y = y0
z = z0
for i in range(1, t):
    dx = (-y**2) - (z**2) - (alpha*z) + (alpha*delta)
    dy = (x*y) - (beta * x * z) - y + gamma
    dz = (beta * x * y) + (x * z) - z
    x = x + (dif + dx)
    y = y + (dif * dy)
    z = z + (dif * dz)
    PointX.append(x)
    PointY.append(y)
    PointZ.append(z)
    
sublistlen = int(len(PointX) / step)
verts.append([])
new_vert = verts[0].append
for i in range(sublistlen):
    new_vert(
        (PointX[i * step] * factor),
        (PointY[i * step] * factor),
        (PointZ[i * step] * factor)
        )
``
`

**Comment by zeffii** [comment]
but i get this error:
```python
on line:  24
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\generator\script1_lite.py", line 426, in process_script
    exec(self.script_str, locals(), locals())
  File "<string>", line 24, in <module>
OverflowError: (34, 'Result too large')
```

**Comment by DaveSledz** [comment]
Cool! Mine is working but I cannot change the values - no result - just a static mesh:
![Zrzut ekranu 2020-08-3 o 14 33 50](https://user-images.githubusercontent.com/45789626/89182739-82884200-d596-11ea-91ea-897a850039b3.jpg)

**Comment by zeffii** [comment]
i don't know atm.
```python
"""
in  alpha   s d=2.0 n=2
in  beta    s d=4 n=2
in  delta   s d=8 n=2
in  gamma   s d=1 n=2
in  factor  s d=7 n=2
in  dif     s d=0.005 n=2
in  t       s d=20000 n=2
in  step    s d=10 n=2
out verts   v
"""    

x0, y0, z0 = 0.1, 0, 0
i = 0
j = 0

PointX, PointY, PointZ = [], [], []

x = x0
y = y0
z = z0
for i in range(1, t):
    dx = (-y**2) - (z**2) - (alpha*z) + (alpha*delta)
    dy = (x*y) - (beta * x * z) - y + gamma
    dz = (beta * x * y) + (x * z) - z
    x = x + (dif + dx)
    y = y + (dif * dy)
    z = z + (dif * dz)
    PointX.append(x)
    PointY.append(y)
    PointZ.append(z)
    
sublistlen = int(len(PointX) // step)
verts.append([])
new_vert = verts[0].append
for i in range(sublistlen):
    idx = i*step
    new_vert(PointX[idx]*factor, PointY[idx]*factor, PointZ[idx]*factor)
```

**Comment by DaveSledz** [comment]
![d47d3e63-e670-4ba5-a1aa-fc066e1902aa_rw_1200](https://user-images.githubusercontent.com/45789626/89183309-4dc8ba80-d597-11ea-88ca-c69044c9a571.jpg)

Gonna try from the groundup - it looks like simple equations now the implementation : - )

**Comment by zeffii** [comment]
@DaveSledz  where did you find the original code you provide here, i can't find it. i think there are some transcription errors?

**Comment by DaveSledz** [comment]
I found on Blender Artist thread, your post is from May 2016: https://blenderartists.org/t/attraktors-generative-equation/629114/33

**Comment by zeffii** [comment]
ah yes, i understand now :)

**Comment by zeffii** [comment]
then this
```
"""
in  alpha   s d=0.2 n=2
in  beta    s d=4 n=2
in  delta   s d=8 n=2
in  gamma   s d=1 n=2
in  factor  s d=7 n=2
in  dif     s d=0.005 n=2
in  t       s d=20000 n=2
in  step    s d=10 n=2
out verts   v
"""    

x0, y0, z0 = 0.1, 0, 0
i = 0
j = 0

PointX, PointY, PointZ = [], [], []

x = x0
y = y0
z = z0
for i in range(1, t):
    dx = (-y**2) - (z**2) - (alpha*x) + (alpha*delta)
    dy = (x*y) - (beta * x * z) - y + gamma
    dz = (beta * x * y) + (x * z) - z
    x = x + (dif + dx)
    y = y + (dif * dy)
    z = z + (dif * dz)
    PointX.append(x)
    PointY.append(y)
    PointZ.append(z)
    
sublistlen = int(len(PointX) / step)
verts.append([])
new_vert = verts[0].append
for i in range(sublistlen):
    idx = i*step
    new_vert([PointX[idx]*factor, PointY[idx]*factor, PointZ[idx]*factor])
```

**Comment by DaveSledz** [comment]
![Zrzut ekranu 2020-08-3 o 15 40 06](https://user-images.githubusercontent.com/45789626/89188972-a4d28d80-d59f-11ea-9d56-07c633e4cd9d.jpg)

Thanks Zeffi. It works very nice

**Comment by zeffii** [comment]
i think i made a typo in the original :)
```python
"""
in  alpha   s d=0.2 n=2
in  beta    s d=4 n=2
in  delta   s d=8 n=2
in  gamma   s d=1 n=2
in  factor  s d=7 n=2
in  dif     s d=0.005 n=2
in  t       s d=20000 n=2
in  step    s d=10 n=2
out verts   v
"""    

x0, y0, z0 = 0.1, 0, 0
i = 0
j = 0

PointX, PointY, PointZ = [], [], []

x = x0
y = y0
z = z0
for i in range(1, t):
    dx = -(y**2) - (z**2) - (alpha*x) + (alpha*delta)
    dy = (x*y) - (beta * x * z) - y + gamma
    dz = (beta * x * y) + (x * z) - z
    x = x + (dif * dx)
    y = y + (dif * dy)
    z = z + (dif * dz)
    PointX.append(x)
    PointY.append(y)
    PointZ.append(z)
    
sublistlen = int(len(PointX) / step)
verts.append([])
new_vert = verts[0].append
for i in range(sublistlen):
    idx = i*step
    new_vert([PointX[idx]*factor, PointY[idx]*factor, PointZ[idx]*factor])
```

**Comment by zeffii** [comment]
there's a small speedup by aliasing the append function.
```python
"""
in  alpha   s d=0.2 n=2
in  beta    s d=4 n=2
in  delta   s d=8 n=2
in  gamma   s d=1 n=2
in  factor  s d=7 n=2
in  dif     s d=0.005 n=2
in  t       s d=20000 n=2
in  step    s d=10 n=2
out verts   v
"""    

x0, y0, z0 = 0.1, 0, 0
i = 0
j = 0

PointX, PointY, PointZ = [], [], []

x = x0
y = y0
z = z0
xappend = PointX.append
yappend = PointY.append
zappend = PointZ.append
for i in range(1, t):
    dx = -(y**2) - (z**2) - (alpha*x) + (alpha*delta)
    dy = (x*y) - (beta * x * z) - y + gamma
    dz = (beta * x * y) + (x * z) - z
    x = x + (dif * dx)
    y = y + (dif * dy)
    z = z + (dif * dz)
    xappend(x)
    yappend(y)
    zappend(z)
    
sublistlen = int(len(PointX) / step)
verts.append([])
new_vert = verts[0].append
for i in range(sublistlen):
    idx = i*step
    new_vert([PointX[idx]*factor, PointY[idx]*factor, PointZ[idx]*factor])
```

**Comment by DaveSledz** [comment]
![Zrzut ekranu 2020-08-3 o 15 56 12](https://user-images.githubusercontent.com/45789626/89190890-67bbca80-d5a2-11ea-9fe7-569130579cbe.jpg)
![Zrzut ekranu 2020-08-3 o 15 59 34](https://user-images.githubusercontent.com/45789626/89190898-6c807e80-d5a2-11ea-841d-a998b4e31ef5.jpg)

Yup, now it looks more like Hadley example: https://syntopia.github.io/StrangeAttractors/
Great job Zeffi!

**Comment by zeffii** [comment]
and slightly less annoying to read
```python
"""
in  alpha   s d=0.2 n=2
in  beta    s d=4 n=2
in  delta   s d=8 n=2
in  gamma   s d=1 n=2
in  factor  s d=7 n=2
in  dif     s d=0.005 n=2
in  t       s d=20000 n=2
in  step    s d=10 n=2
out verts   v
"""    

x0, y0, z0 = 0.1, 0, 0
i = 0
j = 0

verts.append([])
new_vert = verts[0].append
Points = []
p_append = Points.append

x = x0
y = y0
z = z0
for i in range(1, t):
    dx = -(y**2) - (z**2) - (alpha*x) + (alpha*delta)
    dy = (x*y) - (beta * x * z) - y + gamma
    dz = (beta * x * y) + (x * z) - z
    x = x + (dif * dx)
    y = y + (dif * dy)
    z = z + (dif * dz)
    p_append((x, y, z))
    
sublistlen = int(len(Points) / step)
for i in range(sublistlen):
    idx = i*step
    new_vert([Points[idx][0]*factor, Points[idx][1]*factor, Points[idx][2]*factor])
```

**Comment by zeffii** [comment]
final for now
```python
"""
in  alpha   s d=0.2 n=2
in  beta    s d=4.0 n=2
in  delta   s d=8.0 n=2
in  gamma   s d=1.0 n=2
in  factor  s d=7.0 n=2
in  dif     s d=0.005 n=2
in  t       s d=20000 n=2
in  step    s d=10 n=2
out verts   v
"""    

x0, y0, z0 = 0.1, 0, 0
i = 0
j = 0

verts.append([])
new_vert = verts[0].append
Points = []
p_append = Points.append

x = x0
y = y0
z = z0
for i in range(1, t):
    dx = -(y**2) - (z**2) - (alpha*x) + (alpha*delta)
    dy = (x*y) - (beta * x * z) - y + gamma
    dz = (beta * x * y) + (x * z) - z
    x = x + (dif * dx)
    y = y + (dif * dy)
    z = z + (dif * dz)
    p_append((x, y, z))
    
sublistlen = int(len(Points) / step)
for idx in range(0, sublistlen, step):
    new_vert([Points[idx][0]*factor, Points[idx][1]*factor, Points[idx][2]*factor])
```
note that the arguments can be floats too, and that will given much finer control over the shape

**Comment by zeffii** [comment]
can close the issue now, you can keep posting in it tho, but it won't bubble up to the top of the issue tracker anymore :)

**Comment by zeffii** [comment]
here's a different version, skip and mod help sample less values..
```python
"""
in  alpha   s d=0.2 n=2
in  beta    s d=4.0 n=2
in  delta   s d=8.0 n=2
in  gamma   s d=1.0 n=2
in  factor  s d=7.0 n=2
in  dif     s d=0.005 n=2
in  t       s d=20000 n=2
in  step    s d=5 n=2
in  mod     s d=4 n=2
out verts   v
"""    

Points = []
p_append = Points.append

x = 0.1
y = 0.0
z = 0.0
for i in range(1, t):
    for j in range(step):
        dx = -(y**2) - (z**2) - (alpha*x) + (alpha*delta)
        dy = (x*y) - (beta * x * z) - y + gamma
        dz = (beta * x * y) + (x * z) - z
        x = x + (dif * dx)
        y = y + (dif * dy)
        z = z + (dif * dz)
    if i % mod == 0:
        p_append((x, y, z))

verts = [[[c*factor for c in p] for p in Points]]    
```

**Comment by zeffii** [comment]
here is a version which uses numba, and it is much faster (even on my most shitty machine)
```python
"""
in  alpha   s d=0.2 n=2
in  beta    s d=4.0 n=2
in  delta   s d=8.0 n=2
in  gamma   s d=1.0 n=2
in  factor  s d=7.0 n=2
in  dif     s d=0.005 n=2
in  t       s d=20000 n=2
in  step    s d=5 n=2
in  mod     s d=4 n=2
out verts   v
"""    
import numpy as np
from numba_tests import make_hadley

pz = make_hadley(alpha, beta, delta, gamma, factor, dif, t, step, mod)
verts.append(np.array(pz).reshape((-1, 3)).tolist())
```
and you stick the numba version inside `....\2.91\python\lib\site-packages\numba_tests\__init__.py`

![image](https://user-images.githubusercontent.com/619340/89273361-b9666280-d63f-11ea-831e-dfd8c94cddd2.png)
and
![image](https://user-images.githubusercontent.com/619340/89273443-d4d16d80-d63f-11ea-9d30-f242d9388a9c.png)
and inside `__init__.py` 
```python
import numba
from numba import njit
import numpy as np

@njit
def make_hadley(alpha=0.2, beta=4.0, delta=8.0, gamma=1.0, factor=7.0, dif=0.005, t=20000, step=5, mod=4):
    Points = []
    p = Points.extend

    x = 0.1
    y = 0.0
    z = 0.0
    for i in range(1, t):
        for j in range(step):
            dx = -(y**2) - (z**2) - (alpha*x) + (alpha*delta)
            dy = (x*y) - (beta * x * z) - y + gamma
            dz = (beta * x * y) + (x * z) - z
            x = x + (dif * dx)
            y = y + (dif * dy)
            z = z + (dif * dz)
        if i % mod == 0:
            p([x*factor, y*factor, z*factor])

    return Points
```

and to run that, the first time is a little slow as it precompiles it once, then it is noticably faster.. maybe 3 or 4 times. which no specific optimizations even.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/89273940-87a1cb80-d640-11ea-9acd-9fcf833d5ef4.png)

**Comment by zeffii** [comment]
and this appears to be even faster, due to the the way `+=`  is optimized in python inside loops
```python
@njit
def make_hadley2(alpha=0.2, beta=4.0, delta=8.0, gamma=1.0, factor=7.0, dif=0.005, t=20000, step=5, mod=4):
    Points = []
    p = Points.extend

    x = 0.1
    y = 0.0
    z = 0.0
    for i in range(1, t):
        for j in range(step):
            x += dif * (-(y**2) - (z**2) - (alpha*x) + (alpha*delta))
            y += dif * ((x*y) - (beta*x*z) - y + gamma)
            z += dif * ((beta*x*y) + (x*z) - z)
        if i % mod == 0:
            p([x*factor, y*factor, z*factor])

    return Points
```
