### ISSUE TITLE
Mesh Viewer 2D is broken on osX, shader compile error

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3480]
<img width="440" alt="Screen Shot 2020-08-25 at 10 59 01 am" src="https://user-images.githubusercontent.com/3952687/91110767-22cb1580-e6c2-11ea-872d-b56dbc77f074.png">

```
2020-08-25 10:58:36,292 [ERROR] sverchok.core.update_system: Node Viewer 2D had exception: Shader Compile Error, see console for more details
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/core/update_system.py", line 383, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/viz/viewer_2d.py", line 813, in process
    geom = generate_mesh_geom(config, vecs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/viz/viewer_2d.py", line 478, in generate_mesh_geom
    config.v_shader = get_2d_smooth_color_shader()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/viz/viewer_2d.py", line 156, in get_2d_smooth_color_shader
    return gpu.types.GPUShader(smooth_2d_vertex_shader, smooth_2d_fragment_shader)
Exception: Shader Compile Error, see console for more details
EVENT: node_property_update          IN: SvIcosphereNode           INSTANCE: IcoSphere                
GPUShader: compile error:
ERROR: 0:33: Use of undeclared identifier 'gl_FragColor'

2020-08-25 10:58:36,327 [ERROR] sverchok.core.update_system: Node Viewer 2D had exception: Shader Compile Error, see console for more details
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/core/update_system.py", line 383, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/viz/viewer_2d.py", line 813, in process
    geom = generate_mesh_geom(config, vecs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/viz/viewer_2d.py", line 478, in generate_mesh_geom
    config.v_shader = get_2d_smooth_color_shader()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/viz/viewer_2d.py", line 156, in get_2d_smooth_color_shader
    return gpu.types.GPUShader(smooth_2d_vertex_shader, smooth_2d_fragment_shader)
Exception: Shader Compile Error, see console for more details
```

**Comment by zeffii** [comment]
could be a mac issue..

![image](https://user-images.githubusercontent.com/619340/91150081-35dae700-e6bc-11ea-98e6-3ea734716cfb.png)

**Comment by zeffii** [comment]
@enzyme69  you'll notice the following nodes don't work either..

Searching 862 files for "gl_FragColor" (case sensitive)

C:\Users\zeffi\Desktop\GITHUB\sverchok\nodes\number\easing.py:
   88      void main()
   89      {
   90:        gl_FragColor = color;
   91      }
   92      '''
   ..
  125      void main()
  126      {
  127:         gl_FragColor = a_color;
  128      }
  129      '''

C:\Users\zeffi\Desktop\GITHUB\sverchok\nodes\viz\vd_draw_experimental.py:
   52      void main()
   53      {
   54:         gl_FragColor = vec4(pos * brightness, 1.0);
   55      }
   56  '''

C:\Users\zeffi\Desktop\GITHUB\sverchok\nodes\viz\viewer_2d.py:
  122      void main()
  123      {
  124:        gl_FragColor = color;
  125      }
  126      '''
  ...
  151      void main()
  152      {
  153:         gl_FragColor = a_color;
  154      }
  155      '''

C:\Users\zeffi\Desktop\GITHUB\sverchok\nodes\viz\viewer_waveform_output.py:
  193      void main()
  194      {
  195:        gl_FragColor = color;
  196      }
  197      '''
  ...
  222      void main()
  223      {
  224:         gl_FragColor = a_color;
  225      }
  226      '''

7 matches across 4 files

**Comment by zeffii** [comment]
and the `vdmk3` (vd_draw_experimental) is listed in there because the `gl_FragColor` is used for the custom fragment shader, which i suspect you've never used on osx.

![image](https://user-images.githubusercontent.com/619340/91150831-2f00a400-e6bd-11ea-9e8d-22a17607a4f5.png)

this might deserve a bug report to `blender.devs`

**Comment by zeffii** [comment]
`gl_FragColor` should be available, even when not explicitly added to the fragment and vertex shader.  it's auto injected (at least, it should be.. )

i could be wrong, but that's what appears to not be happening.

**Comment by zeffii** [comment]
see the examples also do first explicitly declare that property 

https://docs.blender.org/api/blender2.8/gpu.html#triangle-with-custom-shader

high probability that you will get errors trying to execute that code from blender's Text Editor too.

**Comment by zeffii** [comment]
a small fix we could inject 
```
out vec4 gl_FragColor;
```
in the fragment shaders listed above..

**Comment by zeffii** [comment]
it seems `gl_FragColor` is maybe a Blender convenience for shader coders,, it doesn't appear in the openGL specs as a default. ( i thought it was )
