### ISSUE TITLE
NURBS Surface Loft From Curves seems not working...

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3491]
<img width="614" alt="Screen Shot 2020-08-29 at 2 07 05 pm" src="https://user-images.githubusercontent.com/3952687/91628219-fcc6ad80-ea00-11ea-9a3c-2a985a26540c.png">

[sv_nurbs_in_001.blend.zip](https://github.com/nortikin/sverchok/files/5144765/sv_nurbs_in_001.blend.zip)
 
Following @portnov video tutorial, I can't seem to make this to work:

<img width="614" alt="Screen Shot 2020-08-29 at 2 07 05 pm" src="https://user-images.githubusercontent.com/3952687/91628230-1bc53f80-ea01-11ea-951c-598957d356d5.png">

```
IndexError: list index out of range
EVENT: node_property_update          IN: SvExEvalCurveNode         INSTANCE: Evaluate Curve           
2020-08-29 14:06:58,463 [ERROR] sverchok.core.update_system: Node Evaluate Curve had exception: list index out of range
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/core/update_system.py", line 383, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/curve/eval_curve.py", line 76, in process
    if isinstance(curve_s[0], SvCurve):
IndexError: list index out of range
EVENT: node_property_update          IN: SvExEvalCurveNode         INSTANCE: Evaluate Curve           
2020-08-29 14:06:58,709 [ERROR] sverchok.core.update_system: Node Evaluate Curve had exception: list index out of range
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/core/update_system.py", line 383, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/curve/eval_curve.py", line 76, in process
    if isinstance(curve_s[0], SvCurve):
IndexError: list index out of range
EVENT: node_property_update          IN: SvExEvalCurveNode         INSTANCE: Evaluate Curve           
2020-08-29 14:06:58,889 [ERROR] sverchok.core.update_system: Node Evaluate Curve had exception: list index out of range
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/core/update_system.py", line 383, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/curve/eval_curve.py", line 76, in process
    if isinstance(curve_s[0], SvCurve):
IndexError: list index out of range

```

**Comment by portnov** [comment]
Your curves are Bezier, not Nurbs. So in your case you have to use "Bezier In" node instead.

**Comment by enzyme69** [comment]
@portnov that's right, interesting gotcha!! thanks for all the cool nodes, I want to design something with this~

<img width="917" alt="Screen Shot 2020-08-29 at 4 32 46 pm" src="https://user-images.githubusercontent.com/3952687/91630520-4e793300-ea15-11ea-905d-87a2dbaf434b.png">

**Comment by enzyme69** [comment]
@portnov Can Bezier and Nurbs In to auto update?

**Comment by portnov** [comment]
They support "live Object In" mode. You have to enable the mode in Sverchok preferences first, then you can toggle it on/off either in N panel of 3D view, or with Ctrl-Shift-F5 in 3D view.

**Comment by portnov** [comment]
Have no idea, why the feature is disabled by default...

**Comment by enzyme69** [comment]
Yes, this "Live In" or update per frame change, etc is not too obvious. Thanks for tips!

**Comment by enzyme69** [comment]
<img width="301" alt="Screen Shot 2020-08-30 at 12 58 40 pm" src="https://user-images.githubusercontent.com/3952687/91650263-9e610400-eac0-11ea-9222-f47db446597b.png">

Maybe wish list is to have this under "Bezier In".

**Comment by enzyme69** [comment]
The sorting of curve for Loft operation is also quite interesting task. How do @portnov do the sorting from 3D view? What would be quite interesting is if we can operate in 3D view, and perform lofting, and it generates SV nodes, in the background.
