### ISSUE TITLE
how to install Scipy in sverchok? [Windows]

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#3500]
https://blender.stackexchange.com/questions/192874/how-to-install-scipy-in-sverchok

Judging by screenshot, it's Windows, so I'm afraid I can't help there :) @zeffii  or @vicdoval maybe you can?

**Comment by vicdoval** [comment]
I don't have enough reputation to comment "Can you share de output of the console" I have just installed scipy in a fresh blender with no troubles

**Comment by zeffii** [comment]
on windows here it returns this ( but it does not suggest for me to reboot because of any kind of success )

```python
 ./python.exe -m pip install scipy
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\__main__.py", line 16, in <module>
    from pip._internal import main as _main  # isort:skip # noqa
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\cli\autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\cli\main_parser.py", line 11, in <module>
    from pip._internal.commands import (
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\commands\__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\commands\completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\cli\base_command.py", line 26, in <module>
    from pip._internal.index import PackageFinder
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\index\__init__.py)
```

i think best way on windows is either via anaconda, or straight up binaries https://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy

**Comment by vicdoval** [comment]
I tried it in 2.83.5 ....
@zeffi Did you try to upgrade Pip first?

**Comment by zeffii** [comment]
@vicdoval upgrade pip gives a similar error
```
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\__main__.py", line 16, in <module>
    from pip._internal import main as _main  # isort:skip # noqa
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\cli\autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\cli\main_parser.py", line 11, in <module>
    from pip._internal.commands import (
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\commands\__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\commands\completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\cli\base_command.py", line 26, in <module>
    from pip._internal.index import PackageFinder
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\lib\site-packages\pip\_internal\index\__init__.py)
```

**Comment by zeffii** [comment]
even manually
```
PS C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\bin> .\python.exe -m pip install --upgrade pip
```

**Comment by zeffii** [comment]
even `.\python.exe -m ensurepip --upgrade` says
```
PS C:\Users\zeffi\Desktop\test_blenders\current_28\2.90\python\bin> .\python.exe -m ensurepip --upgrade
Looking in links: c:\Users\zeffi\AppData\Local\Temp\tmpakfg1hzx
Requirement already up-to-date: setuptools in c:\users\zeffi\desktop\test_blenders\current_28\2.90\python\lib\site-packages (41.2.0)
Requirement already up-to-date: pip in c:\users\zeffi\desktop\test_blenders\current_28\2.90\python\lib\site-packages (20.1.1)
```

**Comment by portnov** [comment]
@nortikin maybe you will be able to help?

**Comment by nortikin** [comment]
```normal site-packages is not writeable```
so, is it protected from writing?

**Comment by portnov** [comment]
When using simple "pip install",  that's okay, because next it says: "Defaulting to user installation"; so it's just installing into `~/.local/...` somewhere instead of `/usr/lib/...`. I'm not sure what exactly this means when running pip from blender installation; maybe the folder where Blender is installed is not writeable for current user?

**Comment by nortikin** [comment]
> When using simple "pip install", that's okay, because next it says: "Defaulting to user installation"; so it's just installing into `~/.local/...` somewhere instead of `/usr/lib/...`. I'm not sure what exactly this means when running pip from blender installation; maybe the folder where Blender is installed is not writeable for current user?

i think so.

**Comment by portnov** [comment]
So probably under windows you have to be admin to run pip install correctly?
@nortikin or @zeffii could you please suggest this on stackexchange.

**Comment by zeffii** [comment]
@portnov  i start powershell as an administrator, generally. so that might just give a different error. but still an error

**Comment by portnov** [comment]
@zeffii I don't think your error is related to what is posted on stackexchange... You're getting an error, while in the output on stackexchange, pip is saying "everything is okay", but `import scipy` fails.

**Comment by zeffii** [comment]
@portnov  i see,  i'll stay out of it as per a conversation we had a while back.

**Comment by zeffii** [comment]
i had to wipe all versions of pip from 
```
2.90\python\lib\site-packages
```
and then run
```
2.90\python\bin> ./python.exe -m ensurepip -U
```
and then stuff like this does work
```
python\bin> ./python.exe -m pip install scipy
python\bin> ./python.exe -m pip install pymcubes
```
