### ISSUE TITLE
export to json doesn't work

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#3553]
After some new commits there is error wile jsoning:
```bash
ERROR:sverchok.ui.sv_IO_panel:Object of type IDPropertyGroup is not JSON serializable
Traceback (most recent call last):
  File "/home/ololo/.config/blender/2.90/scripts/addons/sverchok/ui/sv_IO_panel.py", line 285, in execute
    gist_body = json.dumps(layout_dict, sort_keys=True, indent=2)
  File "/home/ololo/Downloads/INSTALL/blender-2.90.0-linux64/2.90/python/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/ololo/Downloads/INSTALL/blender-2.90.0-linux64/2.90/python/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/home/ololo/Downloads/INSTALL/blender-2.90.0-linux64/2.90/python/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/ololo/Downloads/INSTALL/blender-2.90.0-linux64/2.90/python/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/ololo/Downloads/INSTALL/blender-2.90.0-linux64/2.90/python/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/ololo/Downloads/INSTALL/blender-2.90.0-linux64/2.90/python/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  [Previous line repeated 1 more time]
  File "/home/ololo/Downloads/INSTALL/blender-2.90.0-linux64/2.90/python/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/ololo/Downloads/INSTALL/blender-2.90.0-linux64/2.90/python/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/ololo/Downloads/INSTALL/blender-2.90.0-linux64/2.90/python/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type IDPropertyGroup is not JSON serializable
{'Vertices': [(8.5, 1.0, 0.0), (8.5, 1.5, 0.0), (8.5, 2.0, 0.0), (8.5, 2.5, 0.0), (8.5, 3.0, 0.0), (8.5, 4.5, 0.0), (8.5, 5.0, 0.0), (8.5, 5.5, 0.0), (2.0, 1.0, 0.0), (2.0, 1.5, 0.0), (2.0, 2.0, 0.0), (2.0, 2.5, 0.0), (2.0, 3.0, 0.0), (2.0, 4.5, 0.0), (2.0, 5.0, 0.0), (2.0, 5.5, 0.0)], 'Edges': [(0, 8), (1, 9), (2, 10), (3, 11), (4, 12), (5, 13), (6, 14), (7, 15)], 'Polygons': [], 'MaterialIdx': [], 'Matrix': Matrix(((1.0, 0.0, 0.0, 0.0),
        (0.0, 1.0, 0.0, 0.0),
        (0.0, 0.0, 1.0, 0.0),
        (0.0, 0.0, 0.0, 1.0)))}
{'Vertices': [(20.5, 0.5, 0.0), (2.0, 29.200000762939453, 0.0), (2.0, 0.5, 0.0), (20.5, 29.200000762939453, 0.0), (20.5, 6.0, 0.0), (6.0, 6.0, 0.0), (7.5, 6.0, 0.0), (5.0, 6.0, 0.0), (4.0, 6.0, 0.0), (3.0, 6.0, 0.0), (15.5, 0.5, 0.0), (2.0, 4.0, 0.0), (2.0, 3.5, 0.0), (20.5, 2.0, 0.0), (20.5, 3.0, 0.0), (20.5, 3.5, 0.0), (20.5, 5.0, 0.0), (8.5, 3.5, 0.0), (8.5, 4.0, 0.0), (3.0, 3.5, 0.0), (4.0, 0.5, 0.0), (5.0, 3.5, 0.0), (7.5, 0.5, 0.0), (6.0, 0.5, 0.0), (15.5, 3.5, 0.0), (17.0, 2.0, 0.0), (17.0, 3.5, 0.0), (8.5, 0.5, 0.0), (18.5, 2.0, 0.0), (2.0, 6.0, 0.0), (18.5, 3.5, 0.0), (8.5, 2.0, 0.0), (2.0, 0.5, 0.0), (15.5, 3.0, 0.0), (8.5, 3.5, 0.0), (8.5, 5.0, 0.0), (8.5, 6.0, 0.0)], 'Edges': [(1, 2), (1, 3), (0, 3), (11, 12), (27, 36), (10, 24), (8, 20), (7, 21), (9, 19), (12, 17), (11, 18), (6, 22), (5, 23), (25, 26), (0, 32), (4, 29), (13, 31), (14, 33), (15, 34), (16, 35), (28, 30)], 'Polygons': [], 'MaterialIdx': [], 'Matrix': Matrix(((1.0, 0.0, 0.0, 0.0),
        (0.0, 1.0, 0.0, 0.0),
        (0.0, 0.0, 1.0, 0.0),
        (0.0, 0.0, 0.0, 1.0)))}

ERROR:sverchok.utils.sv_IO_panel_tools:TypeError('Object of type IDPropertyGroup is not JSON serializable')
Traceback (most recent call last):
  File "/home/ololo/.config/blender/2.90/scripts/addons/sverchok/ui/sv_IO_panel.py", line 145, in execute
    write_json(layout_dict, destination_path)
  File "/home/ololo/.config/blender/2.90/scripts/addons/sverchok/utils/sv_IO_panel_tools.py", line 124, in write_json
    node_tree.writelines(m)
UnboundLocalError: local variable 'm' referenced before assignment
```

_Originally posted by @nortikin in https://github.com/nortikin/sverchok/pull/3517#issuecomment-693716303_

latest sverchok
blender 2.9

**Comment by Durman** [comment]
```
'SVG Document': {'params': {'file_name': 'default'}, 'bl_idname': 'SvSvgDocumentNode', 'height': 100.0, 'width': 200.0, 'label': '', 
'hide': False, 'location': (1493.1541748046875, 264.5855407714844)}, 'File Path': {'params': {'files': [<bpy id prop: 
owner="NT╨У╨Ю╨б╨в ╨а 21.1101-2013 SVG ╤Н╨║╤Б╨┐╨╛╤А╤В", name="", address=0x000002EAD59B1928>],
```

**Comment by zeffii** [comment]
one or more nodes in the blend file being exported, contains a property that io_json doesn't handle. usually 
- PointerProperties or a 
- PropertyGroup

upload the blend here @nortikin we can track down the node, and fix it for now.

**Comment by Durman** [comment]
I indeed found one bug with export which was caused by merging socket refactoring branch 9 days ago. But it does not relevant with this issue it would raise another error. 

From what I found in the gallery file the problem is that at least one node `SVG Document` can't be convert into JSON by current convert version without extra instruction from the node.

**Comment by zeffii** [comment]
`svg document` node doesn't have PointerProp or PropertyGroup in it's own class, so i'd like to see the blend being exported.

**Comment by zeffii** [comment]
that looks like the `filepath` socket not being serialized correctly..

**Comment by Durman** [comment]
I don't see any problem with the socket.

**Comment by zeffii** [comment]
yeah no `iIDPropertyGroup` on that either.

but it is also not SVG document:  https://gist.github.com/34a18b6c7a3a05e9e37847ffa6b5ab0d

**Comment by zeffii** [comment]
it's the FilePath node.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/325dad18adeb0d7c84435532a19c5242faae4dd9/nodes/network/file_path.py#L31

**Comment by zeffii** [comment]
so the question @vicdoval  is.. does it make sense to store any data from that collection during export with json ? it's skipped easily by io_json code by addinginto the node class
```python
    properties_to_skip_iojson = ['files'] 
```

**Comment by zeffii** [comment]
`files` contains not full path, that's composed from self.directory + 
```python
        for file_elem in self.files:
            filepath = os.path.join(directory, file_elem.name)
```

**Comment by zeffii** [comment]
so .. i think this would work.. for the filepath node
```
    def storage_set_data(self, storage):
        '''function to get data when importing from json''' 
        strings_json = storage['string_storage']
        filenames = json.loads(strings_json)['filenames']
        dirname = json.loads(strings_json)['dirname']
        
        self.id_data.freeze(hard=True)
        self.set_data(self, dirname, filenames):
        self.id_data.unfreeze(hard=True)

    def storage_get_data(self, node_dict):
        '''function to set data for exporting json''' 
        local_storage = {
            'filenames': [file_elem.name for file_elem in self.files], 
            'dirname': self.dirname
        }
        node_dict['string_storage'] = json.dumps(local_storage)

```

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/issues/2814#issuecomment-693723284
here is file

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/3557

**Comment by zeffii** [comment]
https://gist.github.com/de783fb3ac1956cc6754629be14dfb82

exports OK, but doesn't import, because i try to reuse `set_data` inside `storage_set_data`, but it throws
```python
    for k, v in file_elem.items():
AttributeError: 'str' object has no attribute 'items'
```

**Comment by zeffii** [comment]
so... what is a `OperatorFileListElement`  ? :)   

https://docs.blender.org/api/blender2.8/bpy.types.OperatorFileListElement.html?highlight=operatorfilelistelement#module-bpy.types.OperatorFileListElement

so it's just a list of `{"name": filename }`

**Comment by zeffii** [comment]
https://gist.github.com/02058427f43011c3b288096c34c894e2

exports and imports !
