### ISSUE TITLE
Pulga Collision / Self Collision error?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3626]
When using Pulga Collision node plugging it into force, I am getting error right away:

[pp_error.blend.zip](https://github.com/nortikin/sverchok/files/5351761/pp_error.blend.zip)
<img width="601" alt="Screen Shot 2020-10-09 at 10 39 24 am" src="https://user-images.githubusercontent.com/3952687/95523946-c460b900-0a1b-11eb-96b0-3f83d5a75713.png">

```
AttributeError: 'function' object has no attribute 'result'
2020-10-09 10:38:23,675 - sverchok.core.update_system - ERROR - Node Pulga Physics Solver had exception: 'function' object has no attribute 'result'
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/core/update_system.py", line 384, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/nodes/pulga_physics/pulga_physics_solver.py", line 312, in process
    cache_new = pulga_system_init(par, gates_dict, out_lists, cache)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/utils/pulga_physics_modular_core.py", line 1415, in pulga_system_init
    iterate(iterations_max, out_params)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/utils/pulga_physics_modular_core.py", line 1425, in iterate
    ps.iterate()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/utils/pulga_physics_modular_core.py", line 1391, in iterate
    force.add(self)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/utils/pulga_physics_modular_core.py", line 483, in add_brute_force
    ps.relations.result[:] = 0
AttributeError: 'function' object has no attribute 'result'

```

**Comment by vicdoval** [comment]
Fixed. Thanks for reporting 😄
