### ISSUE TITLE
Pulga Modular Spring --- not sure how this node works

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3627]
<img width="640" alt="Screen Shot 2020-10-09 at 10 43 12 am" src="https://user-images.githubusercontent.com/3952687/95524132-3b964d00-0a1c-11eb-8482-67d767729922.png">

When plugging float into Springs:
```
2020-10-09 10:44:03,141 - sverchok.core.update_system - ERROR - Node Pulga Physics Solver had exception: arrays used as indices must be of integer (or boolean) type
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/core/update_system.py", line 384, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/nodes/pulga_physics/pulga_physics_solver.py", line 312, in process
    cache_new = pulga_system_init(par, gates_dict, out_lists, cache)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/utils/pulga_physics_modular_core.py", line 1410, in pulga_system_init
    ps.setup_forces()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/utils/pulga_physics_modular_core.py", line 1380, in setup_forces
    force.setup(self)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/utils/pulga_physics_modular_core.py", line 957, in setup
    self.dist_rest = calc_rest_length(ps.verts, self.springs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/utils/pulga_physics_modular_core.py", line 90, in calc_rest_length
    pairs_springs = np_verts[np_springs, :]
IndexError: arrays used as indices must be of integer (or boolean) type
```

When plugging random 0,1:
```
2020-10-09 10:44:55,628 - sverchok.core.update_system - ERROR - Node Pulga Physics Solver had exception: too many indices for array
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/core/update_system.py", line 384, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/nodes/pulga_physics/pulga_physics_solver.py", line 312, in process
    cache_new = pulga_system_init(par, gates_dict, out_lists, cache)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/utils/pulga_physics_modular_core.py", line 1410, in pulga_system_init
    ps.setup_forces()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/utils/pulga_physics_modular_core.py", line 1380, in setup_forces
    force.setup(self)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/utils/pulga_physics_modular_core.py", line 957, in setup
    self.dist_rest = calc_rest_length(ps.verts, self.springs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.90/scripts/addons/sverchok-master/utils/pulga_physics_modular_core.py", line 91, in calc_rest_length
    vect_rest = (pairs_springs[:, 0, :] - pairs_springs[:, 1, :])
IndexError: too many indices for array

```

**Comment by vicdoval** [comment]
The springs input expects edges list.
Check the docs at:
https://github.com/nortikin/sverchok/blob/master/docs/nodes/pulga_physics/pulga_springs_force.rst
![image](https://user-images.githubusercontent.com/10011941/95529007-18e34480-09da-11eb-84c9-ca51630ec000.png)

**Comment by enzyme69** [comment]
Wow.... so cool! Thanks Vic~
