### ISSUE TITLE
cant enable sverchok on 2.90.1

### ISSUE THREAD

**Issue by adhhrg** [nortikin/sverchok#3687]
## Problem statement

cant check the box after installation,it shows

Traceback (most recent call last):
  File "C:\Files\BLENDER BUILDS\stable\blender-2.90.1-windows64\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\hongy\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sverchok-master\__init__.py", line 74, in <module>
    node_list = make_node_list(nodes)
NameError: name 'nodes' is not defined

## Steps to reproduce

1. install the addon on 2.90.1
2.try to enable it 
3. it shows error

## Expected result

expect to work

## Actual result

didn't work

## Sverchok version

from sverchok github, the latest version

**Comment by zeffii** [comment]
try this: https://github.com/nortikin/sverchok#errors-during-install-or-enable-in-preferences
