### ISSUE TITLE
rightlick_menu on node when select viewerdraw or stethoscope throws exception

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3728]
also adding temporal viewers.
```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 381, in do_update_general
    node = nodes[node_name]
KeyError: 'bpy_prop_collection[key]: key "tion" not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\ui\sv_temporal_viewers.py", line 153, in execute
    add_temporal_viewer(context, self.force_stethoscope, self.cut_links)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\ui\sv_temporal_viewers.py", line 132, in add_temporal_viewer
    add_temporal_stethoscope(tree, nodes, links, existing_node)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\ui\sv_temporal_viewers.py", line 111, in add_temporal_stethoscope
    tree.update()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\node_tree.py", line 231, in update
    self.sv_update()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\node_tree.py", line 104, in sv_update
    process_from_nodes(self.sv_links.get_nodes(self))
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 481, in process_from_nodes
    do_update(update_list, ng.nodes)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 424, in do_update
    do_update_general(node_list, nodes)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\profile.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 409, in do_update_general
    start_exception_drawing_with_bgl(ng, node_name, error_text, err)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\exception_drawing_with_bgl.py", line 62, in start_exception_drawing_with_bgl
    node = ng.nodes[node_name]
KeyError: 'bpy_prop_collection[key]: key "tion" not found'

location: <unknown location>:-1
```

**Comment by zeffii** [comment]
master pull resolved it :)

**Comment by zeffii** [comment]
there's still something going on here.. i just got a similar message 
```
KeyError: 'bpy_prop_collection[key]: key "Curve Mapper" not found'
```
and there's no such node even in the nodetree anymore.

**Comment by zeffii** [comment]
@Durman  is there a way to rebuild the cache entirely, from the UI, if there appears to be some stale state ?

**Comment by zeffii** [comment]
it's seems OK after using a fresh/new NodeTree in my startup blend.

**Comment by Durman** [comment]
I think @vicdoval is more familiar with current update system

**Comment by vicdoval** [comment]
F8 "script.reload" should wipe everything. Maybe would be nice to have a button in the ui that does something similar
