### ISSUE TITLE
Blender 2.91: Sverchok, Sorcar, Animation Nodes Node Tree Editor not showing --- is it just me?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3742]
I tested latest Blender 2.91 and none of SV, AN, or Sorcar addon showing up ..... :( wonder if it's just me panic-ing. I did uninstall and reinstall.

```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
192-168-1-7:~ jimmygunawan$ /Applications/BLENDER_291/Blender.app/Contents/MacOS/Blender ; exit;
Read prefs: /Users/jimmygunawan/Library/Application Support/Blender/2.91/config/userpref.blend
found bundled python: /Applications/BLENDER_291/Blender.app/Contents/Resources/2.91/python

 Start Spring Bones Addon... 

Warning: class IMPORT_OT_usdz contains a property which should be an annotation!
/Users/jimmygunawan/Library/Application Support/Blender/2.91/scripts/addons/io_scene_usdz/__init__.py:141
    assign as a type annotation: IMPORT_OT_usdz.materials
    assign as a type annotation: IMPORT_OT_usdz.animations
Warning: class EXPORT_OT_usdz contains a property which should be an annotation!
/Users/jimmygunawan/Library/Application Support/Blender/2.91/scripts/addons/io_scene_usdz/__init__.py:141
    assign as a type annotation: EXPORT_OT_usdz.exportMaterials
    assign as a type annotation: EXPORT_OT_usdz.exportAnimations
    assign as a type annotation: EXPORT_OT_usdz.bakeTextures
    assign as a type annotation: EXPORT_OT_usdz.bakeAO
    assign as a type annotation: EXPORT_OT_usdz.bakeAOSamples
    assign as a type annotation: EXPORT_OT_usdz.bakeTextureSize
    assign as a type annotation: EXPORT_OT_usdz.globalScale
    assign as a type annotation: EXPORT_OT_usdz.useConverter
sv: import settings
SciPy package is not available. Voronoi nodes and RBF-based nodes will not be available.
2020-11-26 11:42:12,084 - sverchok.dependencies - INFO - SciPy package is not available. Voronoi nodes and RBF-based nodes will not be available.
geomdl package is not available, some NURBS related nodes will not be available
2020-11-26 11:42:12,085 - sverchok.dependencies - INFO - geomdl package is not available, some NURBS related nodes will not be available
SciKit-Image package is not available; SciKit-based implementation of Marching Cubes and Marching Squares will not be available
2020-11-26 11:42:12,085 - sverchok.dependencies - INFO - SciKit-Image package is not available; SciKit-based implementation of Marching Cubes and Marching Squares will not be available
PyMCubes package is not available. PyMCubes-based implementation of Marching Cubes will not be available
2020-11-26 11:42:12,086 - sverchok.dependencies - INFO - PyMCubes package is not available. PyMCubes-based implementation of Marching Cubes will not be available
Circlify package is not available. Circlify node will not be available
2020-11-26 11:42:12,086 - sverchok.dependencies - INFO - Circlify package is not available. Circlify node will not be available
FreeCAD package is not available, Solids nodes will not be available
2020-11-26 11:42:12,086 - sverchok.dependencies - INFO - FreeCAD package is not available, Solids nodes will not be available
Cython package is not available, Enhanched KDTree search will not be available
2020-11-26 11:42:12,086 - sverchok.dependencies - INFO - Cython package is not available, Enhanched KDTree search will not be available
Dependencies available: pip.
2020-11-26 11:42:12,086 - sverchok.dependencies - INFO - Dependencies available: pip.
/Users/jimmygunawan/Library/Application Support/Blender/2.91/scripts/addons/sverchok-master/settings.py:15: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  PYPATH = bpy.app.binary_path_python
sv: import all modules
/Users/jimmygunawan/Library/Application Support/Blender/2.91/scripts/addons/sverchok-master/settings.py:15: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  PYPATH = bpy.app.binary_path_python
Traceback (most recent call last):
  File "/Applications/BLENDER_291/Blender.app/Contents/Resources/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.91/scripts/addons/sverchok-master/__init__.py", line 74, in <module>
    node_list = make_node_list(nodes)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.91/scripts/addons/sverchok-master/core/__init__.py", line 59, in make_node_list
    import_modules(names, '{}.{}'.format(base_name, category), node_list)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.91/scripts/addons/sverchok-master/core/__init__.py", line 65, in import_modules
    im = importlib.import_module('.{}'.format(m), base)
  File "/Applications/BLENDER_291/Blender.app/Contents/Resources/2.91/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.91/scripts/addons/sverchok-master/nodes/ladybug/sun_position.py", line 11, in <module>
    from sverchok.dependencies import ladybug
ImportError: cannot import name 'ladybug' from 'sverchok.dependencies' (/Users/jimmygunawan/Library/Application Support/Blender/2.91/scripts/addons/sverchok-master/dependencies.py)
Registered Animation Nodes
module changed on disk: '/Applications/BLENDER_291/Blender.app/Contents/Resources/2.91/scripts/addons/add_mesh_extra_objects/__init__.py' reloading...
```

**Comment by enzyme69** [comment]
Sorcar suddenly works. SV and AN not showing.

**Comment by enzyme69** [comment]
Disable Sorcar, SV works again. Weird.
