### ISSUE TITLE
Loop node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3794]
![2020-12-25_08-29-11](https://user-images.githubusercontent.com/28003269/103119098-49f31d00-468b-11eb-8b25-1db5ac677a1b.png)

```
Python: Traceback (most recent call last):
  File "sverchok\node_tree.py", line 369, in update
    self.sv_update()
  File "sverchok\nodes\logic\loop_out.py", line 89, in sv_update
    if type(socket.links[0].from_socket) != type(self.outputs[socket.name]):
KeyError: 'bpy_prop_collection[key]: key "Iterations" not found'
```

**Comment by vicdoval** [comment]
Fixed at #3826
