### ISSUE TITLE
ImportError: cannot import name 'gcd' from 'fractions'

### ISSUE THREAD

**Issue by sxiii** [nortikin/sverchok#3872]
## Problem statement

Tried enabling Sverchok (latest) from release source code ZIP file.

## Versions
Blender 2.91.0 on Manjaro 20.2.1 Nibia, kernel 5.10.7-3-MANJARO
Sverchok-vstable 3, however, in add-ons it says "0.6.0.0"

## Steps to reproduce

1. Edit -> Preferences -> Add-ons -> Install from file -> choose ZIP
2. Trying to enable checkmark near sverchok
3. Error appears

## Expected result

Sverchok enabled

## Actual result

Error appears

## Sverchok version

Sverchok-vstable 3 (latest) from release ZIP

<details><summary>## Error log</summary>

```

Traceback (most recent call last):
  File "/usr/share/blender/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/sa/.config/blender/2.91/scripts/addons/sverchok-vstable3/__init__.py", line 74, in <module>
    node_list = make_node_list(nodes)
  File "/home/sa/.config/blender/2.91/scripts/addons/sverchok-vstable3/core/__init__.py", line 59, in make_node_list
    import_modules(names, '{}.{}'.format(base_name, category), node_list)
  File "/home/sa/.config/blender/2.91/scripts/addons/sverchok-vstable3/core/__init__.py", line 65, in import_modules
    im = importlib.import_module('.{}'.format(m), base)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/sa/.config/blender/2.91/scripts/addons/sverchok-vstable3/nodes/number/scalar_mk4.py", line 20, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)

```

</details>

Thanks

**Comment by zeffii** [comment]
you may want to use the `master` release, or i've just now added a new release of the current state https://github.com/nortikin/sverchok/releases/tag/vstable4

and it will include this fix : https://github.com/nortikin/sverchok/pull/3825

**Comment by zeffii** [comment]
assuming this is adequate, else reopen @sxiii
