### ISSUE TITLE
Exception: Plane normal is (almost) zero!

### ISSUE THREAD

**Issue by gerroon** [nortikin/sverchok#4074]
## Problem statement

Voronoi on Mesh is throwing this error
![blender_p785Vd9WLI](https://user-images.githubusercontent.com/8519469/117045789-85ef5c00-acd5-11eb-9eaa-be9332090327.jpg)
.

## Steps to reproduce

1. create the node network in the attached image

## Expected result
Proper voronoi mesh

## Actual result
Errors with no real mesh

## Sverchok version
0.6.0.0 (0024862)  updated from the add-ons own update checker as of yesterday. I probably installed it using the zip originally.

```
2021-05-04 12:36:10,880    ERROR sverchok.core.update_system Node Voronoi on Mesh had exception: Plane normal is (almost) zero!
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\core\update_system.py", line 384, in do_update_general
    node.process()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\nodes\spatial\voronoi_on_mesh.py", line 155, in process
    precision = precision)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\utils\voronoi3d.py", line 351, in voronoi_on_mesh
    precision = precision)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\utils\voronoi3d.py", line 299, in voronoi_on_mesh_bmesh
    ridges_per_site = get_ridges_per_site(voronoi)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\utils\voronoi3d.py", line 246, in get_ridges_per_site
    plane = PlaneEquation.from_normal_and_point(normal, middle)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\utils\geom.py", line 729, in from_normal_and_point
    raise Exception("Plane normal is (almost) zero!")
Exception: Plane normal is (almost) zero!


```

**Comment by zeffii** [comment]
you are applying the matrix too late.

![image](https://user-images.githubusercontent.com/619340/117049851-fe294200-ad14-11eb-9ac4-70f325b07b6b.png)

**Comment by gerroon** [comment]
@zeffii 

Thanks for the reply. Just after this post I did another update hoping it was a bug, not when I try your method (switch the matrix apply) I am getting completely different error 


```

2021-05-04 13:32:59,711    ERROR sverchok.core.update_system Node Viewer Draw.001 had exception: list indices must be integers or slices, not list
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\update_system.py", line 384, in do_update_general
    node.process()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\viz\viewer_draw_mk4.py", line 892, in process
    geom = generate_mesh_geom(config, vecs)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\viz\viewer_draw_mk4.py", line 456, in generate_mesh_geom
    polygons_geom(config, vecs, polygons, p_vertices, p_vertex_colors, p_indices, v_path, p_cols, idx_p_offset, points_color)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\viz\viewer_draw_mk4.py", line 345, in polygons_geom
    polygon_indices, original_idx = ensure_triangles(vecs, polygons, config.handle_concave_quads)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\viz\viewer_draw_mk4.py", line 84, in ensure_triangles
    subcoords = [Vector(coords[idx]) for idx in idxset]
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\viz\viewer_draw_mk4.py", line 84, in <listcomp>
    subcoords = [Vector(coords[idx]) for idx in idxset]
TypeError: list indices must be integers or slices, not list



```

**Comment by gerroon** [comment]
@zeffii 

Please see the video, how I am getting the plane normal thing even after switching the matrix. For some reason increasing the points throws the error


https://user-images.githubusercontent.com/8519469/117054671-f9966680-acdf-11eb-9643-871701e73771.mp4

**Comment by zeffii** [comment]
i can only guess that increasing the number of points per face, will lead to higher chance that one or more of the points is very close to one of the points of the input mesh.

**Comment by zeffii** [comment]
for a tidy debug, it's not clear to me what kind of _input mesh_ you have, is it just a plane?

**Comment by zeffii** [comment]
to be clear here, what i think the problem is , may have nothing to do with the problem :)

**Comment by zeffii** [comment]
in your first example you are generating random points on a transformed mesh, but you are passing the untransformed mesh to the voronoi node. So the voronoi node is being asked to generate a voronoi from points that are not directly on the input mesh - this is why i made a point about changing where you apply the matrix. do it early, or do it later (at the end..)

**Comment by vicdoval** [comment]
A `merge by distance` node after the `random points on mesh ` may solve the issue

**Comment by gerroon** [comment]
Hey guys thanks for the inputs I will give it a try.
