### ISSUE TITLE
Error when script node is reloaded under the new update system

### ISSUE THREAD

**Issue by vkter** [nortikin/sverchok#4229]
Python: Traceback (most recent call last):
  File "C:\Users\121\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\socket_data.py", line 105, in SvGetSocket
    out = socket_data_cache[s_ng][s_id]
KeyError: '-8540842626835638738'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\121\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\script\script1_lite.py", line 81, in execute
    getattr(context.node, self.fn_name)()
  File "C:\Users\121\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\script\script1_lite.py", line 313, in load
    self.process()
  File "C:\Users\121\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\script\script1_lite.py", line 331, in process
    self.process_script()
  File "C:\Users\121\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\script\script1_lite.py", line 421, in process_script
    __local__dict__ = self.make_new_locals()
  File "C:\Users\121\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\script\script1_lite.py", line 357, in make_new_locals
    val = s.sv_get(default=[[]])
  File "C:\Users\121\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\sockets.py", line 418, in sv_get
    return self.convert_data(SvGetSocket(self, other, deepcopy), implicit_conversions, other)
  File "C:\Users\121\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\socket_data.py", line 116, in SvGetSocket
    raise SvNoDataError(socket)
sverchok.core.socket_data.SvNoDataError: No data passed into socket 'verts'

location: <unknown location>:-1

**Comment by vkter** [comment]
The whole sverchok seems to be paralyzed

**Comment by Durman** [comment]
Can you attach the problem file?

**Comment by vkter** [comment]
> Can you attach the problem file?

[Desktop.zip](https://github.com/nortikin/sverchok/files/6835500/Desktop.zip)

**Comment by vkter** [comment]
I found that importing a module file that does not exist will cause this error, and then paralyze the entire sverchok

**Comment by Durman** [comment]
This is more or less expecting behaviour. The SNL node does not produce any output (because it has an error during execution) and the next node can't find any data. What I would expect is that the SNL node would rise the error explicitly. I suspect that the error is lost in some of try catch construction inside the node.
What behaviour would you expect?

**Comment by Durman** [comment]
There is property which suppress the node errors. Actually I don't see motivation to have this property or at least to have it exposed in the UI. The documentation does not give any hints about that.
![2021-07-18_08-47-36](https://user-images.githubusercontent.com/28003269/126056110-17c0268f-faeb-4121-bbeb-5ebccb526f00.png)
https://github.com/nortikin/sverchok/blob/23ebab557a8abb2cebab54d4f938ae9ec45dc620/nodes/script/script1_lite.py#L477-L478

According this #3257 the purpose of the property is to suppress errors during JSON importing.  I'm not sure that this is correct approach to deal with errors but if there is no way but suppressing an error I don't see why it can't be done with standard one more try catch construction in `load_from_json`.

Easy fix would be remove the property from the UI and make it be True by default.

**Comment by vkter** [comment]
After this error occurs, there is no response when adding other nodes. I hope that after this error occurs, other nodes of sverchok can still run normally.

**Comment by Durman** [comment]
In my case other nodes work.

https://user-images.githubusercontent.com/28003269/126060303-f76068bc-4e52-48d2-94c5-320e27872f0f.mp4

Am I missing some step to reproduce?

**Comment by vkter** [comment]
It’s a bit strange, but nothing happens when I reopen the file
https://user-images.githubusercontent.com/74725748/126061575-690799a6-7a61-4e8b-b181-afcf0107a7f1.mp4

**Comment by zeffii** [comment]
Exception handling gets a little complicated when exceptions can occur in the script (inside the `exec`) _vs_ something that caused an exception in the code of snlite ( outside of the `exec` ). 

The purpose of that boolean to "raise to tree level" is that the error that was being shown beside the node was not pertinent to the user's "script", it was showing only the exceptions "outside of the `exec`". 

@vkter  it looks like you are trying to load "Test.py" and not "Text.py" ?

@Durman 
![image](https://user-images.githubusercontent.com/619340/126064887-91850a35-77f2-41fd-a55d-2ec55d70ef93.png)

the screen position calculation is borked

**Comment by zeffii** [comment]
i don't mind  changing the raise boolean to True , and if there are no issues after testing later the property can be removed entirely.

**Comment by Durman** [comment]
@vkter 
I see that you have the problem but I can't reproduce it. Can you describe the certain steps to reproduce it. For example:
1. Open the file
2. Press reload on the SNL node
3. Reopen the file `File->open->path/to/the/untitled.blend`

zeffii, please, open a separate issue with reproducing steps.

**Comment by vkter** [comment]
I reproduced the error, the steps are as follows:
1 Open a new blender file
2 Load the Text.py file in a text editor
3 Use SNL node to load the file
4 Close and save the blender file
5 Reopen the blender file, add any node and preview it, but nothing happens
[Text.zip](https://github.com/nortikin/sverchok/files/6836355/Text.zip)

**Comment by Durman** [comment]
Works for me. What Blender do you use?

https://user-images.githubusercontent.com/28003269/126070038-47bba377-8c7e-465d-a89a-68ef2c6e8d62.mp4

**Comment by vkter** [comment]
I use the official version of blender 2.93, maybe my blender has a problem, I will uninstall and reinstall blender 2.93 to see if the problem still occurs

**Comment by Durman** [comment]
If it won't help upload the log file using this steps - https://github.com/nortikin/sverchok/issues/4231#issuecomment-882244306

**Comment by rwny** [comment]
my sverchok.log from #4231 
-------------------------------------------------------------------------------------------------------------------------------
2021-07-18 08:08:38,350 [INFO] root: Initializing Sverchok logging. Blender version 2.93.1, Sverchok version 0.6.0.0
2021-07-19 14:35:41,880 [INFO] root: Initializing Sverchok logging. Blender version 2.93.1, Sverchok version 1.0.0
2021-07-19 14:35:41,881 [DEBUG] root: Current log level: DEBUG, log to text buffer: sverchok.log, log to file: no, log to console: yes
2021-07-19 14:35:41,881 [DEBUG] sverchok.node_tree 57: update_gl_scale_info called from sv_post_load
2021-07-19 14:36:18,341 [DEBUG] sverchok.ui.color_def 124: building color cache
2021-07-19 14:36:18,353 [DEBUG] sverchok.core.main_tree_handler 182: Global update - 0ms
2021-07-19 14:36:24,352 [DEBUG] sverchok.core.main_tree_handler 182: Global update - 0ms
2021-07-19 14:36:28,247 [DEBUG] sverchok.core.main_tree_handler 182: Global update - 7ms
2021-07-19 14:36:29,622 [DEBUG] sverchok.core.main_tree_handler 182: Global update - 1ms
2021-07-19 14:36:31,141 [DEBUG] sverchok.core.main_tree_handler 182: Global update - 0ms
2021-07-19 14:38:03,766 [DEBUG] sverchok.node_tree 57: update_gl_scale_info called from sv_post_load
2021-07-19 14:38:10,099 [DEBUG] sverchok.ui.color_def 124: building color cache
2021-07-19 14:39:04,723 [DEBUG] sverchok.node_tree 57: update_gl_scale_info called from sv_post_load
2021-07-19 14:40:40,206 [DEBUG] sverchok.node_tree 57: update_gl_scale_info called from sv_post_load

**Comment by vkter** [comment]
The problem persists after reinstalling, the following is my sverchok.log
2021-07-19 15:41:39,725 [INFO] root: Initializing Sverchok logging. Blender version 2.93.0, Sverchok version 1.0.0
2021-07-19 15:41:39,726 [DEBUG] root: Current log level: DEBUG, log to text buffer: sverchok.log, log to file: no, log to console: yes
2021-07-19 15:41:39,726 [DEBUG] sverchok.ui.color_def 124: building color cache
2021-07-19 15:41:39,738 [DEBUG] sverchok.core.main_tree_handler 182: Global update - 0ms
2021-07-19 15:41:46,959 [DEBUG] sverchok.core.main_tree_handler 182: Global update - 0ms
2021-07-19 15:41:49,430 [INFO] sverchok.nodes.script.script1_lite 469 (SN: Text.py): Unexpected error: <class 'ModuleNotFoundError'>
2021-07-19 15:41:49,435 [INFO] sverchok.nodes.script.script1_lite 472 (SN: Text.py): on line: 8
2021-07-19 15:41:49,440 [DEBUG] sverchok.core.main_tree_handler 182: Global update - 0ms
2021-07-19 15:42:16,665 [INFO] root: Initializing Sverchok logging. Blender version 2.93.0, Sverchok version 1.0.0
2021-07-19 15:42:16,666 [DEBUG] root: Current log level: DEBUG, log to text buffer: sverchok.log, log to file: no, log to console: yes
2021-07-19 15:42:16,667 [DEBUG] sverchok.node_tree 57: update_gl_scale_info called from sv_post_load
2021-07-19 15:42:38,493 [DEBUG] sverchok.ui.color_def 124: building color cache

**Comment by Durman** [comment]
I manage reproduce the error.)) I had to install Sverchok from a zip file. Looks like Blender acts differently in this case. When I use my development Sverchok folder everything works. Will have a look what the problem.

**Comment by Durman** [comment]
The problem is that `handlers` module create one instance of the function and `main_tree_handler` another.

https://github.com/nortikin/sverchok/blob/f98b8721ac895631d64ee7c0de2300a0335c971e/data_structure.py#L1168

Perhaps this feature #3650 was never working if the add-on was installed from zip.

**Comment by Durman** [comment]
@vkter @rwny You can try to install fixed version. Let me know whether the fix helped or not.

**Comment by rwny** [comment]
it's working !! 
Thank you  very much :))

**Comment by vkter** [comment]
The problem was fixed after the update, thank you very much for fixing it

**Comment by mlevet** [comment]
Is it related ?
I'm having this serie of errors after upgrading (with zip file)
Traceback (most recent call last):
  File "/Users/ml/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/sockets.py", line 59, in process_from_socket
    self.node.process_node(context)
  File "/Users/ml/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/node_tree.py", line 312, in process_node
    self.id_data.update_nodes([self])
  File "/Users/ml/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/node_tree.py", line 161, in update_nodes
    return TreeHandler.send(TreeEvent(TreeEvent.NODES_UPDATE, self, nodes))
  File "/Users/ml/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/main_tree_handler.py", line 32, in send
    NodesUpdater.cancel_task()
  File "/Users/ml/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/main_tree_handler.py", line 172, in cancel_task
    cls._handler.throw(CancelError)
ValueError: generator already executing
File "/Users/ml/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/sockets.py", line 56, in process_from_socket
2021-07-19 23:02:13,198 [ERROR] sverchok.core.main_tree_handler 131: 'NoneType' object is not an iterator

**Comment by Durman** [comment]
@mlevet No, it looks like is something different. Please open new issue with the problem file and description of how to reproduce the error.
