### ISSUE TITLE
activation issue on python 3.10

### ISSUE THREAD

**Issue by Sinasta** [nortikin/sverchok#4388]
Traceback (most recent call last):
  File "/usr/share/blender/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/sinasta/.config/blender/3.1/scripts/addons/sverchok-master/__init__.py", line 75, in <module>
    imported_modules = init_architecture(__name__, utils_modules, ui_modules)
  File "/home/sinasta/.config/blender/3.1/scripts/addons/sverchok-master/core/__init__.py", line 97, in init_architecture
    import_settings(imported_modules, sv_name)
  File "/home/sinasta/.config/blender/3.1/scripts/addons/sverchok-master/core/__init__.py", line 78, in import_settings
    settings = importlib.import_module(".settings", sv_dir_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/sinasta/.config/blender/3.1/scripts/addons/sverchok-master/settings.py", line 10, in <module>
    from sverchok.core import main_tree_handler  # don't remove this should fix #4229 (temp solution)
  File "/home/sinasta/.config/blender/3.1/scripts/addons/sverchok-master/core/main_tree_handler.py", line 18, in <module>
    from sverchok.utils.tree_structure import Tree, Node
  File "/home/sinasta/.config/blender/3.1/scripts/addons/sverchok-master/utils/tree_structure.py", line 11, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by Sinasta** [comment]
I know that python 3.10 is not supported yet. im just reporting that issue in case someone knows an easy fix. thank you for your work.

**Comment by Durman** [comment]
I thing the import is wrong there
```diff
- from collections import Mapping
+ from collections.abc import Mapping
```

**Comment by Sinasta** [comment]
Thank you for the answer. The error upon activation changed to:

Traceback (most recent call last):
  File "/usr/share/blender/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/sinasta/.config/blender/3.1/scripts/addons/sverchok-master/__init__.py", line 75, in <module>
    imported_modules = init_architecture(__name__, utils_modules, ui_modules)
  File "/home/sinasta/.config/blender/3.1/scripts/addons/sverchok-master/core/__init__.py", line 97, in init_architecture
    import_settings(imported_modules, sv_name)
  File "/home/sinasta/.config/blender/3.1/scripts/addons/sverchok-master/core/__init__.py", line 78, in import_settings
    settings = importlib.import_module(".settings", sv_dir_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/sinasta/.config/blender/3.1/scripts/addons/sverchok-master/settings.py", line 10, in <module>
    from sverchok.core import main_tree_handler  # don't remove this should fix #4229 (temp solution)
  File "/home/sinasta/.config/blender/3.1/scripts/addons/sverchok-master/core/main_tree_handler.py", line 19, in <module>
    from sverchok.utils.handle_blender_data import BlTrees, BlTree
  File "/home/sinasta/.config/blender/3.1/scripts/addons/sverchok-master/utils/handle_blender_data.py", line 10, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by Sinasta** [comment]
i changed collections to collections.abc in handle_blender_data.py and in meshes.py. And now the activation works perfectly well.

**Comment by Sinasta** [comment]
i will report further if any errors occur.
