### ISSUE TITLE
Can't activate Sverchok 1.0 in Blender 3.1.2

### ISSUE THREAD

**Issue by PabloCaracena** [nortikin/sverchok#4442]
## Problem statement
I just can't turn on the addon after installing it. I tried reopening Blender after installation, doesn't work.

## Steps to reproduce
1. Open Blender
2. Install de addon with the "Install..." button in "Preferences > Add-ons"
3. Close Blender and open again
4. Try to activate it 

## Expected result
Activated addon

## Actual result
Blender throws an error

## Sverchok version
Downloaded from releases
Sverchok-1_0_0.zip (https://github.com/nortikin/sverchok/releases/download/v1.0.0/sverchok-1_0_0.zip)

## Blender version 
Blender 3.1.2 installed from Steam

## Blender Error Log

Traceback (most recent call last):
  File "D:\Steam\steamapps\common\Blender\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "D:\BlenderScripts\addons\sverchok-1_0_0\__init__.py", line 75, in <module>
    imported_modules = init_architecture(__name__, utils_modules, ui_modules)
  File "D:\BlenderScripts\addons\sverchok-1_0_0\core\__init__.py", line 97, in init_architecture
    import_settings(imported_modules, sv_name)
  File "D:\BlenderScripts\addons\sverchok-1_0_0\core\__init__.py", line 78, in import_settings
    settings = importlib.import_module(".settings", sv_dir_name)
  File "D:\Steam\steamapps\common\Blender\3.1\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\BlenderScripts\addons\sverchok-1_0_0\settings.py", line 10, in <module>
    from sverchok.core import main_tree_handler  # don't remove this should fix #4229 (temp solution)
  File "D:\BlenderScripts\addons\sverchok-1_0_0\core\main_tree_handler.py", line 18, in <module>
    from sverchok.utils.tree_structure import Tree, Node
  File "D:\BlenderScripts\addons\sverchok-1_0_0\utils\tree_structure.py", line 11, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (D:\Steam\steamapps\common\Blender\3.1\python\lib\collections\__init__.py)

**Comment by zeffii** [comment]
download and install from : https://github.com/nortikin/sverchok/archive/refs/heads/master.zip

**Comment by zeffii** [comment]
sverchok 1.0.0 references parts of a python standard library module that have been renamed/moved
see https://github.com/nortikin/sverchok/commit/771a4b9415ef6fa4d9018ab21aff67c9257ac20c

**Comment by PabloCaracena** [comment]
> download and install from : https://github.com/nortikin/sverchok/archive/refs/heads/master.zip

That works 👍

**Comment by Durman** [comment]
We can create v1.0.1 release to support Blender 3.1
