### ISSUE TITLE
Unable to setup python Open3D on macOS

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4447]
## Problem statement

I have not been able to install Open3D on macOS.

## Steps to reproduce

error message:

```
Traceback (most recent call last):
  File "/Applications/BLENDER_31/Blender.app/Contents/Resources/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.1/scripts/addons/sverchok-open3d-master/__init__.py", line 36, in <module>
    from sverchok_open3d import icons, settings, sockets, examples, menu
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.1/scripts/addons/sverchok-open3d-master/settings.py", line 5, in <module>
    PYPATH = bpy.app.binary_path_python
AttributeError: 'bpy.app' object has no attribute 'binary_path_python'
```

I wonder if the python of my system matters?

macOS Monterey 12.4 Beta.

**Comment by zeffii** [comment]
replace those lines with
```
if bpy.app.version >= (2, 91, 0):
    PYPATH = sys.executable
else:
    PYPATH = bpy.app.binary_path_python
```
here a PR for @vicdoval https://github.com/vicdoval/sverchok-open3d/pull/9
