### ISSUE TITLE
Sverchok not working at all in Blender 4.0 Alpha

### ISSUE THREAD

**Issue by meikasahara** [nortikin/sverchok#4915]
Operating System: Xubuntu 22.04.2 LTS with 5.15.0-72-generic kernel.

In any of the latest Blender 4.0 alpha builds (later than May 22nd build),  the latest Sverchok 1.2 add-on does not work at all. The add-on appears to be enabled in the Preferences, but there is no context, and it does not appear in the editor types at all.
When loading, Blender returns the following errors in the console regarding Sverchok:

 ```
File "/home/user/.config/blender/4.0/scripts/addons/sverchok-master/__init__.py", line 113, in <module>
    imported_modules, node_modules, core = import_sverchok()
  File "/home/user/.config/blender/4.0/scripts/addons/sverchok-master/__init__.py", line 106, in import_sverchok
    node_modules_ = core.import_nodes()
  File "/home/user/.config/blender/4.0/scripts/addons/sverchok-master/core/__init__.py", line 56, in import_nodes
    import_modules(names, '{}.{}'.format(base_name, category), node_modules)
  File "/home/user/.config/blender/4.0/scripts/addons/sverchok-master/core/__init__.py", line 63, in import_modules
    im = importlib.import_module('.{}'.format(m), base)
```
When trying to disable and re-enable the addon from the Preferences, the following error appears:

`addon_utils.disable: sverchok-master not disabled
addon not loaded: 'sverchok-master'
cause: cannot import name 'core' from partially initialized module 'sverchok-master' (most likely due to a circular import) (/home/user/.config/blender/4.0/scripts/addons/sverchok-master/__init__.py)
addon not loaded: 'sverchok-master'
cause: cannot import name 'core' from partially initialized module 'sverchok-master' (most likely due to a circular import) (/home/user/.config/blender/4.0/scripts/addons/sverchok-master/__init__.py)
`

**Comment by Durman** [comment]
It seems for Blender 4.0 all strings `3D_UNIFORM_COLOR` should be replaced with `UNIFORM_COLOR` according to the example in the docs - https://docs.blender.org/api/4.0/gpu.html#d-lines-with-single-color

Probably there are others incompatible changes in 4.0

**Comment by meikasahara** [comment]
Sverchok can now be installed on Blender 4.0 but Stethoscope and Viewer Draw nodes do not work. The following errors appear in the console: 
```

Traceback (most recent call last):
  File "/home/me/.config/blender/4.0/scripts/addons/sverchok-master/ui/bgl_callback_nodeview.py", line 148, in draw_callback_px
    draw_text_data(data)
  File "/home/me/.config/blender/4.0/scripts/addons/sverchok-master/utils/sv_stethoscope_helper.py", line 40, in draw_text_data
    blf.size(font_id, int(text_height), 72)
TypeError: blf.size() takes exactly 2 arguments (3 given)
```

and

```
Traceback (most recent call last):
  File "/home/diffeomorphist/.config/blender/4.0/scripts/addons/sverchok-master/ui/bgl_callback_3dview.py", line 83, in draw_callback_px
    bgl.glEnable(bgl.GL_DEPTH_TEST)
TypeError: 'NoneType' object is not callable

```
