### ISSUE TITLE
Some Sverchok nodes do not work in Blender 4.0 Alpha (Related to #4915) 

### ISSUE THREAD

**Issue by meikasahara** [nortikin/sverchok#4961]
Sverchok can now be installed on Blender 4.0 but the Stethoscope and the Viewer Draw nodes do not work. The following errors appear in the console: 
```

Traceback (most recent call last):
  File "/home/me/.config/blender/4.0/scripts/addons/sverchok-master/ui/bgl_callback_nodeview.py", line 148, in draw_callback_px
    draw_text_data(data)
  File "/home/me/.config/blender/4.0/scripts/addons/sverchok-master/utils/sv_stethoscope_helper.py", line 40, in draw_text_data
    blf.size(font_id, int(text_height), 72)
TypeError: blf.size() takes exactly 2 arguments (3 given)
```

and

```
Traceback (most recent call last):
  File "/home/diffeomorphist/.config/blender/4.0/scripts/addons/sverchok-master/ui/bgl_callback_3dview.py", line 83, in draw_callback_px
    bgl.glEnable(bgl.GL_DEPTH_TEST)
TypeError: 'NoneType' object is not callable

```

**Comment by Durman** [comment]
Yes, this is expected, here is the task to tackle it - #4895
