### ISSUE TITLE
FreeCAD path setup permission issue

### ISSUE THREAD

**Issue by chiboreache** [nortikin/sverchok#4971]
```python
Traceback (most recent call last):
File "/home/chibo/.config/blender/3.6/scripts/addons/sverchok-1_2_0/settings.py", line 187, in execute
file_path = open(join(site_packages, "freecad_path.pth"), "w+")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/freecad_path.pth'
Error: Python: Traceback (most recent call last):
File "/home/chibo/.config/blender/3.6/scripts/addons/sverchok-1_2_0/settings.py", line 187, in execute
file_path = open(join(site_packages, "freecad_path.pth"), "w+")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/freecad_path.pth'
```

![2023-08-06x00:25:04](https://github.com/nortikin/sverchok/assets/16459251/f53838e7-52d8-455e-b5ff-3d4bfd7cecd6)

**Comment by luzpaz** [comment]
Did you follow the instructions in https://github.com/nortikin/sverchok/wiki/FreeCAD ?

**Comment by chiboreache** [comment]
@luzpaz 

installed `aur/netgen-git`

but then getting same error

`➜  ~ sudo echo '/usr/lib/x86_64-linux-gnu/netgen' >> /etc/ld.so.conf.d/x86_64-linux-gnu.conf
warning: An error occurred while redirecting file '/etc/ld.so.conf.d/x86_64-linux-gnu.conf'
open: Permission denied`

**Comment by luzpaz** [comment]
https://askubuntu.com/a/279855  
I wonder if this is the solution?  (haven't tested)

**Comment by chiboreache** [comment]
@luzpaz 

```sh
sh: -c: line 1: unexpected EOF while looking for matching `''
sh: -c: line 2: syntax error: unexpected end of file
```

with no luck..

**Comment by luzpaz** [comment]
My bad.. I missed a single quote!
```bash
sudo sh -c "echo '/usr/lib/x86_64-linux-gnu/netgen' >> /etc/ld.so.conf.d/x86_64-linux-gnu.conf"
```

**Comment by chiboreache** [comment]
@luzpaz 

under this path is nothing

![2023-08-16x16:16:14](https://github.com/nortikin/sverchok/assets/16459251/39d20664-d16e-45c1-888f-1723f4608a3b)


if i add only `'netgen'` to `x86_64-linux-gnu.conf` -  it's doesn't work either 


```pacman -Ql netgen
netgen-git /usr/
netgen-git /usr/bin/
netgen-git /usr/bin/netgen
netgen-git /usr/include/
netgen-git /usr/include/netgen/
netgen-git /usr/include/netgen/core/
netgen-git /usr/include/netgen/core/archive.hpp
netgen-git /usr/include/netgen/core/array.hpp
netgen-git /usr/include/netgen/core/bitarray.hpp
netgen-git /usr/include/netgen/core/concurrentqueue.h
netgen-git /usr/include/netgen/core/exception.hpp
netgen-git /usr/include/netgen/core/flags.hpp
netgen-git /usr/include/netgen/core/hashtable.hpp
netgen-git /usr/include/netgen/core/localheap.hpp
netgen-git /usr/include/netgen/core/logging.hpp
netgen-git /usr/include/netgen/core/memtracer.hpp
netgen-git /usr/include/netgen/core/mpi_wrapper.hpp
netgen-git /usr/include/netgen/core/ngcore.hpp
netgen-git /usr/include/netgen/core/ngcore_api.hpp
netgen-git /usr/include/netgen/core/ngstream.hpp
netgen-git /usr/include/netgen/core/paje_trace.hpp
netgen-git /usr/include/netgen/core/profiler.hpp
netgen-git /usr/include/netgen/core/python_ngcore.hpp
netgen-git /usr/include/netgen/core/ranges.hpp
netgen-git /usr/include/netgen/core/register_archive.hpp
netgen-git /usr/include/netgen/core/signal.hpp
netgen-git /usr/include/netgen/core/simd.hpp
netgen-git /usr/include/netgen/core/simd_arm64.hpp
netgen-git /usr/include/netgen/core/simd_avx.hpp
netgen-git /usr/include/netgen/core/simd_avx512.hpp
netgen-git /usr/include/netgen/core/simd_generic.hpp
netgen-git /usr/include/netgen/core/simd_sse.hpp
netgen-git /usr/include/netgen/core/symboltable.hpp
netgen-git /usr/include/netgen/core/table.hpp
netgen-git /usr/include/netgen/core/taskmanager.hpp
netgen-git /usr/include/netgen/core/type_traits.hpp
netgen-git /usr/include/netgen/core/utils.hpp
netgen-git /usr/include/netgen/core/version.hpp
netgen-git /usr/include/netgen/core/xbool.hpp
netgen-git /usr/include/netgen/csg/
netgen-git /usr/include/netgen/csg/algprim.hpp
netgen-git /usr/include/netgen/csg/brick.hpp
netgen-git /usr/include/netgen/csg/csg.hpp
netgen-git /usr/include/netgen/csg/csgeom.hpp
netgen-git /usr/include/netgen/csg/csgparser.hpp
netgen-git /usr/include/netgen/csg/curve2d.hpp
netgen-git /usr/include/netgen/csg/edgeflw.hpp
netgen-git /usr/include/netgen/csg/explicitcurve2d.hpp
netgen-git /usr/include/netgen/csg/extrusion.hpp
netgen-git /usr/include/netgen/csg/gencyl.hpp
netgen-git /usr/include/netgen/csg/geoml.hpp
netgen-git /usr/include/netgen/csg/identify.hpp
netgen-git /usr/include/netgen/csg/manifold.hpp
netgen-git /usr/include/netgen/csg/meshsurf.hpp
netgen-git /usr/include/netgen/csg/polyhedra.hpp
netgen-git /usr/include/netgen/csg/revolution.hpp
netgen-git /usr/include/netgen/csg/singularref.hpp
netgen-git /usr/include/netgen/csg/solid.hpp
netgen-git /usr/include/netgen/csg/specpoin.hpp
netgen-git /usr/include/netgen/csg/spline3d.hpp
netgen-git /usr/include/netgen/csg/splinesurface.hpp
netgen-git /usr/include/netgen/csg/surface.hpp
netgen-git /usr/include/netgen/csg/triapprox.hpp
netgen-git /usr/include/netgen/csg/vscsg.hpp
netgen-git /usr/include/netgen/general/
netgen-git /usr/include/netgen/general/autodiff.hpp
netgen-git /usr/include/netgen/general/autoptr.hpp
netgen-git /usr/include/netgen/general/gzstream.h
netgen-git /usr/include/netgen/general/hashtabl.hpp
netgen-git /usr/include/netgen/general/myadt.hpp
netgen-git /usr/include/netgen/general/mystring.hpp
netgen-git /usr/include/netgen/general/netgenout.hpp
netgen-git /usr/include/netgen/general/ngarray.hpp
netgen-git /usr/include/netgen/general/ngbitarray.hpp
netgen-git /usr/include/netgen/general/ngpython.hpp
netgen-git /usr/include/netgen/general/optmem.hpp
netgen-git /usr/include/netgen/general/parthreads.hpp
netgen-git /usr/include/netgen/general/seti.hpp
netgen-git /usr/include/netgen/general/sort.hpp
netgen-git /usr/include/netgen/general/spbita2d.hpp
netgen-git /usr/include/netgen/general/stack.hpp
netgen-git /usr/include/netgen/general/table.hpp
netgen-git /usr/include/netgen/general/template.hpp
netgen-git /usr/include/netgen/geom2d/
netgen-git /usr/include/netgen/geom2d/csg2d.hpp
netgen-git /usr/include/netgen/geom2d/geometry2d.hpp
netgen-git /usr/include/netgen/geom2d/spline2d.hpp
netgen-git /usr/include/netgen/geom2d/vsgeom2d.hpp
netgen-git /usr/include/netgen/gprim/
netgen-git /usr/include/netgen/gprim/adtree.hpp
netgen-git /usr/include/netgen/gprim/geom2d.hpp
netgen-git /usr/include/netgen/gprim/geom3d.hpp
netgen-git /usr/include/netgen/gprim/geomfuncs.hpp
netgen-git /usr/include/netgen/gprim/geomobjects.hpp
netgen-git /usr/include/netgen/gprim/geomops.hpp
netgen-git /usr/include/netgen/gprim/geomops2.hpp
netgen-git /usr/include/netgen/gprim/geomtest3d.hpp
netgen-git /usr/include/netgen/gprim/gprim.hpp
netgen-git /usr/include/netgen/gprim/spline.hpp
netgen-git /usr/include/netgen/gprim/splinegeometry.hpp
netgen-git /usr/include/netgen/gprim/transform3d.hpp
netgen-git /usr/include/netgen/include/
netgen-git /usr/include/netgen/include/acisgeom.hpp
netgen-git /usr/include/netgen/include/csg.hpp
netgen-git /usr/include/netgen/include/geometry2d.hpp
netgen-git /usr/include/netgen/include/gprim.hpp
netgen-git /usr/include/netgen/include/incopengl.hpp
netgen-git /usr/include/netgen/include/inctcl.hpp
netgen-git /usr/include/netgen/include/incvis.hpp
netgen-git /usr/include/netgen/include/linalg.hpp
netgen-git /usr/include/netgen/include/meshing.hpp
netgen-git /usr/include/netgen/include/myadt.hpp
netgen-git /usr/include/netgen/include/mydefs.hpp
netgen-git /usr/include/netgen/include/mystdlib.h
netgen-git /usr/include/netgen/include/netgen_config.hpp
netgen-git /usr/include/netgen/include/netgen_version.hpp
netgen-git /usr/include/netgen/include/nginterface_v2_impl.hpp
netgen-git /usr/include/netgen/include/ngsimd.hpp
netgen-git /usr/include/netgen/include/occgeom.hpp
netgen-git /usr/include/netgen/include/opti.hpp
netgen-git /usr/include/netgen/include/parallel.hpp
netgen-git /usr/include/netgen/include/stlgeom.hpp
netgen-git /usr/include/netgen/include/visual.hpp
netgen-git /usr/include/netgen/interface/
netgen-git /usr/include/netgen/interface/writeuser.hpp
netgen-git /usr/include/netgen/linalg/
netgen-git /usr/include/netgen/linalg/densemat.hpp
netgen-git /usr/include/netgen/linalg/linalg.hpp
netgen-git /usr/include/netgen/linalg/opti.hpp
netgen-git /usr/include/netgen/linalg/polynomial.hpp
netgen-git /usr/include/netgen/linalg/vector.hpp
netgen-git /usr/include/netgen/meshing/
netgen-git /usr/include/netgen/meshing/adfront2.hpp
netgen-git /usr/include/netgen/meshing/adfront3.hpp
netgen-git /usr/include/netgen/meshing/basegeom.hpp
netgen-git /usr/include/netgen/meshing/bcfunctions.hpp
netgen-git /usr/include/netgen/meshing/bisect.hpp
netgen-git /usr/include/netgen/meshing/boundarylayer.hpp
netgen-git /usr/include/netgen/meshing/classifyhpel.hpp
netgen-git /usr/include/netgen/meshing/clusters.hpp
netgen-git /usr/include/netgen/meshing/curvedelems.hpp
netgen-git /usr/include/netgen/meshing/delaunay2d.hpp
netgen-git /usr/include/netgen/meshing/fieldlines.hpp
netgen-git /usr/include/netgen/meshing/findip.hpp
netgen-git /usr/include/netgen/meshing/findip2.hpp
netgen-git /usr/include/netgen/meshing/geomsearch.hpp
netgen-git /usr/include/netgen/meshing/global.hpp
netgen-git /usr/include/netgen/meshing/hpref_hex.hpp
netgen-git /usr/include/netgen/meshing/hpref_prism.hpp
netgen-git /usr/include/netgen/meshing/hpref_pyramid.hpp
netgen-git /usr/include/netgen/meshing/hpref_quad.hpp
netgen-git /usr/include/netgen/meshing/hpref_segm.hpp
netgen-git /usr/include/netgen/meshing/hpref_tet.hpp
netgen-git /usr/include/netgen/meshing/hpref_trig.hpp
netgen-git /usr/include/netgen/meshing/hprefinement.hpp
netgen-git /usr/include/netgen/meshing/improve2.hpp
netgen-git /usr/include/netgen/meshing/improve3.hpp
netgen-git /usr/include/netgen/meshing/localh.hpp
netgen-git /usr/include/netgen/meshing/meshclass.hpp
netgen-git /usr/include/netgen/meshing/meshfunc.hpp
netgen-git /usr/include/netgen/meshing/meshing.hpp
netgen-git /usr/include/netgen/meshing/meshing2.hpp
netgen-git /usr/include/netgen/meshing/meshing3.hpp
netgen-git /usr/include/netgen/meshing/meshtool.hpp
netgen-git /usr/include/netgen/meshing/meshtype.hpp
netgen-git /usr/include/netgen/meshing/msghandler.hpp
netgen-git /usr/include/netgen/meshing/paralleltop.hpp
netgen-git /usr/include/netgen/meshing/python_mesh.hpp
netgen-git /usr/include/netgen/meshing/ruler2.hpp
netgen-git /usr/include/netgen/meshing/ruler3.hpp
netgen-git /usr/include/netgen/meshing/soldata.hpp
netgen-git /usr/include/netgen/meshing/specials.hpp
netgen-git /usr/include/netgen/meshing/surfacegeom.hpp
netgen-git /usr/include/netgen/meshing/topology.hpp
netgen-git /usr/include/netgen/meshing/validate.hpp
netgen-git /usr/include/netgen/meshing/visual_interface.hpp
netgen-git /usr/include/netgen/mydefs.hpp
netgen-git /usr/include/netgen/nginterface.h
netgen-git /usr/include/netgen/nginterface_v2.hpp
netgen-git /usr/include/netgen/nglib.h
netgen-git /usr/include/netgen/nglib_occ.h
netgen-git /usr/include/netgen/occ/
netgen-git /usr/include/netgen/occ/occ_edge.hpp
netgen-git /usr/include/netgen/occ/occ_face.hpp
netgen-git /usr/include/netgen/occ/occ_solid.hpp
netgen-git /usr/include/netgen/occ/occ_utils.hpp
netgen-git /usr/include/netgen/occ/occ_vertex.hpp
netgen-git /usr/include/netgen/occ/occgeom.hpp
netgen-git /usr/include/netgen/occ/occmeshsurf.hpp
netgen-git /usr/include/netgen/occ/vsocc.hpp
netgen-git /usr/include/netgen/pybind11/
netgen-git /usr/include/netgen/pybind11/LICENSE
netgen-git /usr/include/netgen/pybind11/attr.h
netgen-git /usr/include/netgen/pybind11/buffer_info.h
netgen-git /usr/include/netgen/pybind11/cast.h
netgen-git /usr/include/netgen/pybind11/chrono.h
netgen-git /usr/include/netgen/pybind11/common.h
netgen-git /usr/include/netgen/pybind11/complex.h
netgen-git /usr/include/netgen/pybind11/detail/
netgen-git /usr/include/netgen/pybind11/detail/class.h
netgen-git /usr/include/netgen/pybind11/detail/common.h
netgen-git /usr/include/netgen/pybind11/detail/descr.h
netgen-git /usr/include/netgen/pybind11/detail/init.h
netgen-git /usr/include/netgen/pybind11/detail/internals.h
netgen-git /usr/include/netgen/pybind11/detail/type_caster_base.h
netgen-git /usr/include/netgen/pybind11/detail/typeid.h
netgen-git /usr/include/netgen/pybind11/eigen.h
netgen-git /usr/include/netgen/pybind11/embed.h
netgen-git /usr/include/netgen/pybind11/eval.h
netgen-git /usr/include/netgen/pybind11/functional.h
netgen-git /usr/include/netgen/pybind11/gil.h
netgen-git /usr/include/netgen/pybind11/iostream.h
netgen-git /usr/include/netgen/pybind11/numpy.h
netgen-git /usr/include/netgen/pybind11/operators.h
netgen-git /usr/include/netgen/pybind11/options.h
netgen-git /usr/include/netgen/pybind11/pybind11.h
netgen-git /usr/include/netgen/pybind11/pytypes.h
netgen-git /usr/include/netgen/pybind11/stl.h
netgen-git /usr/include/netgen/pybind11/stl/
netgen-git /usr/include/netgen/pybind11/stl/filesystem.h
netgen-git /usr/include/netgen/pybind11/stl_bind.h
netgen-git /usr/include/netgen/stlgeom/
netgen-git /usr/include/netgen/stlgeom/meshstlsurface.hpp
netgen-git /usr/include/netgen/stlgeom/stlgeom.hpp
netgen-git /usr/include/netgen/stlgeom/stlline.hpp
netgen-git /usr/include/netgen/stlgeom/stltool.hpp
netgen-git /usr/include/netgen/stlgeom/stltopology.hpp
netgen-git /usr/include/netgen/stlgeom/vsstl.hpp
netgen-git /usr/include/netgen/visualization/
netgen-git /usr/include/netgen/visualization/meshdoc.hpp
netgen-git /usr/include/netgen/visualization/mvdraw.hpp
netgen-git /usr/include/netgen/visualization/vispar.hpp
netgen-git /usr/include/netgen/visualization/visual.hpp
netgen-git /usr/include/netgen/visualization/visual_api.hpp
netgen-git /usr/include/netgen/visualization/vssolution.hpp
netgen-git /usr/lib/
netgen-git /usr/lib/cmake/
netgen-git /usr/lib/cmake/netgen/
netgen-git /usr/lib/cmake/netgen/NetgenConfig.cmake
netgen-git /usr/lib/cmake/netgen/netgen-targets-release.cmake
netgen-git /usr/lib/cmake/netgen/netgen-targets.cmake
netgen-git /usr/lib/netgen/
netgen-git /usr/lib/netgen/libngcore.so
netgen-git /usr/lib/netgen/libnggui.so
netgen-git /usr/lib/netgen/libnglib.so
netgen-git /usr/lib/netgen/libtogl.a
netgen-git /usr/lib/python3.11/
netgen-git /usr/lib/python3.11/site-packages/
netgen-git /usr/lib/python3.11/site-packages/netgen/
netgen-git /usr/lib/python3.11/site-packages/netgen/NgOCC.py
netgen-git /usr/lib/python3.11/site-packages/netgen/__init__.py
netgen-git /usr/lib/python3.11/site-packages/netgen/__main__.py
netgen-git /usr/lib/python3.11/site-packages/netgen/config.py
netgen-git /usr/lib/python3.11/site-packages/netgen/csg.py
netgen-git /usr/lib/python3.11/site-packages/netgen/geom2d.py
netgen-git /usr/lib/python3.11/site-packages/netgen/gui.py
netgen-git /usr/lib/python3.11/site-packages/netgen/libngguipy.so
netgen-git /usr/lib/python3.11/site-packages/netgen/libngpy.so
netgen-git /usr/lib/python3.11/site-packages/netgen/meshing.py
netgen-git /usr/lib/python3.11/site-packages/netgen/occ.py
netgen-git /usr/lib/python3.11/site-packages/netgen/read_gmsh.py
netgen-git /usr/lib/python3.11/site-packages/netgen/read_meshio.py
netgen-git /usr/lib/python3.11/site-packages/netgen/stl.py
netgen-git /usr/lib/python3.11/site-packages/netgen/version.py
netgen-git /usr/lib/python3.11/site-packages/netgen/webgui.py
netgen-git /usr/lib/python3.11/site-packages/pyngcore/
netgen-git /usr/lib/python3.11/site-packages/pyngcore/__init__.py
netgen-git /usr/lib/python3.11/site-packages/pyngcore/pyngcore.cpython-311-x86_64-linux-gnu.so
netgen-git /usr/share/
netgen-git /usr/share/netgen/
netgen-git /usr/share/netgen/boundarycondition.geo
netgen-git /usr/share/netgen/boxcyl.geo
netgen-git /usr/share/netgen/circle_on_cube.geo
netgen-git /usr/share/netgen/cone.geo
netgen-git /usr/share/netgen/cube.geo
netgen-git /usr/share/netgen/cubeandring.geo
netgen-git /usr/share/netgen/cubeandspheres.geo
netgen-git /usr/share/netgen/cubemcyl.geo
netgen-git /usr/share/netgen/cubemsphere.geo
netgen-git /usr/share/netgen/cylinder.geo
netgen-git /usr/share/netgen/cylsphere.geo
netgen-git /usr/share/netgen/doc/
netgen-git /usr/share/netgen/doc/ng4.pdf
netgen-git /usr/share/netgen/ellipsoid.geo
netgen-git /usr/share/netgen/ellipticcyl.geo
netgen-git /usr/share/netgen/extrusion.geo
netgen-git /usr/share/netgen/fichera.geo
netgen-git /usr/share/netgen/frame.step
netgen-git /usr/share/netgen/hinge.stl
netgen-git /usr/share/netgen/lshape3d.geo
netgen-git /usr/share/netgen/manyholes.geo
netgen-git /usr/share/netgen/manyholes2.geo
netgen-git /usr/share/netgen/matrix.geo
netgen-git /usr/share/netgen/ortho.geo
netgen-git /usr/share/netgen/part1.stl
netgen-git /usr/share/netgen/period.geo
netgen-git /usr/share/netgen/py_tutorials/
netgen-git /usr/share/netgen/py_tutorials/exportNeutral.py
netgen-git /usr/share/netgen/py_tutorials/mesh.py
netgen-git /usr/share/netgen/py_tutorials/shaft.geo
netgen-git /usr/share/netgen/revolution.geo
netgen-git /usr/share/netgen/screw.step
netgen-git /usr/share/netgen/sculpture.geo
netgen-git /usr/share/netgen/shaft.geo
netgen-git /usr/share/netgen/shell.geo
netgen-git /usr/share/netgen/sphere.geo
netgen-git /usr/share/netgen/sphereincube.geo
netgen-git /usr/share/netgen/square.in2d
netgen-git /usr/share/netgen/squarecircle.in2d
netgen-git /usr/share/netgen/squarehole.in2d
netgen-git /usr/share/netgen/torus.geo
netgen-git /usr/share/netgen/trafo.geo
netgen-git /usr/share/netgen/twobricks.geo
netgen-git /usr/share/netgen/twocubes.geo
netgen-git /usr/share/netgen/twocyl.geo
```

**Comment by chiboreache** [comment]
![2023-08-16x16:28:11](https://github.com/nortikin/sverchok/assets/16459251/1fa663c4-64f3-424f-964d-b4843bb65825)

nope
