### ISSUE TITLE
ImportError: DLL load failed while importing MeshPart: The specified procedure could not be found.

### ISSUE THREAD

**Issue by TheOtherRealm** [nortikin/sverchok#4974]
## Problem statement
After upgrading to v3.6.1, I am getting: DLL not found .   I also got rid of some old versions that I wasn't using,  that I thought weren't linked to anything, but now I am thinking that they must have been.  Regardless, I have removed and reinstalled Sverchok several times, and keep getting the same error.  I know DLLs have new restrictions in newer Python versions, but everything was working before I downloaded the new version and I'm pretty sure that restriction was in place in the python version used in 3.5.
 
Is the problem installation related? 
Sort of, I can install it but not enable it.  The box is grayed out

For any other issues, or if the installation still failed; Please describe the problem here.

## Steps to reproduce 
1. Upgrade to version 3.6 from 3.5 (with Sverchok installed in the previous version)
2. Get rid of some old versions that were located in a different drive and that should not have been connected to the version you are using
3. Open v3.6
4. Get red error messages in place of nodes
5. Uninstall and reinstall
6. Continue to get errors (see below)

## Expected result
That the extension works and the 'enable' box is not grayed out

## Actual result
I get this error message:

```
Modules Installed (sverchok-master) from 'E:\\Downloads\\sverchok-master-3.zip' into 'C:\\Users\\Someone\\AppData\\Roaming
er Foundation\\Blender\\3.6\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Programs\Blender\stable\blender-3.6.1\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Someone\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\sverchok-master\__init__.py", line 113, in <module>
    imported_modules, node_modules, core = import_sverchok()
  File "C:\Users\Someone\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\sverchok-master\__init__.py", line 106, in import_sverchok
    node_modules_ = core.import_nodes()
  File "C:\Users\Someone\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\sverchok-master\core\__init__.py", line 56, in import_nodes
    import_modules(names, '{}.{}'.format(base_name, category), node_modules)
  File "C:\Users\Someone\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\sverchok-master\core\__init__.py", line 63, in import_modules
    im = importlib.import_module('.{}'.format(m), base)
  File "C:\Programs\Blender\stable\blender-3.6.1\3.6\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Someone\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\sverchok-master\nodes\list_mutators\vd_attr_node_mk2.py", line 15, in <module>
    from sverchok.nodes.viz.viewer_draw_mk4 import SvViewerDrawMk4
  File "C:\Users\Someone\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\sverchok-master\nodes\viz\viewer_draw_mk4.py", line 31, in <module>
    from sverchok.utils.sv_obj_baker import SvObjBakeMK3
  File "C:\Users\Someone\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\sverchok-master\utils\sv_obj_baker.py", line 114, in <module>
    from sverchok.utils.solid import standard_mesher, mefisto_mesher
  File "C:\Users\Someone\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\sverchok-master\utils\solid.py", line 24, in <module>
    import MeshPart
ImportError: DLL load failed while importing MeshPart: The specified procedure could not be found.
```

## Sverchok version
1.2.0
`sverchok-master.zip`, from the installation instructions in the [README.md](https://github.com/nortikin/sverchok/blob/master/README.md) file

**Comment by rastart** [comment]
I confirm this issue.
My Python env is both at 3.10.12:  blender 3.6.2 and freeCAD 0.21.1

I tried also to import MeshPart module from blender python consolle and I get the same error.
I checked the sys.path list and the path to freecad lib is there, so I can import the other freecad modules without problems.
No problem importing MeshPart from FreeCAD consolle. 

Right now I'm not able to solve the problem and to get Sverchok working I disabled the module in the addon folder:
utils/solid.py -> comment line 24 #import MeshPart
nodes/solid_to_mesh_mk2 -> comment line 12/13

**Comment by satabol** [comment]
Do you rebuild FreeCad package for new version of Blender's Python?
