### ISSUE TITLE
Evolver Node Error

### ISSUE THREAD

**Issue by frusaka** [nortikin/sverchok#5076]
## Problem statement
I was trying to use the Evolver node but it seems to run into errors. 

## Steps to reproduce
I used the example from the documentation to make the shortest path that cycles through all points.
![Screenshot (27)](https://github.com/nortikin/sverchok/assets/104128952/0378292e-a492-43ea-9df4-032cdc91f9f8)

## Actual result
When I tried to run it, I got this:
`
Python: Traceback (most recent call last):
  File "C:\Users\Me\Documents\Blender scripts\addons\sverchok-master\utils\sv_operator_mixins.py", line 67, in execute
    response = self.sv_execute(context, node)
  File "C:\Users\Me\Documents\Blender scripts\addons\sverchok-master\nodes\logic\evolver.py", line 558, in sv_execute
    population.evolve()
  File "C:\Users\Me\Documents\Blender scripts\addons\sverchok-master\nodes\logic\evolver.py", line 526, in evolve
    self.population_g = self.get_new_population(actual_population_fitenss, mode)
  File "C:\Users\Me\Documents\Blender scripts\addons\sverchok-master\nodes\logic\evolver.py", line 457, in get_new_population
    weights = 1/np.power(np.array(fitness), self.node.fitness_booster)
TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'
`

## Sverchok version 1.3.0 alpha

**Comment by satabol** [comment]
@frusaka Can you share file with your scheme? I can't reproduce problem.

**Comment by frusaka** [comment]
Just As Is, hit run.
[genes_sv - 1.zip](https://github.com/nortikin/sverchok/files/14074115/genes_sv.-.1.zip)
