### ISSUE TITLE
temporal viewer throws error

### ISSUE THREAD

**Issue by luckychris** [nortikin/sverchok#5078]
## Problem statement

MacBook, Blender 4.1 alpha

i have a few curves and this node tree:

<img width="715" alt="image" src="https://github.com/nortikin/sverchok/assets/232549/58f63c38-2b0b-44c0-8267-a442dffd0c4e">

when connecting that viewer i got this error:

Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/bgl_callback_3dview.py", line 83, in draw_callback_px
    bgl.glEnable(bgl.GL_DEPTH_TEST)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/bgl_callback_3dview.py", line 83, in draw_callback_px
    bgl.glEnable(bgl.GL_DEPTH_TEST)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/bgl_callback_3dview.py", line 83, in draw_callback_px
    bgl.glEnable(bgl.GL_DEPTH_TEST)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/bgl_callback_3dview.py", line 83, in draw_callback_px
    bgl.glEnable(bgl.GL_DEPTH_TEST)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/bgl_callback_3dview.py", line 83, in draw_callback_px
    bgl.glEnable(bgl.GL_DEPTH_TEST)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/bgl_callback_3dview.py", line 83, in draw_callback_px
    bgl.glEnable(bgl.GL_DEPTH_TEST)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/bgl_callback_3dview.py", line 83, in draw_callback_px
    bgl.glEnable(bgl.GL_DEPTH_TEST)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/bgl_callback_3dview.py", line 83, in draw_callback_px
    bgl.glEnable(bgl.GL_DEPTH_TEST)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/bgl_callback_3dview.py", line 83, in draw_callback_px
    bgl.glEnable(bgl.GL_DEPTH_TEST)
TypeError: 'NoneType' object is not callable

Is the problem installation related? then `visit this page first <https://github.com/nortikin/sverchok#troubleshooting-installation-errors>`_.  

For any other issues, or if the installation still failed; Please describe the problem here.

## Steps to reproduce

1. 
2. 
3. 

## Expected result

see the temporal result

What did you expect to see as a result of those steps?

## Actual result

What did you actually get?

## Sverchok version

download from today

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by satabol** [comment]
Hi @luckychris 
Sverchok OpenGL viewers not work in Blender 4.x for a while. But mesh viewers work good.

**Comment by portnov** [comment]
If this is still actual: update sverchok to latest version (master or last release), it should be working now.
