### ISSUE TITLE
Blender 4.1 Official and latest SVerchok on macOS not working

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#5096]
Installed the latest SV zip addon, and not working on Blender 4.1, macOS with error below:
```
Traceback (most recent call last):
  File "/Applications/Blender 41 STABLE/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 444, in enable
    mod.register()
  File "/Users/jimmygunawan/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/__init__.py", line 120, in register
    core.sv_register_modules(imported_modules)
  File "/Users/jimmygunawan/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/core/__init__.py", line 37, in sv_register_modules
    m.register()
  File "/Users/jimmygunawan/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/presets.py", line 1019, in register
    preset.make_add_operator()
  File "/Users/jimmygunawan/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/presets.py", line 276, in make_add_operator
    preset_name = self.name if not self.description else self.description
                                   ^^^^^^^^^^^^^^^^
  File "/Users/jimmygunawan/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/presets.py", line 229, in description
    return self.meta.get("description", None)
           ^^^^^^^^^
  File "/Users/jimmygunawan/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/presets.py", line 219, in meta
    data = self.data
           ^^^^^^^^^
  File "/Users/jimmygunawan/Library/Application Support/Blender/4.1/scripts/addons/sverchok-master/ui/presets.py", line 211, in data
    data = json.loads(data)
           ^^^^^^^^^^^^^^^^
  File "/Applications/Blender 41 STABLE/Blender.app/Contents/Resources/4.1/python/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender 41 STABLE/Blender.app/Contents/Resources/4.1/python/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender 41 STABLE/Blender.app/Contents/Resources/4.1/python/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 197 column 13 (char 4950)


```

**Comment by satabol** [comment]
Did you load latest zip from Release or master?
This error shown at start of Blender of in some scheme? Can you do screenshot?

**Comment by enzyme69** [comment]
I load zip from Master as usual. 

This error is shown when I tick to load SVerchok. So it does not load at all.

**Comment by enzyme69** [comment]
![Uploading Screenshot 2024-04-07 at 11.00.10 AM.png…]()

**Comment by satabol** [comment]
Can you expand dialog with errors to show line numbers? Many line numbers are hidden now.

**Comment by enzyme69** [comment]
<img width="1479" alt="Screenshot 2024-04-08 at 9 10 29 AM" src="https://github.com/nortikin/sverchok/assets/3952687/6ba53f41-b622-440e-9c6f-a5cfdfe4ce95">

**Comment by satabol** [comment]
Hi @enzyme69. I have no MacOS. I try my friend MacBook but got another exception. I need time to reproduce.

**Comment by enzyme69** [comment]
Thank you for looking into this, hope it could work with latest Blender 4.1 -- no rush

**Comment by enzyme69** [comment]
This seems to be issue with macOS running on Mac M chip machine. 

My intel macOS with latest SV and Blender seems to work.

**Comment by satabol** [comment]
Is it with some library? Can you default SV run ?

**Comment by enzyme69** [comment]
Sverchok won't load at all with latest macOS and Blender 4.1x. No default won't run. Need to recompile with ARM.
