### ISSUE TITLE
Error enabling latest release (1.3.0: Blender_4.2)

### ISSUE THREAD

**Issue by Andrej730** [nortikin/sverchok#5160]
@nortikin

Unable to enable the latest Blender release:
1) Download release from https://github.com/nortikin/sverchok/archive/refs/tags/4.2.zip
2) Install it in Blender 4.2 (you can just drag'n'drop the zip archive)
3) See the error.

```
Error: Python: Traceback (most recent call last):
  File "\Blender\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 1388, in execute
    cmd_batch = self.exec_command_iter(is_modal)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Blender\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2452, in exec_command_iter
    self.exec_legacy(source_filepath)
  File "\Blender\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2583, in exec_legacy
    bpy.types.PREFERENCES_OT_addon_install.execute(self, bpy.context)
  File "\Blender\4.2\scripts\startup\bl_operators\userpref.py", line 821, in execute
    bpy.ops.preferences.addon_enable(module=mod.__name__)
  File "\Blender\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: No module named 'sverchok-4'
```

Workarounds:
- if you already installed sverchok and got this error, go to '%appdata%\Blender Foundation\Blender\4.2\scripts\addons' and rename 'sverchok-4.2' to 'sverchok'
- if you haven't installed sverchok yet, open 'sverchok-4.2.zip' archive you downloaded and rename 'sverchok-4.2' foder inside to 'sverchok', then install it.

**Comment by nortikin** [comment]
https://t.me/sverchok3d/902 have made 4.2 zip for windows.

**Comment by portnov** [comment]
I think we have to update installation instructions for cases when you download zips from "releases" section. The instructions should be actually the same as you described.

The only other way for us is to manually prepare zip files with already renamed directory and attach them to release page; but default zip file is always there by default, AFAIK we can not disable it; so there will be two zip files on release page, correct one and incorrect, people will confuse them :/

**Comment by Andrej730** [comment]
Yeah, it's not possible to disable default .zip as it's part of the github releases design but if there would be release .zip attached (which is the same zip, just with a folder renamed indeed), it would appear first and users would try it first.

I think it's worth adding because Releases is probably the main resource that's used to download the build and users have expectations (from experience with other repositories) that release contains archive that's ready to use without any other manipulations. Otherwise, it can be a constant source of confusion for new users (and a papercut for more experienced ones).

**Comment by tetov** [comment]
I just ran into this, and I'd like to suggest using a github action to attach a zip with correct directory name that could run on release or tag. Would that be of interest? I could open a PR if so.

**Comment by Andrej730** [comment]
Releases occur not that often I guess, so for now solution would to simply attach the archive with the renamed folder to https://github.com/nortikin/sverchok/releases/tag/4.2.

I've uploaded fixed archive and pinned it to this first post of this issue. Hopefully, it will help some users.
