### ISSUE TITLE
keymaps registration error when running `blender -b --python-console`

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#742]
http://www.dalaifelinto.com/?p=1153 reminds us that blender can also be accessed as a python console.

```python
blender -b --python-console
```

Sverchok causes an exception, and I know why this happens, and am willing to fix it. Here i want to mention that this happens and we know about it.

```python
Exception in module register(): '~/sverchok/__init__.py'
Traceback (most recent call last):
  File "~/blender/2.76/scripts/modules/addon_utils.py", line 343, in enable
    mod.register()
  File "~/sverchok/__init__.py", line 146, in register
    m.register()
  File "~/sverchok/utils/text_editor_plugins.py", line 409, in register
    add_keymap()
  File "~/sverchok/utils/text_editor_plugins.py", line 355, in add_keymap
    text_editor = wm.keyconfigs.user.keymaps.get('Text')
AttributeError: 'NoneType' object has no attribute 'keymaps'

```
in background mode there's no such thing has `keyconfigs.user`, because headless mode doesn't need key combos.

Not a serious bug, but worth fixing.

**Comment by ly29** [comment]
Yeah, nice usage.

**Comment by nortikin** [comment]
keymaps appears with error many time

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/master/utils/text_editor_plugins.py  can be done much nicer. I'm not sure when this was added the bpy docs addon tutorial, but we should certainly follow this format

http://www.blender.org/api/blender_python_api_current/info_tutorial_addon.html#keymap
```python
# store keymaps here to access after registration
addon_keymaps = []

def register():

    # handle the keymap
    wm = bpy.context.window_manager
    km = wm.keyconfigs.addon.keymaps.new(name='Object Mode', space_type='EMPTY')

    kmi = km.keymap_items.new(ObjectCursorArray.bl_idname, 'SPACE', 'PRESS', ctrl=True, shift=True)
    kmi.properties.total = 4

    addon_keymaps.append((km, kmi))


def unregister():

    # handle the keymap
    for km, kmi in addon_keymaps:
        km.keymap_items.remove(kmi)
    addon_keymaps.clear()
```

**Comment by zeffii** [comment]
maybe something like this:
```python
# store keymaps here to access after registration
addon_keymaps = []


def add_keymap():

    # handle the keymap
    wm = bpy.context.window_manager
    kc = wm.keyconfigs.addon

    if not kc:
        print('no keymap found. that\'s ok')
        return

    km = wm.keyconfigs.addon.keymaps.new(name='Text', space_type='TEXT_EDITOR')
    keymaps = km.keymap_items

    if 'noderefresh_from_texteditor' in dir(bpy.ops.text):
        ''' SHORTCUT 1 Node Refresh: Ctrl + Return '''
        ident_str = 'text.noderefresh_from_texteditor'
        if not (ident_str in keymaps):
            new_shortcut = keymaps.new(ident_str, 'RET', 'PRESS', ctrl=1, head=0)
            addon_keymaps.append((km, new_shortcut))

        ''' SHORTCUT 2 Show svplugMenu Ctrl + I (no text selected) '''
        new_shortcut = keymaps.new('wm.call_menu', 'I', 'PRESS', ctrl=1, head=0)
        new_shortcut.properties.name = 'TEXT_MT_svplug_menu'
        addon_keymaps.append((km, new_shortcut))

        print('added keyboard items to Text Editor.')


def remove_keymap():

    for km, kmi in addon_keymaps:
        km.keymap_items.remove(kmi)
    addon_keymaps.clear()


def register():
    bpy.utils.register_class(BasicTextMenu)
    bpy.utils.register_class(SvVarnamesToSockets)
    bpy.utils.register_class(SvLangConverter)
    bpy.utils.register_class(SvNodeRefreshFromTextEditor)
    add_keymap()


def unregister():
    remove_keymap()
    bpy.utils.unregister_class(SvVarnamesToSockets)
    bpy.utils.unregister_class(SvLangConverter)
    bpy.utils.unregister_class(BasicTextMenu)
    bpy.utils.unregister_class(SvNodeRefreshFromTextEditor)
```

**Comment by zeffii** [comment]
fixed with this commit: https://github.com/nortikin/sverchok/commit/fa1371ecf37d50c5ef81b0d9a1e048763964a6a8
