### ISSUE TITLE
Can't SV import/export layouts containing Groups

### ISSUE THREAD

**Issue by procedural** [nortikin/sverchok#782]
I have a node, Vectors to Lines:

![image](https://cloud.githubusercontent.com/assets/1072168/15757682/74c6d16e-290f-11e6-9558-d0df6f75366b.png)

I exported it with "SV import/export"'s Export button:

https://gist.github.com/procedural/697ced99dc1c59ec0c6331e31a68876a

When I try to import it, I get this error:

![image](https://cloud.githubusercontent.com/assets/1072168/15757651/54c8b9f4-290f-11e6-9ab7-fb06908f06b4.png)

So... Maybe there's another way to export and import a grouped node in Sverchok?

Thanks!

Blender 2.77a, Sverchok master branch

**Comment by nortikin** [comment]
group node is alpha, not even beta stage, please, not use it for import-export. better to use frames for now.

**Comment by procedural** [comment]
@nortikin oh well :) Just wanted to export a node from one scene to another...

**Comment by zeffii** [comment]
if you go into the group and export from there does it work?

It's been a long time since we worked on this, and the 'groups' implementation was never really nailed.

**Comment by zeffii** [comment]
ok..same error. 
```python
location: <unknown location>:-1
############ 0.060
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 582, in execute
    import_tree(ng, self.filepath)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 463, in import_tree
    generate_layout(fullpath, nodes_json)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 293, in generate_layout
    import_tree(group_ng, '', groups_to_import[name])
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 466, in import_tree
    generate_layout('', nodes_json)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 282, in generate_layout
    print('#' * 12, nodes_json['export_version'])
TypeError: string indices must be integers

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by zeffii** [comment]
hmmm.. seems like the group node itself needs some work for updating imported nodes
```python
    def generate_layout(fullpath, nodes_json):

        if isinstance(nodes_json, str):
            print('groups are not yet supported in IO')
            nodes_json = json.loads(nodes_json + '\n')
            print('found:', nodes_json['export_version'])

        print('#' * 12, nodes_json['export_version'])
```
for instance -- this again correctly makes the json string into a searchable dict.. of sorts..there's a lot about this IO that i can't remember or never understood :)  (I coded the first parts and @ly29 contributed the 'group' node / IO code for that node. )

**Comment by ly29** [comment]
It won't work with the current implementation of Sverchok node groups, or probably nodes




On Fri, Jun 3, 2016 at 7:31 AM -0700, "Dealga McArdle" <notifications@github.com<mailto:notifications@github.com>> wrote:


ok..same error.

location: <unknown location>:-1
############ 0.060
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 582, in execute
    import_tree(ng, self.filepath)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 463, in import_tree
    generate_layout(fullpath, nodes_json)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 293, in generate_layout
    import_tree(group_ng, '', groups_to_import[name])
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 466, in import_tree
    generate_layout('', nodes_json)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 282, in generate_layout
    print('#' * 12, nodes_json['export_version'])
TypeError: string indices must be integers

location: <unknown location>:-1

location: <unknown location>:-1

-

**Comment by zeffii** [comment]
@procedural - sorry , this feature is not something we have put much time into collectively. Additionally,  pynodes api doesn't seem to provide a way to change the screen to show that we are viewing a grouped node system, a "Go to Parent" icon, like cycles does:  (and I think this omission makes it all a bit more difficult to use)

![image](https://cloud.githubusercontent.com/assets/619340/15786630/f5d7fb12-29bd-11e6-9686-11a6e7fae832.png)

**Comment by zeffii** [comment]
node_group upon import also doesn't generate sockets on the external `node_group` node

**Comment by zeffii** [comment]
closing this as it refers to the old implementation - the new implementation should have working iojson storing groups soon.
